### ISSUE TITLE
Aggregate Schedule A receipts

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1006]
* [ ] By contribution size
    * Cut points?

@noahmanger which other aggregates (if any) are we going to want?

**Comment by LindsayYoung** [comment]
Amount is not necessary because that is on the summary pages.  
 
For committees,  especially candidate committees it is good to figure out from schedule As
 -  Totals by state
 -  Totals by zipcode
 -  Totals given to other groups with FEC ids
 -  Donations by size - totaling donation in a given range, the under $200 bucket comes from unitemized summary filings. 
   The FEC's map currently uses:
      $200 and Under
      $200.01 - $499
      $500 - $999
      $1000 - $1999
      $2000 and Over

 - For contributions by party, it makes more sense to use aggregates.

**Comment by jmcarp** [comment]
Amount = size. I'll revise the issue.

**Comment by noahmanger** [comment]
Great. This all makes sense to me. Though point of clarification, @LindsayYoung do you mean "Totals *received from* other groups with FEC ids"? Might we want to total those up by certain type / designation / org type? Not sure what the distinctions would be, but I could see it being helpful.

**Comment by LindsayYoung** [comment]
For the website, I was thinking listing the top 10 groups that fund a committee. It is possible to then group them by type, but there are a lot of other features I think we should spend our time on first. But tell me if you have a really good use case in mind. 

For, the API would want to have more detailed PAC to PAC transfer information, not just top 10. 

It would be much more difficult to do top individual donors within a committee, we could talk about that, but that is a separate, longer conversation.

**Comment by jmcarp** [comment]
Done a while back.
