### ISSUE TITLE
Find records by contributor name

### ISSUE THREAD

**Issue by morninj** [18F/openFEC#1049]
It would be really useful to have an API method to retrieve contribution records by donor name—i.e., a programmatic interface along the lines of https://www.opensecrets.org/indivs/

**Comment by LindsayYoung** [comment]
Agreed! That information is found in Schedule A and will have its own endpoint with name searching capabilities soon. 

Thank you for taking your time to file an issue!

**Comment by morninj** [comment]
Awesome. How can I help?

I'm working on an app that needs this functionality. I'm deciding whether to load the raw data into my own database or wait for the API functionality. Do you have a rough timeframe? I'm happy to pitch in.

**Comment by LindsayYoung** [comment]
Since the app is new, I would be cautious in case there are undiscovered bugs. I would recommend going off raw data, but It would be a great opportunity to do some more checking. 

We have schedule A, B and filings on our staging site, and we hope to release it soon. Some queries are still slow. If you want to check it out and give us feed back, that would be great!

Also, I have had a project to compare the API to the bulk data on my back burner, but I haven't been able to give it the attention it needs to get it running, https://github.com/dmil/iCorruptionHack/tree/fec_api (Most of the project has been written by @dmil )

**Comment by dmil** [comment]
@LindsayYoung @morninj its been on my back-burner too, but I'd love to get it up and running. also willing to pitch in. congrats on launch!

**Comment by LindsayYoung** [comment]
Thanks Dhrumil!

I love "OFEC Check"  and I really want to finish that, at least for the totals data- maybe I should plan it into my next sprint. I have been going at 110% and I am dying to have some extra time to work on it.

**Comment by morninj** [comment]
Thanks! I searched around but couldn't find the staging site. Do you have a link?

**Comment by LindsayYoung** [comment]
Sorry for the delayed reply @morninj we now have that going on the API https://api.open.fec.gov/developers#!/schedules/get_schedules_schedule_a

Keep in mind, the project is still in beta, so there may be errors or omissions we don't know about. Please file a ticket if you notice anything amiss.

**Comment by morninj** [comment]
Cool, thanks! I won't be able to try this until after the CA bar exam (7/30), but I'll take a look then and let you know if I find any issues.

**Comment by LindsayYoung** [comment]
Good luck on the bar!
