### ISSUE TITLE
possible gov shutdown language

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1225]
> NOTICE: Due to the lapse in government funding, the information on this website may not be up to date, the transactions submitted via the website may not be processed, and the agency may not be able to respond to inquiries until appropriations are enacted. For more information, please visit [insert something here if we have something].

@emileighoutlaw whaddya think?

**Comment by emileighoutlaw** [comment]
Love it. Tiny notes:

NOTICE: Due to the lapse in [government funding](link to appropriate OPM release about shutdown), the information on this website may not be up to date, and transactions submitted via the website may not be processed. FEC and 18F won't be able to respond to inquiries until the shutdown ends. 

^^Can we say shutdown? I think people will understand that more than "until appropriations are enacted." But either will work. 

I also like saying that we (18F and FEC) won't be able to respond rather than just "the agency." Seems more human?

**Comment by leahbannon** [comment]
Looks good to me, but I'm thinking we can actually get rid of the "transactions" language because people won't be filing anything with beta.fect.gov. How about:

> NOTICE: Due to the lapse in government funding, the information on this website may not be up to date. In addition, FEC and 18F won't be able to respond to inquiries until the shutdown ends.

**Comment by emileighoutlaw** [comment]
Awesome! Looks good to me.

**Comment by leahbannon** [comment]
@amykort --> what do you think about this for the warning that we discussed if there's a shutdown?

**Comment by AmyKort** [comment]
Looks good to me.

**Comment by noahmanger** [comment]
We no longer need this! Closing.
