### ISSUE TITLE
Presidential data error

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1251]
On the election search page, we're now getting two results for US President, one of which lists Romney as the current officholder:

<img width="560" alt="screen shot 2015-10-05 at 2 08 40 pm" src="https://cloud.githubusercontent.com/assets/1696495/10294401/d5f17016-6b6e-11e5-83cb-fa5114310c67.png">

Seems to be an issue with the data as our code hasn't changed recently.

**Comment by LindsayYoung** [comment]
Hey @PaulClark2

We are seeing 2 presidents in the database because we determine who has seats by looking at who is listed as an incumbent. Here is the [sql script](https://github.com/18F/openFEC/blob/develop/data/sql_updates/create_election_outcome_view.sql) that calculates that. 

Romney's most recent F2Z lists him as an incumbent, can you change that please?

Here it is on the staging server:
```
select * from dimcandproperties where candproperties_sk=10101186;
```
 candproperties_sk | cand_sk  | form_sk | form_tp |  cand_id  | election_yr |            cand_nm            | cand_suffix | cand_prefix | cand_m_nm | cand_f_nm |       cand_l_nm       |           cand_st1           |            cand_st2             | cand_city | cand_st | cand_zip | cand_status_cd |       cand_status_desc        | cand_ici_cd |                         cand_ici_desc                         | prim_pers_funds_decl | gen_pers_funds_decl | receipt_dt | effective_end_date |      load_date      |     expire_date     |         pg_date         
-------------------|----------|---------|---------|-----------|-------------|-------------------------------|-------------|-------------|-----------|-----------|-----------------------|------------------------------|---------------------------------|-----------|---------|----------|----------------|-------------------------------|-------------|---------------------------------------------------------------|----------------------|---------------------|------------|--------------------|---------------------|---------------------|-------------------------
          10101186 | 10016248 | 4945912 | F2Z     | P80003353 |        2012 | ROMNEY, MITT / PAUL D. RYAN |             |             |           | MITT      | ROMNEY / PAUL D. RYAN | C/O RED CURVE SOLUTIONS, LLC | 500 CUMMINGS CENTER, SUITE 4400 | BEVERLY   | MA      | 01915    | C              |                  | I           |               |                 0.00 |                0.00 | 2015-10-02 |                    | 2015-10-03 00:30:21 |             | 2015-10-03 01:25:24.404

(The ici_code is fine in `dimcandstatusici`)

Thanks again!

**Comment by PaulClark2** [comment]
SUB_ID | CHG_DEL_ID | FORM_TP | CAND_ID | CAND_ICI | PROCESSING_STATUS
-------|------------|---------|---------|----------|------------------
1100220150017909407 | | F2ZA |P80003353 | I| 12
1100520150017922713 | 1100220150017909407 | F2ZA | P80003353 | C | 2

**Comment by PaulClark2** [comment]
I entered this change transaction too late yesterday.   We won't see this change until Wednesday morning.

**Comment by PaulClark2** [comment]
This has been resolved

![untitled](https://cloud.githubusercontent.com/assets/11817734/10336344/26b43e5e-6cc6-11e5-9b94-9ec345c15fc7.png)

**Comment by LindsayYoung** [comment]
Yep, thanks!
