### ISSUE TITLE
A list of the pre-launch tech miscellany

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1279]
This is a working/planning issue for notes... (list items will likely get replaced with links to issues)

- final accessibility review
- more load testing?
- code quality reviewing

**Comment by noahmanger** [comment]
I don't think we need another accessibility review. We haven't added any new features since the last one.

**Comment by wluoFEC** [comment]
Do we need to have a QA test for the beta.fec.gov to make sure the latest code has been deployed?  I did a quick check this morning.  Search by zip code is not working on beta.fec.gov.  Feedback box and contact us are also not working.

**Comment by LindsayYoung** [comment]
Latest code is at https://fec-proxy.18f.gov/ 

We should do a code freeze in the next few days and that would be a good time to update beta.fec.gov and then after the code freeze, we would only add hotfixes if bugs were discovered, so that way, the beta would be automatically up to date. At that point, additional features could continue on develop.

**Comment by wluoFEC** [comment]
got it.  thanks

**Comment by jenniferthibault** [comment]
Since we're now post-launch, closing this issue
