### ISSUE TITLE
Missing a candidate

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1299]
@jmcarp:  @lindsay   

Candidate H6NY19169 (cmte id C00580415) isn't showing up with numbers. He should have numbers. I looked in the warehouse and he has filed a form 3 and his candidate id and committee id are linked.    
https://fec-proxy.18f.gov/data/candidate/H6NY19169/

**Comment by jmcarp** [comment]
It looks like we aren't linking this candidate to his principal committee because the relevant rows in `dimcmtetpdsgn` are missing values for `cmte_dsgn`:

```
fec=> select cmte_dsgn, * from dimcmteproperties dcp join dimcmtetpdsgn dd on dcp.cmte_sk = dd.cmte_sk where dcp.cmte_id = 'C00580415';
 cmte_dsgn | cmteproperties_sk | cmte_sk  | form_sk | form_tp |  cmte_id  |                  cmte_nm                   |  cmte_st
-----------+-------------------+----------+---------+---------+-----------+--------------------------------------------+---------
           |          10187298 | 10058827 | 4945861 | F1      | C00580415 | FASO FOR CONGRESS                          | PO BOX 4
           |          10184197 | 10058827 | 4918938 | F1      | C00580415 | FASO FOR CONGRESS -- EXPLORATORY COMMITTEE | PO BOX 4
(2 rows)
```

Our logic checks that principal committees are designated as principal, but all of this candidate's designations are `NULL`, so we don't show any principal committees for him.

This should be fixed when we switch from the `dimcmtetpdsgn` table to `cmte_valid_fec_yr`, but we're not planning to make that switch until after launch--it's pretty close to the wire for a major data change like that. In the meantime, we could try to fix the relevant rows in `dimcmtetpdsgn`, or we can change our `JOIN` so that we verify principal committee status based on `dimlinkages` (which is correct in this case) rather than `dimcmtetpdsgn` (which is incorrect).

What do you think @jwchumley @PaulClark2 @LindsayYoung?

**Comment by jmcarp** [comment]
Quick follow-up: the missing `cmte_dsgn` values are also responsible for this committee not showing any numbers. We use the committee designation to decide which fact table to use to look up reports--and since we don't have a designation value at all for this committee, we wind up looking in the wrong fact table.

**Comment by jwchumley** [comment]
I think if you can go ahead and update it to 'P' for now while I figure 
out why it didn't get to you that would be helpful.

Jeff

**Comment by jmcarp** [comment]
Just to be clear, do you want us to manually set the designation for this candidate in `dimcmtetpdsgn`?

**Comment by jwchumley** [comment]
Well, if you can take care of it easily programmatically that's fine. I 
was just thinking this close to the demo it might be best not to make 
changes. What do you think?

**Comment by jmcarp** [comment]
Would it be possible to fix the offending records in `dimcmteproperties` on the FEC side? I talked about this with @LindsayYoung, and we'd prefer not to overwrite any data on our side if at all possible.

@jwchumley @PaulClark2

**Comment by LindsayYoung** [comment]
I was just writing the same thing. The last time we tried to fix thinks on our end they got messed up when FEC fixed it for real in the data warehouse.

**Comment by jwchumley** [comment]
I think so. Let me make sure my change triggers and update to you.

**Comment by LindsayYoung** [comment]
Thank you Jeff!

**Comment by jwchumley** [comment]
Paul has already set up an update for tonight. We'll check in the morning.

**Comment by LindsayYoung** [comment]
I see him now:
https://beta.fec.gov/data/candidate/H6NY19169/
https://fec-proxy.18f.gov/data/candidate/H6NY19169/
