### ISSUE TITLE
So users can find transactions easier, allow column sorting in disbursement and receipt searches

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1307]
If Possible before Demo but not critical:
Most of the columns in the transaction searches need to be sortable. If it isn't too big a deal then at least the disbursement recipient name  and committee name should be sortable. If it is too big a deal I can work around it for the demo.

**Comment by noahmanger** [comment]
As far as I know, this is constrained by the number of records we're dealing with. Allowing full-text sort on some of these columns would be a big knock on performance. 

I know it's something that we'd all like to see eventually, but will take some time to figure out how to do it right.

**Comment by jmcarp** [comment]
A few follow-ups:
* For receipts, sorting on contributor is a little complicated, since we get the contributor names directly from `sched_a` in some cases, but in others we join to the committees table to get the name. If we always want to use the name from the transaction table and not join against other tables, as we've been discussing in #1306, this would be simpler.
* Sorting on columns in a related table is necessarily going to be more expensive than sorting on columns in the table we're querying. So to sort schedule As by recipient name, we either add a join on a committee table, or we denormalize and copy recipient committee names directly into our transaction table when we build it. Neither is difficult, but today probably isn't the day to roll this out.

**Comment by jwchumley** [comment]
agreed

**Comment by noahmanger** [comment]
Story card: https://18f.storiesonboard.com/m/fec/!card/QXvlFqCgemgHGznTzA9tmQ

**Comment by leahbannon** [comment]
We should also include IEs in this now if possible.
