### ISSUE TITLE
Bug: Cycle Select info disclaimer blocks use of cycle select

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1341]
In a usability test with a user this morning, a user was attempting to select a different cycle but was unable to because our "under consideration" notice blocks it. 

![dropdown](https://cloud.githubusercontent.com/assets/474916/11001431/2ae0c6ca-8475-11e5-9687-6ea6aa82fb17.gif)

This was in IE (not sure what version), but I replicated that it is also is hard to get to in Chrome (though not impossible).

**Comment by jenniferthibault** [comment]
Ah—I'm suspecting that the hover effect is on the whole div. If it is, (as evidenced by being able to activate the tooltip when your mouse is over the dropdown) we should change it so that the hover state only activates when you're over the "View Data for:" and the icon. If that still interferes, we could just make the icon the hover activator. 

Thoughts, @noahmanger ?

**Comment by emileighoutlaw** [comment]
Looking at this, I'm also thinking we should consider trimming the content substantially. 

I like:
> This site groups data in two-year periods.
> We're working on new views that will let you personalize this timespan, but we need your input. See our designs on GitHub, and let us know what you think.

I took off the last line that said users could also leave input at the bottom of the page on the feedback tool because:
- As far as I know no one has left feedback that way, and
- The text is so lengthy right now it's intimidating. I think cutting the line about the feedback button will *increase* our chance of getting meaningful feedback.

We could port over the first section of original text to the beginning of the GitHub issue:
> betaFEC groups data in two-year periods — if a candidate or committee has been active more than two years, the website won't show all their data.

**Comment by LindsayYoung** [comment]
Maybe:
betaFEC groups data in two-year periods for you to choose from. Feel free to give us feedback on this by clicking the feedback button on the bottom right of the page.

I'm not a fan of the wording "If a candidate or committee has been active more than two years, the website won't show all their data." Because we do show their data, you can select any 2-year period we have records for that candidate or committee.

**Comment by onezerojeremy** [comment]
Solid point, Lindsay. 

Otherwise I like what Emileigh has here.

**Comment by emileighoutlaw** [comment]
Yep. Excellent point, Lindsay.

**Comment by noahmanger** [comment]
Cool cool. So the reason that this bug happens has to do with the way that IE apparently associates `label`s with their `input`s. It interprets a hover over an input as a hover over it's associated label, which is completely non-standard and very annoying. 

Do we want to tackle the language update and updated code to fix this bug in a hotfix? Or just wait until we implement the new cycle select entirely?

**Comment by emileighoutlaw** [comment]
Taking out the troublesome section that Lindsay noted, I think we're good to try out the below language when we fix the bug. 

> This site groups data in two-year periods.
> We're working on new views that will let you personalize this timespan, but we need your input. See    
> our designs on GitHub, and let us know what you think.

**Comment by jenniferthibault** [comment]
@noahmanger it looks like the language @emileighoutlaw is recommending is specific to the pre-cycle select state, so I'm guessing hot fix?

After the cycle select is implemented, we will need new language for the tooltip, or we should eliminate the tooltip entirely. The tooltip's main purpose here was to introduce the limitations of the current state, but those limitations wouldn't exist with the cycle select in place. So we'd either need to change language to explain the functionality (I'm hunching that's not necessary), or eliminate it.

**Comment by noahmanger** [comment]
Do we still care about trimming the language? We've decided on a direction, so I don't think it's necessary.

**Comment by jenniferthibault** [comment]
Don't think so—I'd vote for removing the tooltip here entirely.
