### ISSUE TITLE
Discussion: Expiring cached data downloads

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1377]
For performance reasons, CSV files generated for data downloads are temporarily cached in S3, so that if several users request the same download around the same time, we only generate the file once. But we still have to decide how, and how often, to clear the cache. A few options:

* Delete all files in the cache after the nightly data update. This has the advantage of offering users relatively fresh data for all downloads, but it couples our cache lifetime to the frequency of the data update. If we want to be able to cache downloads for longer than a day, this wouldn't work well.
* Tell S3 to delete cached files after a fixed expiration time--for example, one week. This has the advantage of being very simple: we set an expiration time for files in our S3 bucket, and Amazon takes care of the rest. We can also expire cache objects on arbitrary schedules, without linking them to our data update frequency.

Thoughts @LindsayYoung @noahmanger @jenniferthibault?

**Comment by jmcarp** [comment]
FWIW, I would have a slight preference for the second option, but I'm open to both, and either would be quick to implement.

**Comment by jenniferthibault** [comment]
So...here's a scenario I'm thinking of that will help me understand the differences.

It's 24 hours after a filing deadline, and a journalist goes to betaFEC to download the latest data. 
In option 1: the data they download is up to date within the past 24 hours (?) 
In option 2: If anyone had downloaded that data set within the last week, this journalist would receive that download (and that might not contain the recent filings) (?)

Is that accurate? The concern I'm getting at is that folks won't be able to get the most recent data.

**Comment by jmcarp** [comment]
It's a little more complicated than that, but yes, we're talking about a trade-off between performance and data freshness. Large data downloads are going to take significant time to build, and will impose significant load on the database, so I think we want to be very careful about how much work we allow them to do. It's also more palatable to go from a seven-day cache to a one-day cache than the reverse--it wouldn't be ideal to start with a one-day cache, discover that performance is too slow, and then switch to a longer caching period.

If it's critical for data downloads to be as fresh as possible, we might want to look into a dedicated read replica just for downloads: https://aws.amazon.com/rds/details/read-replicas/, so that heavy load on the download feature wouldn't slow down the rest of the site. Of course, this would raise infrastructure costs.

**Comment by LindsayYoung** [comment]
@jenniferthibault I love how you are thinking about this and I would like this to be a better resource for reporters too. I do think the main sticking point for reporters is going to be the timeliness of the data rather than the number of rows in a custom download. 

Realistically, this is not a good resource for reporting on time-sensitive stuff. I would love it to be, but  the FEC would need to push data to us and we would need to update the API about every hour.  (At least for transaction data and high level totals, I think the maps and other breakdowns are still fine to be calculated once a day, though that does introduce inconsistency).

Moreover, I believe that 65,000 rows is the most you can get to load in an excel document. That means that if we are trying to improve the experience of most reporters, having more than a million downloads requires database skills. My assumption is that most people who have database skills could be able to use the API and don't need this. That assumption won't fit everyone, and for that subset of people, they can break their query down in to pieces, like using date ranges to subdivide the queries.  

I don't mean to harp on our current shortcomings. This is really good information for deep dives, that are less time sensitive. For that kind of work, you are probably (though not always) looking for particular donors or committees etc.  These stories are harder to find, take more time and can continue between the onslaught during reporting deadlines.   

The API is good for people that want to replace infrastructure from the weekly to daily updates, they can do that with the API and just request the new information coming in. This is not something you would want to do manually. 

Currently, the reporting that takes place closest to the deadline will come from the e-filings feed which updates on the hour or 1/2 hour- I don't precisely remember. We currently don't have access to that.

As for what people are looking for first, most often it is how much money is raised, which you don't need a million records for, you need to look at the summary numbers. That is usually followed by interesting transactions, donors which you do need to browse the transactions for.

Happy to reach out to some reporting people and verify these assumptions if that would be helpful.

**Comment by jenniferthibault** [comment]
Thank you both for helping me understand better!

From the perspective of explaining how the system works (totally difference from the performance of the system, I know), there would be a nice pairing if we could explain the data on the site as updated every night. It feels complicated to say that the data is updated every night, but downloads are updated every seven days. I don't know if this is a compelling enough point to base the choice around entirely, but it does make me lean toward the first option. 

Thanks for inviting me to discuss and for helping me understand more! At this point though, I don't have a strong *informed* opinion, so don't let me influence it too much. It's all you folks!

**Comment by LindsayYoung** [comment]
I definitely like the idea that everything we do will be transparent and people should know what they are getting!

**Comment by noahmanger** [comment]
I'm with Jen in that I think it's important to have parity between the data on the app and the data that one would download. It would be really confusing to have data show up on the the site but not in a downloaded file.

**Comment by LindsayYoung** [comment]
I think that option 1 is ideal, but if we think it would impact performance, we can start with something that is sub-optimal and iterate.

Perhaps we could make some tables after reload that we know people are particularly interested in and have a featured downloads page with links? The current FEC map views have downloads they make nightly* for all presidential, all house etc.  

*I think it is nightly for the presidential resources, but I could be wrong.

**Comment by jmcarp** [comment]
The data download patch implements the first option for now. It'll probably be easier to handle performance issues by limiting download sizes than by caching files for longer.
