### ISSUE TITLE
Restrict data download resources

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1395]
To capture a point from Slack yesterday: as currently implemented, data downloads for itemized receipts and disbursements are too slow and impose too much load on the database to enable in production. If we want to consider enabling bulk downloads for these resources, we would need to implement a few backend improvements first:

* Partition receipts and disbursements by year or two-year period
* Serve data downloads from a separate replica of the database

To be clear, the second point would increase infrastructure costs, probably by a few hundred dollars a month.

In the meantime, I'll implement a whitelist of safe download resources. For now, that will include candidate, committees, and filings.

cc @LindsayYoung @noahmanger @leahbannon

**Comment by noahmanger** [comment]
Sounds like the right approach for now. Being able to download itemized receipts and disbursements is going to be a killer feature, so I'd definitely bump this up in priority.

What's the trade-off in partitioning receipts and disbursements? 

And is this performance an issue even if you're working with a small number of records (say, 1,000 instead of 100,000)?
