### ISSUE TITLE
Candidate H6TX25179 missing from election 2016 TX House 25

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1408]
On this candidate page https://beta.fec.gov/data/candidate/H6TX25179/ the button for 2016 TX House 25 election is showing up, but when I click on that [link for the election page](https://beta.fec.gov/data/elections/house/TX/25/2016/), she doesn't appear (only incumbent Williams, Roger appears).

**Comment by jmcarp** [comment]
Thanks for flagging this. At the moment, only candidates with one or more financial reports are included in the election view. Candidate H6TX25179 didn't report any money raised for the election in question, so she isn't showing up on the election page. A few thoughts about how to improve this behavior:

* Show all candidates in the election view, whether they raised money or not. I actually started work on this way back in #1195, but there was some ambiguity about the correct behavior that we never resolved. Maybe this is a good time to revive that discussion.
* Alternatively, add a disclaimer to the election view explaining that candidates with no fundraising aren't displayed.

Preferences @noahmanger @LindsayYoung?

**Comment by LindsayYoung** [comment]
I think that the purpose of the election pages id to give users context to a particular contest. If there isn't any information or breakdowns to display, I don't see the utility of having listing a bunch of zeros there.

**Comment by noahmanger** [comment]
Yeah, I think I agree with Lindsay. If that's the route we go, we should add a disclaimer explaining it. Because people are almost exclusively going to be interested in candidates who have money associated with them, I don't think most people will even really notice.

I suppose the only case I can think of where it would be a little confusing is in the case of a high profile candidate filing to run but before they've filed their first report. I seem to recall this happening with some of the presidential candidates. 

Maybe a third option would be to list somewhere else on the page all the candidates who have filed but not yet reported. That way you can see them, but they're not included in the same financial tables.

**Comment by jmcarp** [comment]
Either a disclaimer or a list of candidates without money sounds good to me--the last option involves a little work on the API, but nothing too complicated.

**Comment by emileighoutlaw** [comment]
I could see adding something below `Showing 1 to 1 of 1 entries` along the lines of:

> This page only shows candidates who have filed a financial report.

or

> This page only shows candidates who have registered **and** filed a financial report.

**Comment by noahmanger** [comment]
From meeting: add disclaimer with a link to the /candidates filtered down.
