### ISSUE TITLE
Add data to API

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1434]
Talked to @paulclark2 and there is some additional information that needs to be created or transferred from the FEC. Paul, for your connivence, you can check the boxes and add comments to this thread so we know when you add the resources. Thanks!

### Views and Tables (lower priority)
 - [x] A view for itemized communication costs
 - [x] A view for itemized electioneering
 - [ ] ~~Clean replacement for dimparty~~ (will be solved in new work)
 - [ ] ~~Clean replacement for dimreport~~ (will be solved in new work)
 - [ ] ~~A table/view that crosswalks the RAD and reporting election codes.~~ (already have)
 - [ ] A table/view that has the schedule A line numbers with a text explanation

### Columns
 - [x] Add a column on `electioneering_com_vw` for `receipt_date`
 - [x] Add a column on `communication_costs_vw` for `receipt_date`
 - [x] Add a column on `communication_costs_vw` F94.ELECTION_TP, (election type from the F94) 
 - [x] Add a column on `communication_costs_vw` F9.FILE_NUM, (file number from the form 9) 
 - [x] Add a column on `communication_costs_vw` F9.AMNDT_IND (amendment indicator from the form) 
 - [ ] Add a column on filings that works as a true amendment indicator

---
This came from discussion here:
https://docs.google.com/document/d/1dZpMv8K6hikRCHnXUSiEt0hQ4twRQNBeh3bZD786yJs/edit#
(The document is meant to be temporary, the todos are GitHub issues, and the explanations will go into the API and site documentation.)

I am modifying this list as needs change.

**Comment by noahmanger** [comment]
Any updates on this before sprint planning?

**Comment by LindsayYoung** [comment]
Paul started this but it is not in production yet

**Comment by PaulClark2** [comment]
just tested the EC view change to confirm I'm not breaking the data catalog.  It looks good to me.  I'll ask our DBA team to move it to production on Monday

**Comment by jwchumley** [comment]
Here is a list of Line numbers and quasi English descriptions as a starting point for line number filter labels.  
[SUMMARY_FORMAT_DISPLAY.txt](https://github.com/18F/openFEC/files/112904/SUMMARY_FORMAT_DISPLAY.txt)

**Comment by PaulClark2** [comment]
and via email

Josh, Lindsay, Jean and Rohan,  

I'm not sure what's the best way to coordinate this change.  I'll let you all tell me.  

-Paul 


Communication Costs view:  
I've added one (1) column and change the data type of one (1) column. 

New column 
  F7_RECEIPT_DT,
Data type change - NUMBER TO DATE
  TRANSACTION_DT

Electioneering Communication view
I've added four (4) columns.  
   RECEIPT_DT,
   ELECTION_TP,
   FILE_NUM,
   AMNDT_IND


COMMUNICATION_COSTS_VW
(this cause the loading program fail since the type not match)
ERROR:  cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on materialized view ofec_communication_cost_mv depends on column "transaction_dt"


ELECTIONEERING_COM_VW
(this will cause the column order in postGre database and in FECP be different.  However, the loading program will still work)
ERROR:  cannot drop table electioneering_com_vw column pg_date because other objects depend on it
DETAIL:  materialized view ofec_electioneering_mv depends on table electioneering_com_vw column pg_date

**Comment by noahmanger** [comment]
@LindsayYoung can you update the checklist above to reflect what we have / still need? (Sorry, having a hard time deciphering).

**Comment by PaulClark2** [comment]
these should be checked off

Add a column on electioneering_com_vw for receipt_date
Add a column on communication_costs_vw for receipt_date
Add a column on communication_costs_vw F94.ELECTION_TP, (election type from the F94)
Add a column on communication_costs_vw F9.FILE_NUM, (file number from the form 9)
Add a column on communication_costs_vw F9.AMNDT_IND (amendment indicator from the form)

**Comment by noahmanger** [comment]
Is this issue still relevant after our new plan? Or are these tables not included in that?

**Comment by PaulClark2** [comment]
Clean replacement for dimparty & clean replacement for dimreport will be taken care of by the new data plan.  

A table/view that crosswalks the RAD and reporting election codes:  TRC_ELECTION_TYPE should take care of RAD report codes.  Disclosure report codes are in REF_RPT_TP.  You have these two tables.  We also have a disclousre table REF_ELECTION_TP. You do not have this table. 
 
A table/view that has the schedule A line numbers with a text explanation.  This is probably still needed.

Add a column on filings that works as a true amendment indicator.  For F1 and F2 we use a view of the filings to do this.

**Comment by noahmanger** [comment]
Great, thanks. I updated the initial comment and pulled those two tasks into their own issues and assigned them to @PaulClark2 so they're easier to track:

- https://github.com/18F/openFEC/issues/1546
- https://github.com/18F/openFEC/issues/1545

This issue is referenced in those, so closing.
