### ISSUE TITLE
Update individual function

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1435]
After talking to Paul there are 2 updates to the individual function we will want to make:

 - Add new individual party codes as individual contributions: 30, 30T, 31, 31T, 32
 -  [here](https://github.com/18F/openFEC/blob/develop/data/functions/individual.sql#L22) on line 22, it should be counted as an earmark and excluded from our individual filtering if the line has a memo code of X _OR_ it has  “earmark”, “earmk”, or “ermk” in the memo_text.

this comes from:
https://docs.google.com/document/d/1dZpMv8K6hikRCHnXUSiEt0hQ4twRQNBeh3bZD786yJs/edit#

**Comment by jmcarp** [comment]
About changing the earmark logic: what problem does this fix? Which records that are currently not flagged as individual will change?

**Comment by LindsayYoung** [comment]
The party codes are new, the law for how much you could donate to a party changed, so there are now those new codes- we might not have any yet but the are coming.

The and instead of or will add items that have memo_code=x but no "earmark" in the memo text or items that have "earmark" but not memo_code=X I can look for individual transactions if that would be helpful.

**Comment by jmcarp** [comment]
Right, that's what I'm asking: let's look at some records that will change from not individual to individual after changing the earmark logic, so that we can verify that this is a good thing to do.

**Comment by LindsayYoung** [comment]
Glad you brought that up, Josh. Unless, I am doing the query wrong, I am only seeing 2 examples where we need to check text because it is missing `memo='x'`:

It would be nice to get rid of the added complexity and just go with memo code. If you are seeing the same thing, let's ask Paul and Jeff if they are OK simplifying. 

```
select cmte_id, contbr_nm, contb_receipt_amt, receipt_tp, memo_cd, memo_text from sched_a where memo_cd='x' and contb_receipt_amt < 200 and (memo_text not like 'EARMARK' or memo_text not like 'EARMK' or memo_text not like 'ERMK');
 cmte_id │ contbr_nm │ contb_receipt_amt │ receipt_tp │ memo_cd │ memo_text 
─────────┼───────────┼───────────────────┼────────────┼─────────┼───────────
(0 rows)


select * from sched_a where  memo_cd is null and contb_receipt_amt < 200 and (memo_text like 'EARMARK' or memo_text like 'EARMK' or memo_text like 'ERMK');
 sched_a_sk │ form_tp │  cmte_id  │ cmte_nm │ entity_tp │ contbr_id │      contbr_nm       │ contbr_prefix │  contbr_f_nm  │ contbr_m_nm │ contbr_l_nm │ contb
────────────┼─────────┼───────────┼─────────┼───────────┼───────────┼──────────────────────┼───────────────┼───────────────┼─────────────┼─────────────┼──────
  102654507 │ SA11AI  │ C00009985 │         │ IND       │           │ PAYNE, WILLIAM H MR. │               │ WILLIAM H MR. │             │ PAYNE       │      
  102654508 │ SA11AI  │ C00009985 │         │ IND       │           │ PAYNE, WILLIAM H MR. │               │ WILLIAM H MR. │             │ PAYNE       │      
(2 rows)

```

**Comment by jmcarp** [comment]
A few points about those queries--memoed receipts have a `memo_cd` of "X", not "x", and the `LIKE` operators we're using are going to check for exact matches because they don't include any "%" symbols. I think what we want to compare is:

```
select cmte_id, contbr_nm, contb_receipt_amt, receipt_tp, memo_cd, memo_text from sched_a where memo_cd='X' and contb_receipt_amt < 200 and (memo_text not like '%EARMARK%' or memo_text not like '%EARMK%' or memo_text not like '%ERMK%');
```

and

```
select * from sched_a where  memo_cd is null and contb_receipt_amt < 200 and (memo_text like '%EARMARK%' or memo_text like '%EARMK%' or memo_text like '%ERMK%');
```

Meanwhile, I found the original conversation where we got the instruction to check both `memo_cd` and `memo_text`: https://github.com/18F/openFEC/issues/1141#issuecomment-133054126. The relevant piece is:

> We do care about memo_cd. In the case of "earmark" in the memo_text we include the ones with null memo_cd and exclude the ones with non-null memo_cd.

Looking at some examples, I'm wondering if changing this is right:

```
fec=> select contbr_nm, memo_cd, memo_text from ofec_sched_a where image_num = '14020104348';
    contbr_nm     | memo_cd |                                memo_text
------------------+---------+------------------------------------------------------------------
 INADOMI, BETH    |         |
 ACTBLUE          | X       | [MEMO ITEM] NOTE: ABOVE CONTRIBUTION EARMARKED THROUGH THIS ORGAN
 WILLIAMS, LESLIE |         | * EARMARKED CONTRIBUTION: SEE BELOW
(3 rows)
```

The second contribution here meets both the `memo_cd` and `memo_text` criteria, so we currently categorize it as an earmark and exclude it from individual contributions. The third meets the `memo_text` rule but not the `memo_cd` rule, so we don't call it an earmark, and we include it in individual contributions. If we switch the rule from `and` to `or`, we'd consider both records to be earmarks and exclude them both from individual contributions.

Let me know if I'm misunderstanding the change we're talking about here--sorry if so!

**Comment by LindsayYoung** [comment]
For those three rows, the first one is not an earmark, it is directly from an individual and should be included in our totals. The next two are earmarks and should be excluded from or totals. 

`memo_cd` comes from internal coding process, people look for earmarks and flag them, this coding doesn't always happen on transactions less than $200 so we are looking for "earmark" in the text field too.

Thanks for clarifying the querys too!

**Comment by jmcarp** [comment]
Sorry, I picked a bad example--the third row of the query above actually should be categorized as individual, since the `receipt_tp` is "15E". So I'm not sure that row is diagnostic after all. Anyway, the basic question is still the same--which rows will flip from individual to not individual, and vice versa, with this change?

Here are a few examples. I revised the individual helper functions, with the and changed to an or, and called the main function `is_individual_revised`. The main result of the change should be to flip a bunch of rows from individual to not individual, since we're loosening the criteria for earmarked receipts. Here are some examples of rows that changed status. These *look* like individual contributions to me, but I'm less familiar with the forms than @LindsayYoung and others, so I'm not sure. My guess is that the examples are receipts from individuals that were earmarked on other items on the filing--by ActBlue, etc.

```
fec=> select contbr_nm, memo_text, image_num from ofec_sched_a where is_individual and not is_individual_revised(contb_receipt_amt, receipt_tp, line_num, memo_cd, memo_text) limit 15;
     contbr_nm     |                               memo_text                               |  image_num
-------------------+-----------------------------------------------------------------------+-------------
 NEARMAN, ERNIE    | EARMARKED FOR DEMOCRACY FOR AMERICA (C00370007)                       | 15950244071
 NEBBIA, RALPH     | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244074
 NEBEL, ELIABETH L | EARMARKED FOR DEMOCRATIC SENATORIAL CAMPAIGN COMMITTEE (C00042366)    | 15950244076
 NEBEL, SHEILA     | EARMARKED FOR DEMOCRATIC SENATORIAL CAMPAIGN COMMITTEE (C00042366)    | 15950244079
 NEBEL, TERRY      | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244080
 NEBOLSINE, ARCADI | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244084
 NECHIN, ROBERTA   | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244088
 NECHYBA, THOMAS   | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244091
 NEDOL, JAN        | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244095
 NEEDHAM, RUSSELL  | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244097
 NEEDHAM, SANDRA   | EARMARKED FOR DEMOCRATIC SENATORIAL CAMPAIGN COMMITTEE (C00042366)    | 15950244098
 NEEDHAM, THOMAS   | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950244099
 WHALEY, SAM       | EARMARKED FOR DEMOCRACY FOR AMERICA (C00370007)                       | 15950284062
 WHAM, BOB         | EARMARKED FOR DEMOCRATIC CONGRESSIONAL CAMPAIGN COMMITTEE (C00000935) | 15950284066
 WHAM, MATALIE     | EARMARKED FOR DEMOCRATIC SENATORIAL CAMPAIGN COMMITTEE (C00042366)    | 15950284067
(15 rows)
```

**Comment by LindsayYoung** [comment]
@paulclark2 Act Blue is putting "Earmarked for" in in the memo text when they are receiving individual donations. I would like to find the least wrong way to do this.

We could keep trying to parse the text, and include records with earmark, that but exclude records that have "EARMARKED FOR" in them. 

---
Here is the scenario we are going for, as I understand it. Correct me if I am wrong:

In these cases, a person such as Ernie Nearman give money to Act Blue that PAC then gives that money to Democracy for America. 

When we look at Act Blue that money counts as an individual donation. 

When we look at Democracy for America, we don't want to include that money as an individual donation, since Democracy for America got the money from Act Blue. This is important because in Democracy for America's records there can be the total transaction from Act Blue and a transaction that represents Nearman's earmarked contribution. We don't want to double count that when we create totals.

In this case we are looking for earmarks that are given to Act Blue and then re-given to Democracy for America. There are in two ways to find earmarks. First is by looking at the coding; if `memo_cd=X` then a FEC has determined this is an earmark and it is not included in our aggregates. If the amount is greater than $200, and `memo_cd` is null that means it transaction is not an earmark. 

For amounts less than 200, we can look at the memo code- if it is flagged, it is an earmark and not included in our aggregates.  We also want to see if this has a variation of "earmark" but not "earmarked for" in the memo text.

**Comment by PaulClark2** [comment]
`When we look at Democracy for America, we don't want to include that money as an individual donation, since Democracy for America got the money from Act Blue. This is important because in Democracy for America's records there can be the total transaction from Act Blue and a transaction that represents Nearman's earmarked contribution. We don't want to double count that when we create totals.`

No when we look at Democracy for American's individual contributions we want to see "Ernie Nearman" not "ActBlue."  The contribution to Democracy for America come from Ernie Nearman not ActBlue.

**Comment by LindsayYoung** [comment]
If we should count earmarks as individual donations, we should not be filtering them out of the aggregation at all. We should not exclude `memo_code=x` and we should not exclude things with 'earmark' in the memo text, right? 

Just want to be extra explicit since the opposite of what we are doing. Perhaps I am still misunderstanding.

**Comment by PaulClark2** [comment]
The example below looks at ActBlue's reporting of an earmarked contribution and the intended recipient committee's reporting of the contribution.  ActBlue's ID is C00401224 and Orange County's ID is C00321943.  To me the ` contb_receipt_amt < 200 
and receipt_tp is null and (memo_cd is null or (memo_text like 'EARMARK' or memo_text like 'EARMK' or memo_text like 'ERMK'))` restrictions are pulling the correct set of transactions.  @jwchumely   

`select cmte_id, contbr_nm, contb_receipt_amt, receipt_tp, memo_cd, memo_text 
from sched_a where cmte_id in ('C00321943', 'C00401224') 
and image_num in (15970141373, 15950244071) and contb_receipt_amt < 200 
and receipt_tp is null and (memo_cd is null or (memo_text like 'EARMARK' or memo_text like 'EARMK' or memo_text like 'ERMK'));`

CMTE_ID	CONTBR_NM | CONTB_RECEIPT_AMT | RECEIPT_TP | MEMO_CD	MEMO_TEXT
----- | ----- | ----- | ----- | -----
C00401224 | NEARING, LINDA | 15 |  | EARMARKED FOR DEMOCRATIC PARTY OF ORANGE COUNTY (C00321943)
C00321943 | NEARING, LINDA | 15 |  | 	

With the restrictions in the where clause (this query gives us a transaction from ActBlue transaction reported by Orange County that we do not want to include)

`select cmte_id, contbr_nm, contb_receipt_amt, receipt_tp, memo_cd, memo_text from sched_a 
where cmte_id in ('C00321943', 'C00401224') and image_num in (15970141373, 15950244071) and contb_receipt_amt < 200;`

CMTE_ID	CONTBR_NM | CONTB_RECEIPT_AMT | RECEIPT_TP | MEMO_CD | MEMO_TEXT
-----| -----| -----| -----| -----| 
C00321943 | NEARING, LINDA | 15 | |  |  			
C00321943 | ACTBLUE | 15 | X |  | 	
C00401224 | NEARING, LINDA | 15 |  | EARMARKED FOR DEMOCRATIC PARTY OF ORANGE COUNTY (C00321943)

**Comment by LindsayYoung** [comment]
Thanks for clarifying. That makes more sense to me now. I was thinking that it was reported twice instead of 3 times.

**Comment by LindsayYoung** [comment]
@jwchumley can you sign off on [this fix](https://github.com/18F/openFEC/pull/1457/files#diff-88582bb0931300709126076a79c7ded5L32) Want to confirm we are all on the same page. 

Thanks!

**Comment by jmcarp** [comment]
To be more specific about being on the same page: way back in August of last year, we got different instructions from FEC, and I want to be sure that we're doing the right thing before we make a change.

From last August, https://github.com/18F/openFEC/issues/1141#issuecomment-132635114:

> Rule  #2 If it is on line 11a or 12 (F3 or F3x) or line 17 or 17A or 18
(F3P) and the amount is less than $200  and it is not coded include it
        UNLESS  it is a memo entry and includes  "EARMARK','EARMK'
or'ERMK'  in the memo_text field, don't include it.

According to this rule, we only exclude receipts as earmarks if `memo_cd` is set *and* if `memo_text` includes a string like "earmark."

I followed up on this at the time in https://github.com/18F/openFEC/issues/1141#issuecomment-132880405:

> Do we care about the value of the memo_cd column? I see that some receipts with non-null memo_text values have null memo_cd. Do we want to exclude receipts with null memo_cd that have memo_text values that include "earmark"?

As far as I could tell, the reply confirmed that we only want to treat receipts as earmarks and exclude them when the memo code was set *and* the memo text indicated an earmark (https://github.com/18F/openFEC/issues/1141#issuecomment-133054126):

> We do care about memo_cd. In the case of "earmark" in the memo_text we include the ones with null memo_cd and exclude the ones with non-null memo_cd.

From the discussion in this issue and the proposal, it looks like we're changing the rule: instead of excluding receipts that have both a non-null memo code and the word "earmark" in the memo text field, we'll exclude receipts that meet either of the two conditions. Since the conversation back in August mostly involved @jwchumley and the conversation in this issue has mostly involved @PaulClark2, I'd like to verify that the two of you both approve of changing this rule from the instructions that came out last summer.

Sorry to spend so much time on a three-character change, but this touches a lot of records, and I'd like explicit confirmation that we're getting it right.
