### ISSUE TITLE
Discussion: Calendar filter logic

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1442]
I'm pretty sure we've talked about this before, but now that I can actually see how things work, I want to discuss how the overlap between calendar _state filters_ and calendar _category filters_ works.

Currently, they seem to be completely independent. For example, on 2/14/16, there's an event for "EC period starts" for the Ohio primary election on March 15. If you have the "EC period" filter on, it shows up, even if you have non-Ohio state filters selected. 

I would expect that if I have, say, "EC Periods" and "Alaska" selected, I would only see the EC Periods for Alaska.

**Comment by LindsayYoung** [comment]
States filter elections and reports.

The periods are from the cal_event table. They have a messy field called location that but not a standardized state field.

**Comment by noahmanger** [comment]
Gotcha. Shouldn't they also filter IE and EC periods that are also state-specific?
So here's a concrete example: https://fec-proxy.18f.gov/calendar/?state=NH&category=IE+Periods&category=EC+Periods

In this case, I'd expect to only see EC Periods and IE Periods relevant to New Hampshire, similar to how here the NH primary doesn't show up when you have Alaska selected: https://fec-proxy.18f.gov/calendar/?state=AK&category=election-P

**Comment by jmcarp** [comment]
@LindsayYoung answered this above, but let me expand on the point a bit. Election events and most reporting deadlines have structured state information in the source FEC tables, so we're able to filter them by state. This includes categories that begin with `election-` or `report-`. If you check the IE and EC checkboxes, you'll see that they don't match either of these patterns--we group them under reporting periods because it makes sense conceptually, even though the data come from a different source than the rest of the reporting deadlines. IE and EC periods, as well as outreach, meetings, rule-making, and other categories, come from a different table that doesn't include structured state data, meaning that state filters don't apply.

As @LindsayYoung has mentioned, we *could* try to parse states from the free text descriptions in the `cal_event` table. This could be a bit error-prone, since state information isn't consistently encoded--sometimes using abbreviations, sometimes full names--but it should be doable. I can take a look at this tomorrow if folks think it would be worthwhile.

**Comment by noahmanger** [comment]
Aaaah that's my bad, I just re-read the original response and see now. Thanks for clarifying. So yes, I think if we're grouping them because they're conceptually similar (which I think is good), then they need to have the same behavior. I'd prefer to find a solution to this that didn't involve complicated and error-prone parsing, ideally through the initial data entry.

**Comment by jmcarp** [comment]
If we have time, let's bring this up with FEC next meeting. I agree that it would be ideal for the data entry layer to handle this, but that might weigh in favor of rebuilding that piece. Either way, seems like somebody's going to have to parse the existing data at some point--even if we clean up the process going forward, we still have years worth of events with plain-text locations.

**Comment by LindsayYoung** [comment]
:+1: to a clean process going forward

**Comment by noahmanger** [comment]
Closing this as it's just a part of the broader question around how we want to manage data going forward.
