### ISSUE TITLE
Move back 18F updates to reduce lag.

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1448]
It looks like we are running them at midnight GMT (7 pm eastern). @paulclark2 is going to confirm with Rohan and the DBAs that we can run these updates later (maybe 3  am eastern), so that we are up to date with the website. 

Code for scheduling task is [here].(https://github.com/18F/openFEC/blob/209160bacb7cedc345c0c1e1a1a24871d4e8845e/webservices/tasks/__init__.py#L32)

Paul, can you post the time you think the updates will be done by on this issue? Thanks!

**Comment by PaulClark2** [comment]
Completion times for the past 3 days.   I wonder if we can't think of a way to flag completion so that the processes on your side start running dynamically once an appropriate set of tables is refreshed.  

These tables are refreshed by 1:30 a.m.

|Table Name|
|-----|
|DIMCAND|
|DIMCANDOFFICE|
|DIMCANDPROPERTIES|
|DIMCANDSTATUSICI|
|DIMCMTE|
|DIMCMTEAGENT|
|DIMCMTEBANK|
|DIMCMTEPROPERTIES|
|DIMCMTERELATED|
|DIMCMTETPDSGN|
|DIMDATES|
|DIMELECTIONTP|
|DIMLINKAGES|
|DIMOFFICE|
|DIMPARTY|
|DIMREPORTTYPE|
|DIMYEARS|
|FACTHOUSESENATE_F3|
|FACTINDPEXPCONTB_F5|
|FACTPACSANDPARTIES_F3X|
FACTPRESIDENTIAL_F3P|
|SCHED_E|
|FORM_5|
|FORM_57|
|FORM_7|
|FORM_76|
|FORM_9|
|FORM_91|
|FORM_94|

These tables are refreshed by 3:00 a.m.

|Table Name|
|-----|
|SCHED_A|
|SCHED_B|
|VW_FILING_HISTORY|
|TRC_ELECTION|
|CAND_VALID_FEC_YR|
|CMTE_VALID_FEC_YR|
|TRC_REPORT_DUE_DATE|
|CAND_INACTIVE|
|EXPORT_SDRFORM98|
|CAND_CMTE_LINKAGE|

These tables are refreshed by 4:00 a.m.

|Table Name|
|-----|
|F_ITEM_RECEIPT_OR_EXP|
|V_SUM_AND_DET_SUM_REPORT|
|F_RPT_OR_FORM_SUB|
|F_ITEM_RECEIPT_OR_EXP|

These tables are refreshed by 6:15 a.m.

|Table Name|
|-----|
|CAL_CATEGORY|
|CAL_CATEGORY_SUBCAT|
|CAL_EVENT_CATEGORY|
|CAL_EVENT_STATUS|
|CAL_EVENT|

**Comment by noahmanger** [comment]
Will this change make us effectively always up to date with fec.gov?
