### ISSUE TITLE
release planning: Dino, sprint 6

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1460]
_I'm using this issue to test an approach I'm suggesting for release planning, hopefully fixes https://github.com/18F/openFEC-web-app/issues/1026._

Features: 
* Calendar - http://fec-proxy.18f.gov/calendar
 * Data quality: are the correct events showing up? Do they have the correct data associated with them?
Is there anything missing?
* Filter tags - https://fec-proxy.18f.gov/data/receipts (and other pages) 
 * Do tags for each of the various types of filters work as expected: dates, money, names, typehead, checkboxes?
* Independent Expenditures - https://fec-proxy.18f.gov/data/independent-expenditures 
 * Do we have the correct filters and are they working as expected?
 * Is the correct data showing up? Are any records missing?
 * Are we using the correct fields in the details panels?
 * Are links from the IE sub-totals (like here) linking to the correct underlying data?

Checks
* [ ] will we want to announce this? (we'll need to do some comms planning) --> I think we should definitely announce the calendar at some point, but ideally after it has been live on the site and tested more.
* [ ] [open an issue in Accessibility Reviews repo](https://github.com/18F/Accessibility_Reviews/issues/new) with this checklist and give Bristow a heads up

```
  * Name of the Project:
  * URL:
  * Login details:
  * Date the review is needed:
  * Is this a DHS project?
```

Post links to issues that were created because of this testing in the comments.

**Comment by leahbannon** [comment]
Subscribe doesn't seem to work for Google for me. It opens my Google calendar, but then nothing else happens. It worked fine for downloading to Apple iCal. I haven't tested for Outlook. Do we have an issue for this yet?

**Comment by leahbannon** [comment]
A meeting without an end time is showing up as an full day event. Not sure if this matters...

<img width="472" alt="screen shot 2016-01-26 at 4 25 06 pm" src="https://cloud.githubusercontent.com/assets/4323988/12599750/589ea474-c449-11e5-9f54-07b0561031ee.png">

**Comment by noahmanger** [comment]
Thanks for logging all this, Leah. Breaking out the issues:

**Calendar**
- Google Cal subscription + Add to Calendar in tooltips: Josh just pushed a patch. Good catch.
- On closing tooltips, I found myself wanting the same behavior, so a new issue: https://github.com/18F/fec-cms/issues/189
- Let's keep an eye on the location stuff. It may be useful to have it link to a map or address or something.

**IE Table**
- Filed a new issue for certain candidate links on IE tables being broken: https://github.com/18F/openFEC-web-app/issues/1057
- That page you said is 404'ing works for me on dev
- On document links, I'm not sure. We also link to it from the details panel with the "View original image" button, so maybe it doesn't matter?

Because we're only trying to launch the filter tags and IE page next week, the issue with candidate links being broken is the only one that _needs_ to be fixed, but good to get this calendar stuff now too.

**Comment by noahmanger** [comment]
This release is done.
