### ISSUE TITLE
API Endpoint for totals over time

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1466]
#For some of the new views, we will want to create a browse view for exploring financials. To do that, we will want to default to the most current data or have the user select a 2 year slice, or full election year in certain candidate views. Then they can filter by total receipts, total disbursements, cash on hand and debt. (The totals will be the totals of the time period selected and not just the most recent.)

**Comment by noahmanger** [comment]
One addition: we want this for both `/committees/` and `/candidates/`, where the candidates includes all their authorized committees.

**Comment by jmcarp** [comment]
Note: I'm going to work off the columns and filters laid out in https://docs.google.com/spreadsheets/d/1-LjKQy3dOJI9FJmrhNEfgsr-uD7HzzH0qf1zpo3azTE/edit#gid=1333566859 for this issue.

**Comment by jenniferthibault** [comment]
@jmcarp first thing tomorrow morning I can make a quick mockup of these filters & columns. Don't let it hold you up from starting, but it might help or make it more clear if there are questions.

**Comment by jenniferthibault** [comment]
Here are WIP mockups for the candidates tables. There are a few stylistic things I'm still wiggling out, like how to make a vertical election period toggle, but hopefully this will help flesh out how filters are grouped and column order.

![all candidates](https://cloud.githubusercontent.com/assets/11636908/12706343/ca54bbd4-c850-11e5-9678-89f96e7c9da4.png)

![candidates - president](https://cloud.githubusercontent.com/assets/11636908/12706344/d308e5d4-c850-11e5-8113-e4eecc8d6aa9.png)

![candidates - senate](https://cloud.githubusercontent.com/assets/11636908/12706346/d7fea66e-c850-11e5-89dd-a8eb7bfcd573.png)

![candidates - house](https://cloud.githubusercontent.com/assets/11636908/12706347/da1a84a4-c850-11e5-9816-f7328add97b9.png)

**Comment by emileighoutlaw** [comment]
I'm googly eyed over these mock-ups, Jen! I think they're wonderfully clear!

I'm adding some content notes below, but let me know if there's a better place for me to capture this?

#### Candidate
I’d like the subtext to read “Enter a name or candidate ID”

#### Years
Would it be more correct to say “Years the candidate was active?” What we have, “years the candidate ran for office” makes me anticipate an election year. 

#### Candidates that accept federal funds
I think this should be “Candidates *who* accept federal funds.” I wonder if this check box should come at the bottom of the filter? Seems like a less common search function than total receipts and total disbursements. But I could be wrong about that.

#### State and District drop-downs
What do you think about the text defaulting to “Select” rather than “Select state” or “Select district.” I think it’ll be clear from the filter label and tighten things a little. But I don’t have a ton of experience with usability and content in filters.

#### Misc
Just as a general style note, we’ll want to make sure we capitalize Senate and House in all instances.

**Comment by jenniferthibault** [comment]
Process question: Where and how do we want to track edits at this level?

- Do we want to keep the spreadsheet 100% accurate (will take minimal adjusting, likely on @emileighoutlaw 's part) pros: @emileighoutlaw can craft language before seeing mockups. con: I've heard @jmcarp prefers non-google docs.
- Or.....do we want to keep these tracked in GitHub issues?


I'm always inclined toward having one primary document for all these things, rather than spreading it across issues, but not sure how that works for other folks.

**Comment by noahmanger** [comment]
Next step: demo and review with frontend.
