### ISSUE TITLE
Research performance improvements for data downloads

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1489]
There are two kinds of work that make data downloads slow: (1) loading data from postgres into python and (2) serializing data from python to disk. Off the top of my head, there are a few things we could do that would make downloads faster, potentially much faster--but there are trade-offs, too.

* Use custom serializers instead of marshmallow. Marshmallow is designed to be flexible and easy to use, not to serialize large numbers of records as efficiently as possible. If we write our own serialization functions instead of relying on marshmallow, we should be able to speed up serialization significantly. Trade-off: we wouldn't get to re-use the marshmallow schemas we've already written, so we'd wind up implementing serialization logic twice for several views.
* Write csvs directly from psql. The psql terminal includes a facility for dumping records to csv. This means we wouldn't have to load data into python at all--which is great, because we save a step, and python is slow. This would be a pretty radical change, bypassing both marshmallow and sqlalchemy. We'd lose dynamic column renaming (changing "rpt_yr" to "report_year") and would have to do some work to get nice names in the output. But we'd get downloads potentially much faster. In a not completely fair comparison, downloading about 50k itemized independent expenditures took about 130s with our current setup and about 10s with `copy` (the comparison isn't fair because we aren't also serializing nested candidates and committees):

```
fec=> \copy (select * from ofec_sched_e where get_cycle(rpt_yr) = 2012 and not is_notice) to '/tmp/itemized.csv' with csv
COPY 39097
Time: 11978.305 ms
```

That's a lot faster.

Anyway, this may be something for @ccostino to keep in mind while reviewing the data download code. Pinging @LindsayYoung too.

**Comment by jmcarp** [comment]
For reference, if we want to try using `copy` and offloading a lot of the work to postgres, I'm thinking we'd talk to `psycopg2` directly, as documented here: http://initd.org/psycopg/docs/usage.html#using-copy-to-and-copy-from

**Comment by ccostino** [comment]
@jmcarp:  The second suggestion you have listed seems like the much more performant and scalable solution.  How important is the serialization mechanisms that exist right now?  Or better yet, what purpose are they serving at the moment other than providing data for download/display?  I just want to make sure I have a clear understanding of the project as it is right now to understand all of the trade-offs.

When I've worked on similar features in the past we almost always had to shift processing to the server to be some form of an asynchronous activity so we didn't bring the site itself down with such requests.  One project in particular comes to mind where we had reports being generated that would take an enormous amount of time that we shifted to be a Celery task.  The user would initiate a request for the info on the site which would trigger the task, and the site notified them (via e-mail I believe) when their report was ready for download.

It seems like a similar thing could be done if you wanted the results available in real-time for someone making a download request.  We could create a task that generates the CSV on the server using the psql copy utility and then do some quick data manipulation to change column headers and whatnot before serving the CSV back as the response.

Alternatively, we could setup a job that runs behind the scenes at set intervals (once a day, once an hour, etc.) to create the CSVs automatically so that they're always available immediately for anyone.  However, this is provided that all users would always downloading the same kind of results CSV, which I don't think is the case because I think we're custom-tailoring the CSV based on their applied searches and filters if I remember correctly from what you showed me.

**Comment by jmcarp** [comment]
Just to be clear, the workflow you're describing is the same as the workflow we're using, with the exception of switching from SQLAlchemy to direct communication with psycopg2. We're using celery now, and the celery workers run in a separate set of cloud.gov instances so that they don't interfere with the rest of the application.

The benefits of not using SQLAlchemy instead of psycopg2 are consistency with the rest of the API and ease of use. We're already using SQLAlchemy to rename variables and construct queries, and marshmallow to format output (adding nested relations, dynamically formatting columns, etc). Since we've already written this logic for the API, it would be ideal to avoid rewriting it. The question is if we can find a way to reuse existing code to work with `copy`.

**Comment by jmcarp** [comment]
Some concrete examples of things we'd need to figure out to use `copy`:

* We're using SQLAlchemy to alias column names--e.g. `report_type = db.Column('rpt_tp', db.String)`. This saves us the trouble of renaming several hundred columns in sql scripts--although this wouldn't be hard to do. We should also be able to introspect these aliases from our models.
* We calculate some column values dynamically, using `@property` and `@declared_attr` decorators in the models. We could either pre-compute all of these values on loading data, or add sql stored procedures to continue building them on the fly.
* We're using marshmallow to exclude fields that shouldn't be used in exports, like internal IDs and full-text vectors--as well as including nested schemas. Although it would help speed up download performance if we didn't bother with nesting here.

I also think it would be fun and potentially informative to pair on this briefly sometime and get a clearer sense of how much time it would take, and what kind of benefits we'd get. Want to give it a try @ccostino?

**Comment by ccostino** [comment]
Ah okay, I didn't realize most of this was already in place!  Forgive me, it's tough keeping track of the details while being split between projects as I am at the moment.  Thank you for clarifying and providing additional context!

Yes, I think this would definitely be fun and informative to pair on this, let's schedule a time for next week when I'll be much more available; this will also give me a bit more of a chance to bring myself up-to-speed.

**Comment by LindsayYoung** [comment]
Would either of you mind if I listened in on the downloads session?

**Comment by ccostino** [comment]
@LindsayYoung:  Not at all!  We should figure out a way to make this work nicely.  It might be easiest when you and I are in the office since we'd be able to share a screen to see everything while chatting with @jmcarp.

**Comment by noahmanger** [comment]
Research complete!
