### ISSUE TITLE
Discussion: Missing report types in sched_e

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1499]
We currently use the `rpt_tp` column in the `sched_e` table to filter out 24- and 48-hour reports like so:

`...where rpt_tp not in ('24', '48')...`

It turns out that some records in `sched_e` have `null` values for this column, so we don't exclude them. But some of those records look like they *should* be categorized as 24- or 48-hour reports. Here's an example: http://docquery.fec.gov/cgi-bin/fecimg/?12030834023. This document was filed on the "24/48 hour notice of independent expenditures" form, and the filer checked the "48-hour report" box, but the `rpt_tp` value in the database is `null`. In other words, we're currently including this record in the data tables, but it sounds like we shouldn't be.

Is there a reason the `rpt_tp` column is `null` here? I'm wondering if there's a way to fill in those missing values, or if we can find a better rule for identifying 24- and 48-hour notices in this table.

Ping @noahmanger @LindsayYoung @PaulClark2 @jwchumley

**Comment by PaulClark2** [comment]
We need to modify the query  for the current release of the IE page to `...where rpt_tp not in ('24', '48') and filing_form = 'F3X'...`  Otherwise, we have a mix of form types  F3X,  F5 and F24 and a mix of IEs reported on regular reports and IEs reported on 24-hour and 48-hour reports of independent expenditures.  

There are 10,008 `sched_e` rows without a report type (344,696 rows have report type populated) and the `form_57` tables does not include a report type column.  `select count(*)  from sched_e where rpt_tp is null;`  

Generally, we do not look at report type information in transaction rows.  So, I'm not surprised there are some rows with missing report type information.   We seem to have a couple options:  1) populate the report type information using the report type from the transaction's parent row; 2) join the transaction table with a form table and use report type from the form table.  Option #2 would allow us to treat Form 3X, Form 5 and F24 independent expenditures the same way.  

I see several steps we need to take with the IE page.  Step 1 should happen as soon as possible.  

1) modify the query as mentioned above and in #fec-partners to restrict the transactions to only IE reported on F3x regular reports `...where rpt_tp not in ('24', '48') and filing_form = 'F3X'...`

2) add IEs reported on regular Form 5 filings

3) figure out how best to add 24-hour and 48-hour reports of independent expenditures reported on Forms 5 and 24 (F3X-SE)

**Comment by jmcarp** [comment]
Got it--we'll remove itemized IE that weren't filed on F3X from the browse view right away.
