### ISSUE TITLE
Missing districts in election events

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1507]
I see that we have districts included in events like EC periods, but we seem to be missing them for the actual election events, such as in Texas on March 12:

<img width="249" alt="screen shot 2016-02-11 at 3 53 33 pm" src="https://cloud.githubusercontent.com/assets/1696495/12994785/cfbf1cba-d0d7-11e5-84ed-e1e3a27ee962.png">

Can you see if it's not too much trouble to add this?

**Comment by noahmanger** [comment]
Ping on this.

**Comment by LindsayYoung** [comment]
Working on this and the caucus ruckus now ;)

**Comment by LindsayYoung** [comment]
This might be a data issue, I am going to submit a pr for the caucus stuff and keep looking at this.

**Comment by LindsayYoung** [comment]
We seem to be showing the district information we have. Unfortunately, in the election table, most of the house events do not have district information. It is set up to have districts and the districts are spaces rather than nulls,  so I did not realize how faulty the table was earlier. 

By doing a spot check, it looks like you only have the district information when it is a special election.

```
fec=> select count (*) from trc_election where office_sought='H';
 count 
───────
  1256
(1 row)

fec=> select count (*) from trc_election where office_sought='H' and election_district!=' ';
 count 
───────
   260
(1 row)
```

**Comment by jmcarp** [comment]
Maybe I'm misinterpreting, but that doesn't really sound like a problem, since most house elections apply to all districts--right?

**Comment by LindsayYoung** [comment]
Yea, that is a good point, it is probably fine

**Comment by noahmanger** [comment]
I don't know if that's the case. I think it may also hold true for certain primaries. I just know that this was flagged as an issue in the FEC's feedback review. @ChristianHilland and @PaulClark2 can you weigh in?

**Comment by ChristianHilland** [comment]
The district number shouldn't matter unless it is a special election. For example, OH-8 has a special elecyion in early March. Paul, thoughts?

**Comment by PaulClark2** [comment]
@noahmanger is this related to https://github.com/18F/openFEC/issues/1508 or is this a separate issue?

**Comment by noahmanger** [comment]
Separate. It was drawn from these comments in the doc:

> Mar 12 and 19th is listing the TX Conventions for minor parties for the Green and Libertarian parties. We list them as "TX Convention-Minor Party (C)" and description "Texas House - Minor Party Conventions [Single County Districts #s 2-3, 7, 16, 18, 20, 29, 30] held today." 

> Special Election naming convention is different from how we list the special elections on the calendar. See March 3 listed as "House Election 12SP." The district is also not included in the description for the Congressional race.

**Comment by LindsayYoung** [comment]
We are showing all the districts that we are given, If you see March 11, 2014 there is a district for the special election.
https://fec-proxy.18f.gov/calendar/?category=election

If there are additional district information that is missing, add the district to the election in `trc_elections` and it will get imported into the calendar.

**Comment by jmcarp** [comment]
It sounds like we're showing all the information we have, so I'm going to close this. Feel free to reopen if there's more to discuss here!

**Comment by PaulClark2** [comment]
The current calendar doesn't list the Green and Libertarian party conventions separately and the beta calendar does.  

The current calendar lists the districts.  The beta calendar does not list the districts.  I think this is the same data problem we've discussed before the cal_event is inconsistent and we are using election dates from trc_election tables not the cal tables.  

screen shots might help.  

current calendar
![tx convention minor party](https://cloud.githubusercontent.com/assets/11817734/13130370/75dd39fa-d5b1-11e5-9597-788744757897.png)

beta calendar
![tx convention beta](https://cloud.githubusercontent.com/assets/11817734/13130382/87cd3cd2-d5b1-11e5-8072-56ffc9be3cb1.png)

For Texas see page 4 footnote 10:  http://www.fec.gov/pubrec/fe2016/2016pdates.pdf

I agree with Josh.  This issue is closed for now or until we have data in the cal or election tables that allow us to display the districts for these elections.
