### ISSUE TITLE
Send 18F table of schedule A line numbers with a text explanation

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1545]
As discussed https://github.com/18F/openFEC/issues/1434

**Comment by PaulClark2** [comment]
I'm trying to recall what on the beta site needed this information.  The table below is what we use to determine what form level line items to display on the two-year summary tab of the Viewer.  We make the determination primarily based on filing form.   This might be less of a problem because on the beta site we don't have a combined  financial summary table but have separate tables for each form type.  On the current site the table that supports the summary tab contains summary financial information from all form types.  

The OFEC scripts for the schedules have column name aliases, do we need tables with column names and English names, too?  @noahmanger @LindsayYoung @ccostino That's fine if we do for documentation.  

V_SUM_COLUMN are summary financial column names from various forms.  

V_SUM_COLUMN	|	TYPE_CD	|	TYPE	|	POSITION	|	F3	|	F3P	|	F3X	|	F4	|	F5	|	F7	|	F13	|	GRAPH_IND	|	FILTER	|	LINE_NUM	|	DISPLAY_CODE_PK
----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----
FED_FUNDS_PER	|	R	|	1	|	1	|		|	X	|		|		|		|		|		|	Y	|		|	16	|	3
FED_FUNDS_PER	|	R	|	1	|	1	|		|		|		|	X	|		|		|		|	Y	|		|	13	|	32
COH_BOP	|	C	|	3	|	1	|	X	|	X	|	X	|	X	|		|		|		|	N	|		|		|	97
SHARED_FED_OP_EXP_PER	|	D	|	2	|	1	|		|		|	X	|		|		|		|		|	Y	|		|		|	119
INDV_ITEM_CONTB	|	R	|	1	|	2	|		|	X	|		|		|		|		|		|	Y	|	2004	|	17A	|	65
INDV_ITEM_CONTB	|	R	|	1	|	2	|	X	|		|		|		|		|		|		|	N	|	2010	|	11AI	|	69
INDV_ITEM_CONTB	|	R	|	1	|	2	|	X	|		|		|		|		|		|		|	Y	|	2004	|	11AI	|	70
COH_COP	|	C	|	3	|	2	|	X	|	X	|	X	|	X	|		|		|		|	N	|		|		|	98
INDV_ITEM_CONTB	|	R	|	1	|	2	|		|		|	X	|		|		|		|		|	N	|	2010	|	11AI	|	103
INDV_ITEM_CONTB	|	R	|	1	|	2	|		|		|	X	|		|		|		|		|	Y	|	2004	|	11AI	|	104
SHARED_NONFED_OP_EXP_PER	|	D	|	2	|	2	|		|		|	X	|		|		|		|		|	Y	|		|		|	120
NET_CONTB	|	C	|	3	|	3	|		|	X	|		|		|		|		|		|	N	|		|		|	1
NET_CONTB	|	C	|	3	|	3	|		|		|	X	|		|		|		|		|	N	|		|		|	30
INDV_CONTB	|	R	|	1	|	3	|		|		|		|	X	|		|		|		|	Y	|		|	14A	|	33
NET_CONTB	|	C	|	3	|	3	|	X	|		|		|		|		|		|		|	N	|		|		|	99
OTHER_FED_OP_EXP_PER	|	D	|	2	|	3	|		|		|	X	|		|		|		|		|	Y	|		|	21B	|	121
INDV_UNITEM_CONTB	|	R	|	1	|	4	|		|	X	|		|		|		|		|		|	Y	|	2004	|		|	4
OP_EXP_PER	|	D	|	2	|	4	|		|	X	|		|		|		|		|		|	Y	|		|	23	|	18
NET_CONTB	|	C	|	3	|	4	|		|		|		|		|		|		|	X	|	N	|		|		|	64
INDV_UNITEM_CONTB	|	R	|	1	|	4	|	X	|		|		|		|		|		|		|	Y	|	2004	|		|	71
OP_EXP_PER	|	D	|	2	|	4	|	X	|		|		|		|		|		|		|	Y	|		|	17	|	86
INDV_UNITEM_CONTB	|	R	|	1	|	4	|		|		|	X	|		|		|		|		|	Y	|	2004	|		|	105
NET_OP_EXP	|	C	|	3	|	5	|		|	X	|		|		|		|		|		|	N	|		|		|	2
NET_OP_EXP	|	C	|	3	|	5	|		|		|	X	|		|		|		|		|	N	|		|		|	31
INDV_UNITEM_CONTB	|	R	|	1	|	5	|		|		|		|	X	|		|		|		|	Y	|		|		|	34
NET_OP_EXP	|	C	|	3	|	5	|	X	|		|		|		|		|		|		|	N	|		|		|	100
TTL_OP_EXP_PER	|	D	|	2	|	5	|		|		|	X	|		|		|		|		|	N	|		|		|	122
ITEM_CONVN_EXP_DISB_PER	|	D	|	2	|	6	|		|		|		|	X	|		|		|		|	Y	|		|	21A	|	49
INDV_CONTB	|	R	|	1	|	6	|		|	X	|		|		|		|		|		|	Y	|	2002	|	17A	|	66
INDV_CONTB	|	R	|	1	|	6	|		|	X	|		|		|		|		|		|	Y	|	2010	|	17A	|	67
INDV_CONTB	|	R	|	1	|	6	|		|	X	|		|		|		|		|		|	N	|	2004	|		|	68
INDV_CONTB	|	R	|	1	|	6	|	X	|		|	X	|		|		|		|		|	Y	|	2002	|	11AI	|	72
INDV_CONTB	|	R	|	1	|	6	|	X	|		|	X	|		|		|		|		|	Y	|	2010	|	11AI	|	73
INDV_CONTB	|	R	|	1	|	6	|	X	|		|	X	|		|		|		|		|	N	|	2004	|		|	74
DEBTS_OWED_BY_CMTE	|	C	|	3	|	6	|	X	|	X	|	X	|	X	|		|		|		|	N	|		|		|	101
TTL_CONTB	|	R	|	1	|	7	|		|		|		|	X	|		|		|		|	N	|		|		|	35
UNITEM_CONVN_EXP_DISB_PER	|	D	|	2	|	7	|		|		|		|	X	|		|		|		|	Y	|		|		|	50
DEBTS_OWED_TO_CMTE	|	C	|	3	|	7	|	X	|	X	|	X	|	X	|		|		|		|	N	|		|		|	102
PTY_CMTE_CONTB	|	R	|	1	|	8	|		|	X	|		|		|		|		|		|	Y	|		|	17B	|	5
SUBTTL_CONVN_EXP_DISB_PER	|	D	|	2	|	8	|		|		|		|	X	|		|		|		|	N	|		|		|	51
PTY_CMTE_CONTB	|	R	|	1	|	8	|	X	|		|		|		|		|		|		|	Y	|		|	11B	|	75
PTY_CMTE_CONTB	|	R	|	1	|	8	|		|		|	X	|		|		|		|		|	Y	|		|	11B	|	106
OTH_CMTE_CONTB	|	R	|	1	|	9	|		|	X	|		|		|		|		|		|	Y	|		|	17C	|	6
TRANF_TO_OTHER_AUTH_CMTE	|	D	|	2	|	9	|		|	X	|		|		|		|		|		|	Y	|		|	24	|	19
OTH_CMTE_CONTB	|	R	|	1	|	9	|	X	|		|		|		|		|		|		|	Y	|		|	11C	|	76
TRANF_TO_OTHER_AUTH_CMTE	|	D	|	2	|	9	|	X	|		|		|		|		|		|		|	Y	|		|	18	|	87
OTH_CMTE_CONTB	|	R	|	1	|	9	|		|		|	X	|		|		|		|		|	Y	|		|	11C	|	107
CAND_CNTB	|	R	|	1	|	10	|		|	X	|		|		|		|		|		|	Y	|		|	17D	|	7
TRANF_TO_OTHER_AUTH_CMTE	|	D	|	2	|	10	|		|		|		|	X	|		|		|		|	Y	|		|	22	|	52
CAND_CNTB	|	R	|	1	|	10	|	X	|		|		|		|		|		|		|	Y	|		|	11D	|	77
TRANF_TO_OTHER_AUTH_CMTE	|	D	|	2	|	10	|		|		|	X	|		|		|		|		|	Y	|		|	22	|	123
TTL_CONTB	|	R	|	1	|	11	|		|	X	|		|		|		|		|		|	N	|		|		|	8
FNDRSG_DISB	|	D	|	2	|	11	|		|	X	|		|		|		|		|		|	Y	|		|	25	|	20
TTL_CONTB	|	R	|	1	|	11	|		|		|		|		|	X	|		|		|	N	|		|	F56	|	59
TTL_CONTB	|	R	|	1	|	11	|	X	|		|		|		|		|		|		|	N	|		|		|	78
TTL_CONTB	|	R	|	1	|	11	|		|		|	X	|		|		|		|		|	N	|		|		|	108
TRANF_FROM_OTHER_AUTH_CMTE	|	R	|	1	|	12	|		|	X	|		|		|		|		|		|	Y	|		|	18	|	9
EXEMPT_LEGAL_ACCTG_DISB	|	D	|	2	|	12	|		|	X	|		|		|		|		|		|	Y	|		|	26	|	21
TRANF_FROM_OTHER_AUTH_CMTE	|	R	|	1	|	12	|	X	|		|		|		|		|		|		|	Y	|		|	12	|	79
TRANF_FROM_OTHER_AUTH_CMTE	|	R	|	1	|	13	|		|		|		|	X	|		|		|		|	Y	|		|	15	|	36
TRANF_FROM_OTHER_AUTH_CMTE	|	R	|	1	|	13	|		|		|	X	|		|		|		|		|	Y	|		|	12	|	109
FED_CAND_CMTE_CONTB_PER	|	D	|	2	|	13	|		|		|	X	|		|		|		|		|	Y	|		|	23	|	124
CAND_LOAN	|	R	|	1	|	14	|		|	X	|		|		|		|		|		|	Y	|		|	19A	|	10
INDT_EXP_PER	|	D	|	2	|	14	|		|		|		|		|	X	|		|		|	Y	|		|	F57	|	60
CAND_LOAN	|	R	|	1	|	14	|	X	|		|		|		|		|		|		|	Y	|		|	13A	|	80
INDT_EXP_PER	|	D	|	2	|	14	|		|		|	X	|		|		|		|		|	Y	|		|	24	|	125
OTH_LOANS	|	R	|	1	|	15	|		|	X	|		|		|		|		|		|	Y	|		|	19B	|	11
OTH_LOANS	|	R	|	1	|	15	|	X	|		|		|		|		|		|		|	Y	|		|	13B	|	81
COORD_EXP_BY_PTY_CMTE_PER	|	D	|	2	|	15	|		|		|	X	|		|		|		|		|	Y	|		|	25	|	126
CAND_LOAN_REPYMNT	|	D	|	2	|	16	|		|	X	|		|		|		|		|		|	Y	|		|	27A	|	22
ALL_LOANS_RECEIVED_PER	|	R	|	1	|	16	|		|		|		|	X	|		|		|		|	Y	|		|	16A	|	37
CAND_LOAN_REPYMNT	|	D	|	2	|	16	|	X	|		|		|		|		|		|		|	Y	|		|	19A	|	88
ALL_LOANS_RECEIVED_PER	|	R	|	1	|	16	|		|		|	X	|		|		|		|		|	Y	|		|	13	|	110
OTH_LOAN_REPYMTS	|	D	|	2	|	17	|		|	X	|		|		|		|		|		|	Y	|		|	27B	|	23
LOAN_REPYMTS_RECEIVED_PER	|	R	|	1	|	17	|		|		|		|	X	|		|		|		|	Y	|		|	16B	|	38
OTH_LOAN_REPYMTS	|	D	|	2	|	17	|	X	|		|		|		|		|		|		|	Y	|		|	19B	|	89
LOAN_REPYMTS_RECEIVED_PER	|	R	|	1	|	17	|		|		|	X	|		|		|		|		|	Y	|		|	14	|	111
TTL_LOANS	|	R	|	1	|	18	|		|	X	|		|		|		|		|		|	N	|		|		|	12
TTL_LOAN_REPYMTS	|	D	|	2	|	18	|		|	X	|		|		|		|		|		|	N	|		|		|	24
TTL_LOANS	|	R	|	1	|	18	|	X	|		|		|		|		|		|		|	N	|		|		|	82
TTL_LOAN_REPYMTS	|	D	|	2	|	18	|	X	|		|		|		|		|		|		|	N	|		|		|	90
TTL_LOANS	|	R	|	1	|	19	|		|		|		|	X	|		|		|		|	N	|		|		|	39
LOANS_MADE_PER	|	D	|	2	|	19	|		|		|		|	X	|		|		|		|	Y	|		|	23A	|	53
LOANS_MADE_PER	|	D	|	2	|	19	|		|		|	X	|		|		|		|		|	Y	|		|	27	|	127
OFFSETS_TO_OP_EXP	|	R	|	1	|	20	|		|	X	|		|		|		|		|		|	Y	|		|	20A	|	13
OTH_LOAN_REPYMTS	|	D	|	2	|	20	|		|		|		|	X	|		|		|		|	Y	|		|	23B	|	54
OFFSETS_TO_OP_EXP	|	R	|	1	|	20	|	X	|		|		|		|		|		|		|	Y	|		|	14	|	83
OFFSETS_TO_OP_EXP	|	R	|	1	|	20	|		|		|	X	|		|		|		|		|	Y	|		|	15	|	112
OTH_LOAN_REPYMTS	|	D	|	2	|	20	|		|		|	X	|		|		|		|		|	Y	|		|	26	|	128
TTL_LOAN_REPYMTS	|	D	|	2	|	21	|		|		|		|	X	|		|		|		|	N	|		|		|	55
FED_CAND_CONTB_REF_PER	|	R	|	1	|	21	|		|		|	X	|		|		|		|		|	Y	|		|	16	|	113
INDV_REF	|	D	|	2	|	22	|		|		|	X	|		|		|		|		|	Y	|		|	28A	|	25
ITEM_REF_REB_RET_PER	|	R	|	1	|	22	|		|		|		|	X	|		|		|		|	Y	|		|	17A	|	40
INDV_REF	|	D	|	2	|	22	|	X	|		|		|		|		|		|		|	Y	|		|	20A	|	91
INDV_REF	|	D	|	2	|	22	|		|	X	|		|		|		|		|		|	Y	|		|	28A	|	129
POL_PTY_CMTE_CONTB	|	D	|	2	|	23	|		|		|	X	|		|		|		|		|	Y	|		|	28B	|	26
UNITEM_REF_REB_RET_PER	|	R	|	1	|	23	|		|		|		|	X	|		|		|		|	Y	|		|		|	41
POL_PTY_CMTE_CONTB	|	D	|	2	|	23	|	X	|		|		|		|		|		|		|	Y	|		|	20B	|	92
POL_PTY_CMTE_CONTB	|	D	|	2	|	23	|		|	X	|		|		|		|		|		|	Y	|		|	28B	|	130
OTH_CMTE_REF	|	D	|	2	|	24	|		|	X	|		|		|		|		|		|	Y	|		|	28C	|	27
SUBTTL_REF_REB_RET_PER	|	R	|	1	|	24	|		|		|		|	X	|		|		|		|	N	|		|		|	42
OTH_CMTE_REF	|	D	|	2	|	24	|	X	|		|		|		|		|		|		|	Y	|		|	20C	|	93
OTH_CMTE_REF	|	D	|	2	|	24	|		|		|	X	|		|		|		|		|	Y	|		|	28C	|	131
TTL_CONTB_REF	|	D	|	2	|	25	|		|		|	X	|		|		|		|		|	N	|		|		|	28
ITEM_OTHER_REF_REB_RET_PER	|	R	|	1	|	25	|		|		|		|	X	|		|		|		|	Y	|		|	18A	|	43
TTL_CONTB_REF	|	D	|	2	|	25	|	X	|		|		|		|		|		|		|	N	|		|		|	94
TTL_CONTB_REF	|	D	|	2	|	25	|		|	X	|		|		|		|		|		|	N	|		|		|	132
UNITEM_OTHER_REF_REB_RET_PER	|	R	|	1	|	26	|		|		|		|	X	|		|		|		|	Y	|		|		|	44
TTL_CONTB_REF	|	D	|	2	|	26	|		|		|		|		|		|		|	X	|	N	|		|	SB	|	63
SUBTTL_OTHER_REF_REB_RET_PER	|	R	|	1	|	27	|		|		|		|	X	|		|		|		|	N	|		|		|	45
ITEM_OTHER_DISB_PER	|	D	|	2	|	27	|		|		|		|	X	|		|		|		|	Y	|		|	24A	|	56
OFFSETS_TO_FNDRSG	|	R	|	1	|	28	|		|	X	|		|		|		|		|		|	Y	|		|	20B	|	14
UNITEM_OTHER_DISB_PER	|	D	|	2	|	28	|		|		|		|	X	|		|		|		|	Y	|		|		|	57
OFFSETS_TO_LEGAL_ACCTG	|	R	|	1	|	29	|		|	X	|		|		|		|		|		|	Y	|		|	20C	|	15
OTHER_DISB_PER	|	D	|	2	|	29	|		|	X	|		|		|		|		|		|	Y	|		|	29	|	29
OTHER_DISB_PER	|	D	|	2	|	29	|	X	|		|		|		|		|		|		|	Y	|		|	21	|	95
OTHER_DISB_PER	|	D	|	2	|	29	|		|		|	X	|		|		|		|		|	Y	|		|	29	|	133
TTL_OFFSETS_TO_OP_EXP	|	R	|	1	|	30	|		|	X	|		|		|		|		|		|	N	|		|		|	16
OTHER_DISB_PER	|	D	|	2	|	30	|		|		|		|	X	|		|		|		|	N	|		|		|	58
OTHER_RECEIPTS	|	R	|	1	|	31	|		|	X	|		|		|		|		|		|	Y	|		|	21	|	17
OTHER_RECEIPTS	|	R	|	1	|	31	|	X	|		|		|		|		|		|		|	Y	|		|	15	|	84
OTHER_RECEIPTS	|	R	|	1	|	31	|		|		|	X	|		|		|		|		|	Y	|		|	17	|	114
SHARED_FED_ACTVY_FED_SHR_PER	|	D	|	2	|	31	|		|		|	X	|		|		|		|		|	Y	|		|		|	134
ITEM_OTHER_INCOME_PER	|	R	|	1	|	32	|		|		|		|	X	|		|		|		|	Y	|		|	19A	|	46
SHARED_FED_ACTVY_NONFED_PER	|	D	|	2	|	32	|		|		|	X	|		|		|		|		|	Y	|		|		|	135
UNITEM_OTHER_INCOME_PER	|	R	|	1	|	33	|		|		|		|	X	|		|		|		|	Y	|		|		|	47
NON_ALLOC_FED_ELECT_ACTVY_PER	|	D	|	2	|	33	|		|		|	X	|		|		|		|		|	Y	|		|	30B	|	136
OTHER_RECEIPTS	|	R	|	1	|	34	|		|		|		|	X	|		|		|		|	Y	|		|		|	48
TTL_FED_ELECT_ACTVY_PER	|	D	|	2	|	34	|		|		|	X	|		|		|		|		|	N	|		|		|	137
TRANF_FROM_NONFED_ACCT_PER	|	R	|	1	|	35	|		|		|	X	|		|		|		|		|	Y	|		|		|	115
TTL_FED_DISB_PER	|	D	|	2	|	35	|		|		|	X	|		|		|		|		|	N	|		|		|	138
TTL_DISB	|	D	|	2	|	36	|	X	|	X	|	X	|	X	|		|		|		|	N	|		|		|	96
TRANF_FROM_NONFED_LEVIN_PER	|	R	|	1	|	36	|		|		|	X	|		|		|		|		|	Y	|		|		|	116
TTL_COMMUNICATION_COST	|	D	|	2	|	37	|		|		|		|		|		|	X	|		|	N	|		|	F76	|	61
TTL_NONFED_TRANF_PER	|	R	|	1	|	37	|		|		|	X	|		|		|		|		|	N	|		|		|	117
TTL_FED_RECEIPTS_PER	|	R	|	1	|	38	|		|		|	X	|		|		|		|		|	N	|		|		|	118
TTL_RECEIPTS	|	R	|	1	|	39	|	X	|	X	|	X	|	X	|		|		|		|	N	|		|		|	85
TTL_RECEIPTS	|	R	|	1	|	40	|		|		|		|		|		|		|	X	|	N	|		|	SA	|	62

**Comment by PaulClark2** [comment]
So the SA table would look something like this.   If we need this, does it need to include Line numbers?

Schedule A column names	|	description
----	|	----
sa.cmte_id,	|	committee id
sa.cmte_nm,	|	committee name
sa.contbr_id,	|	contributor id
sa.contbr_nm,	|	contributor name
sa.contbr_nm_first,	|	contributor first name
sa.contbr_m_nm,	|	contributor middle name
sa.contbr_nm_last,	|	contributor last name
sa.contbr_prefix,	|	contributor name prefix
sa.contbr_suffix,	|	contributor name suffix
sa.contbr_st1,	|	contributor street 1
sa.contbr_st2,	|	contributor street 2
sa.contbr_city,	|	contributor city
sa.contbr_st,	|	contributor state
sa.contbr_zip,	|	contributor zip code
sa.entity_tp,	|	entity type
sa.entity_tp_desc,	|	entity type description
sa.contbr_employer,	|	contributor employer
sa.contbr_occupation,	|	contributor occupation
sa.election_tp,	|	election type
sa.fec_election_tp_desc,	|	fec election type description
sa.fec_election_yr,	|	fec election year
sa.election_tp_desc,	|	election type description
sa.contb_aggregate_ytd,	|	contribution aggregate year to date
sa.contb_receipt_dt,	|	contribution receipt date
sa.contb_receipt_amt,	|	contribution receipt amount
sa.receipt_tp,	|	receipt type
sa.receipt_tp_desc,	|	receipt type description
sa.receipt_desc,	|	receipt description
sa.memo_cd,	|	memo code
sa.memo_cd_desc,	|	memo code description
sa.memo_text,	|	memo text
sa.cand_id,	|	candidate id
sa.cand_nm,	|	candidate name
sa.cand_nm_first,	|	candidate first name
sa.cand_m_nm,	|	candidate middle name
sa.cand_nm_last,	|	candidate last name
sa.cand_prefix,	|	candidate name prefix
sa.cand_suffix,	|	candidate name suffix
sa.cand_office,	|	candidate office
sa.cand_office_desc,	|	candidate office description
sa.cand_office_st,	|	candidate office state
sa.cand_office_st_desc,	|	candidate office state description
sa.cand_office_district,	|	candidate office district
sa.conduit_cmte_id,	|	counduit committee id
sa.conduit_cmte_nm,	|	conduit committee name
sa.conduit_cmte_st1,	|	conduit committee street 1
sa.conduit_cmte_st2,	|	conduit committee street 2
sa.conduit_cmte_city,	|	conduit committee city
sa.conduit_cmte_st,	|	conduit committee state
sa.conduit_cmte_zip,	|	conduit committee zip code
sa.donor_cmte_nm,	|	donor committee name
sa.national_cmte_nonfed_acct,	|	national committee nonfederal account
sa.increased_limit,	|	increased limit
sa.amndt_ind as action_cd,	|	action code
sa.amndt_ind_desc as action_cd_desc,	|	action code description
(case when substr(sa.sub_id,1,1) = 4 then sa.tran_id else null end) as tran_id,	|	transaction id
(case when substr(sa.sub_id,1,1) = 4 then sa.back_ref_tran_id else null end) as back_ref_tran_id,	|	back reference transaction id
sa.back_ref_sched_nm,	|	schedule name
vs.form_tp_cd as filing_form,	|	filing form
sa.form_tp as schedule_type,	|	schedule type
sa.form_tp_desc as schedule_type_desc,	|	schedule type description
sa.line_num,	|	line number
sa.image_num,	|	image number
sa.file_num,	|	file number
sa.sub_id,	|	sub_id
sa.link_id,	|	link_id
sa.orig_sub_id	|	original sub_Id

**Comment by noahmanger** [comment]
Can we close this issue? @LindsayYoung anything else you need?

**Comment by LindsayYoung** [comment]
We don't need anything else, but we should move this to a better place. Maybe google docs or the wiki for now.

**Comment by noahmanger** [comment]
Cool. I just dropped it here: https://github.com/18F/openFEC/wiki/Schedule-A-column-documentation
