### ISSUE TITLE
drivers of openFEC features

### ISSUE THREAD

**Issue by acapizzi** [18F/openFEC#1556]
I am interested in the design process the 18F team used in starting openFEC.  In particular:

- What features of the existing Campaign Finance Disclosure Portal needed improvement or were important to keep?
- What sort of use does FEC's existing data portal get?  Does openFEC aim to change a particular type of issue, or generally ease access for all?
- Did 18F conduct research with FEC personnel before starting openFEC?  If so, were there any non-technology insights that came out of that?
- Did 18F conduct research with the journalists, researchers, and other potential users of FEC data? If so, were there any insights worth sharing that are informing openFEC development?
- Is openFEC focusing on wholesale data access, or including visualization or other data exploration and manipulation for typical users?

**Comment by LindsayYoung** [comment]
These are fantastic questions! I am gong to give some quick answers and let other people from the team chime in too. I am on the developer side of things and they might be able to give better description of our plans and research. 

## What features of the existing Campaign Finance Disclosure Portal needed improvement or were important to keep?
The existing Portal does a good job of making all of the data available, but our research showed that users have a hard time finding what they’re looking for, understanding what they find, and sharing the data. With betaFEC we’ve taken the approach of trying to address root user needs, rather than building a one-to-one replacement for the current tool. 

## What sort of use does FEC's existing data portal get? Does openFEC aim to change a particular type of issue, or generally ease access for all?
The existing site draws a lot of traffic from many types of users: reporters, campaign staff, academics, and everyday members of the public. One of our goals with this project is to make the site a more welcoming site that is engaging to a wide spectrum of users. For example, we hypothesize that jargon and difficult information architecture has been a barrier that kept the public from using the site. 

## Did 18F conduct research with FEC personnel before starting openFEC? If so, were there any non-technology insights that came out of that?
 The short answer is yes. There were public meetings and numerous interviews that helped inform our approach and priorities for the project. The insights we have gained from users have been invaluable. 

## Did 18F conduct research with the journalists, researchers, and other potential users of FEC data? If so, were there any insights worth sharing that are informing openFEC development?
 Yes, @onezerojeremy @noahmanger @jenniferthibault @emileighoutlaw should probably do a blog post on this! We did extensive user research talking journalists, researchers, members of the public, academic, and more. We learned so much from these interviews, for example: users often are looking for information on a specific candidate or committee, so we wanted to make this method of searching for candidates and committees fast and easy. 

In addition to these discovery interviews, we also do weekly usability tests with our users. (Sign up on [beta.fec.gov](https://beta.fec.gov/) if you would like to be interviewed as part of our process.) The research guides our planing and decision making for the project. 

## Is openFEC focusing on wholesale data access, or including visualization or other data exploration and manipulation for typical users?

Our API api.open.fec is focused on data access and also powers beta.fec.gov, where we are planning even more visualization work and things to enhance the experience for general users.

**Comment by noahmanger** [comment]
Closing this. We can reopen if there's further discussion.
