### ISSUE TITLE
API Pull-Election Year 

### ISSUE THREAD

**Issue by gmj2053** [18F/openFEC#1560]
We are using the API pull to create our candidate list to process for the US Elections.  We did our first pull into the DB and I see some weird results.  We want to pull by Election Year (2016 right now).  When you filter using Election Years 2015-2016, you get John Edwards, who ran in 2008
https://beta.fec.gov/data/candidates/?q=edwards&cycle=2016
When you pull him in the "regular" FEC you see
Name: EDWARDS, JOHN (O - OPEN)
Office Sought: P - PRESIDENT
Election Year: 2008
State: US - UNITED STATES, District: 00
Party: DEMOCRATIC PARTY

and also 
https://beta.fec.gov/data/candidates/?q=Nelson&cycle=2016
Bill nelson is a candidate in 2018, not 2016
"regular" fec pull say
Name: NELSON, BILL (I - INCUMBENT)
Office Sought: S - SENATE
Election Year: 2018
State: FL - FLORIDA, District: 00
Party: DEMOCRATIC PARTY

Are we confused by what the API is calling election year?  Is there a better way to refine our query?

Thanks!
Gina Jones

**Comment by LindsayYoung** [comment]
Hello Gina!

The API and the web app can act a little differently. You linked to the website, so that is what I will explain feel free to ask additional questions about the API or anything else.

Right now, Edwards is showing up because his committee is still active, this understandably confuses people. We are changing the behavior here: 18F/openFEC-web-app/pull/1109 that change should be made soon. 

Thanks for your patience and taking the time to give your feedback!

**Comment by gmj2053** [comment]
I do think the confusion is about 'cycle' , I think I am querying the FEC API for election, because the filters on the left say "election".  but that is cycle, which is as you say his committee is still active.  I will let you know if that helps.
