### ISSUE TITLE
Issue with "name" field on FEC API candidate endpoint

### ISSUE THREAD

**Issue by wilbhall** [18F/openFEC#1593]
There no longer seems to be a parameter "name" in the FEC API endpoint under candidates. Queries from iOS code that sent a name parameter to that endpoint just yesterday (March 30th) and worked, are having no effect today. What is more, the "name" parameter no longer appears in the description for the endpoint at https://api.open.fec.gov/developers/#!/candidate/get_candidates.
Apparently, one can now only use this endpoint if one knows the candidate's ID. Is there some new way to find the candidate ID given the name?

EX: The following GET URL worked correctly with Postman on Wed, Mar 30, i.e., it returned a JSON object of all candidates with the letters "clinton" in the name field. It now (April 1) returns a paginated JSON object of all candidates. It seems that the key-value pair {name: XXXX} is now being ignored.

https://api.open.fec.gov/v1/candidates/search/?api_key=DEMO_KEY&name=clinton&per_page=20&page=1&sort=name&sort_nulls_large=true

Regards,
Joe Leichter

**Comment by LindsayYoung** [comment]
Thank you for writing in!

You will want to use `q=`
https://api.open.fec.gov/v1/candidates/search/?api_key=DEMO_KEY&q=clinton&per_page=20&page=1&sort=name&sort_nulls_large=true

We had two ways of doing name searching, but q works better-- it was a tsvector instead of a string, so we dropped name, since it was duplicative. 

I can see how this was disruptive for you. We can add that functionality back so that `name=` will get you the same, better version of search. Since it is Friday afternoon, we won't be able to get to it right away, so you can use `q` in the meantime.

**Comment by wilbhall** [comment]
Great, thank you so much!

Joe Leichter
