### ISSUE TITLE
Style breadcrumbs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1595]
Usability testing revealed the breadcrumb pattern clearly works. Users noticed them, they understood where it put them in the information hierarchy of the site, and they knew how to use them to navigate up the hierarchy.

Here is example of the logic of the breadcrumbs:

![breadcrumbs](https://cloud.githubusercontent.com/assets/1696495/14222434/8572de88-f825-11e5-8793-b68aeab57341.png)

Note: We will not show siblings, and we need a way to visually distinguish non-link parent category titles from parent pages that are links.

Once the designs are complete, we will implement in https://github.com/18F/openFEC-web-app/issues/1154

**Comment by jenniferthibault** [comment]
I'm proposing a more simple solution than you've outlined above @noahmanger — based on if it can be clicked or not instead of revealing so much about our structure. This might be unpopular 😁  but here goes:

The system is:
- If you can click it (if it's a page or a linked parent category) then it's `$inverse` (white) and underlined.
- If you can't click it (if it's a category or the current page you're on) then it's `$gray` and not underlined.

These combos do pass requirements for 508 color contrast ratios :)

![screen shot 2016-04-08 at 7 38 18 pm](https://cloud.githubusercontent.com/assets/11636908/14400086/7bc7a836-fdc1-11e5-80b4-e1cb8792d2ad.png)


![screen shot 2016-04-08 at 7 39 56 pm](https://cloud.githubusercontent.com/assets/11636908/14400101/b596c59c-fdc1-11e5-8208-59de1e0770fd.png)


A thing we probably want to think about and I've included above, is truncating very long page names

One change I'd consider making if we feel it's necessary is making the current page a bit more visually distinct in a subtle way. Mocked up below to demonstrate, but I do prefer the simplicity above^
![screen shot 2016-04-08 at 7 41 08 pm](https://cloud.githubusercontent.com/assets/11636908/14400134/f34fcafa-fdc1-11e5-899d-fed88afd96a1.png)

cc @emileighoutlaw

**Comment by noahmanger** [comment]
I meant to respond earlier:

This looks great. I love the simpler approach. I think it _might_ be good to make the current page bold, though. Or at maybe white? What do you think? 

And +1 to truncating long names. That's easy and a good idea.

Just gimme the word and I can move this to implementation.

**Comment by jenniferthibault** [comment]
**Bold / Grey**
(This feels too easy to ignore)

![screen shot 2016-04-13 at 9 55 57 am](https://cloud.githubusercontent.com/assets/11636908/14495561/085db46c-015e-11e6-8e94-5964ca417942.png)


**Italic / White**
(This feels right but I don't think Karla performs well as Italic, so I'd prefer another approach if we can)

![screen shot 2016-04-13 at 9 55 41 am](https://cloud.githubusercontent.com/assets/11636908/14495585/1bc20c06-015e-11e6-9244-57903c9569f7.png)


**White / Bold**
(This feels good to me, but I'm worried it could come off too strong in the header space, which is already busy. Let's lead with this, and downgrade it to the regular italic weight if it feels like too much in context)

![screen shot 2016-04-13 at 9 56 03 am](https://cloud.githubusercontent.com/assets/11636908/14495598/2801dc12-015e-11e6-9cec-f2f3725463af.png)

If you agree, @noahmanger , feel free to take it from here!

**Comment by emileighoutlaw** [comment]
I've been following this quietly, but I did want to make sure that I explicitly said I am 👍 with truncating the text

**Comment by noahmanger** [comment]
Per this morning, going with simply showing the current page as white, but not bold. Moved to implementation.
