### ISSUE TITLE
Detailed information design of the new data landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1596]
## Task:
Wireframe detailed information and interaction mockups of the new data landing page that can then be visually styled.

## Background:
Usability testing for the dashboard concepts has surfaced a few strong insights, though some questions still remain. Here's my summary of the synthesis we worked on this morning, but please jump in if I'm missing or mis-characterizing anything here, @emileighoutlaw and @brethauer .

### Insights:
- Overall, the dashboard concepts (at each level: landing, overview, and details) have helped introduce people to the data, given them trailheads to provoke further exploring, and given them valuable insights into top-level summaries and trends. 
- Users prefer the approach of Option B, which presents questions as links in to specific parts of the overview pages
- Users make use of opportunities to both follow links to specific candidates and committees as well as continuing to explore top-level summaries
- Users appreciate the inclusion of visualizations, totals and rankings on the landing page, inspiring them to dig in further
- For certain tasks, users still gravitate to the datatable pages, though it's unclear if this is an actual problem
- Users expect to be able to access underlying raw data behind any given visualization or total as a means of exploring further 
- Users found the fundraising visualization in the prototypes easier to understand than the spending one

### Still not clear on
The major thing we're still not clear on is which organizational model works best. Users did seem to value the Candidate Details page from Option B, which presented all the types of data for candidates all together (rathe than separate fundraising and spending pages). The lack of a clear signal may be to lack of any major advantage to one than the other, so we should perhaps just pick an approach and try it out.

**Comment by brethauer** [comment]
@noahmanger @emileighoutlaw and @jenniferthibault : Here is the dashboard research summary doc I put together, which looks across all the research from the last 3 weeks.  It is organized by similar screens where appropriate (e.g. insights for both landing A and B together in order to see where the strengths of each are).

My goal was that this was detailed enough to give us some feedback/insights that are specific enough about the things we tested so that we can be confident about what needs changing, possible refinement, and what things are strong.

https://docs.google.com/document/d/1Pt-0TtdxS1RpKj_s-0vdAWFwMRLtaQeqG2MO-6B9DqA/edit#

**Comment by noahmanger** [comment]
Alright, after several good 1-on-1 and group critiques, I think we have this in a pretty good place:

![a 1 1 landing](https://cloud.githubusercontent.com/assets/1696495/14570206/e85e3fd8-02f7-11e6-8bc7-22944d55b65d.png)

@jenniferthibault what do you think about closing this in favor of future issues for visual design and implementation?

**Comment by jenniferthibault** [comment]
Closing in favor of visual design in https://github.com/18F/fec-style/issues/322
