### ISSUE TITLE
Filings Endpoint Pagination Issue

### ISSUE THREAD

**Issue by kg4097** [18F/openFEC#1598]
I noticed an error with the filings endpoint. The 'page' and 'count' parameters are often inaccurate with many combinations of other parameters. For example, when you use the parameters report_year = 2016, per_page = 100, and list all possible report_types the resulting json reports that there are 112 pages and 11170 results (count), but only 45 pages have results. This occurs with both the demo api key and my assigned api key.

**Comment by LindsayYoung** [comment]
For the larger, transactional endpoints, the page count is approximate. [This blogpost](https://18f.gsa.gov/2015/07/15/openfec-api-update/) goes into more detail. Basically, for these custom queries on large datasets, it can take over a minute to make an exact count. Since adding that overhead to each API call is not feasible, we use a count estimate. 

Thanks for writing in, it is important for us to incorporate this kind of feedback as the FEC API continues to evolve.

**Comment by kg4097** [comment]
Awesome, thank you!
