### ISSUE TITLE
Make schedule_b filter for operating expenditures

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1607]
In order to make a datatable page for just operating expenditures, we need to be able to filter down schedule b's. 

Related frontend changes and convo: https://github.com/18F/openFEC-web-app/issues/1148

From @PaulClark2 : 

> It's a fairly straightforward query. We need to select all the uncategorized transactions on Line 17 of Form 3, Line 23 on Form 3P and Line 21 on Form 3X.
> 
> Here's how we are doing it for the bulk download file (http://www.fec.gov/finance/disclosure/ftpdet.shtml#a2015_2016)

```
FROM f_item_receipt_or_exp f_item
JOIN f_rpt_or_form_sub frpt ON f_item.v_sum_link_id=frpt.sub_id
WHERE f_item.transaction_tp IS NULL 
AND f_item.sched_tp_cd = 'SB'
AND ( (frpt.form_tp = 'F3' AND line_num = '17')
OR (frpt.form_tp = 'F3P' AND line_num = '23')
OR (frpt.form_tp = 'F3X' AND line_num LIKE '21%'))
```

**Comment by LindsayYoung** [comment]
1) we might want to implement this after downloads, since this could complicate queries and slow things down
2) I think I would like to have this implemented with 2 new fields, one that is a form type line number combination, and a field that explains what that means (from the form instructions), so form and line number would be `F3-17` and a line number explanation field would say "total amount of operating expenditures" based on [the instructions](http://www.fec.gov/pdf/forms/fecfrm3i.pdf). That way, we are adding one filter and making it more flexible.

**Comment by PaulClark2** [comment]
We may want to include operating expenditures from Form 4s, too.  Form 4 Line 21(a)
