### ISSUE TITLE
Respond to calendar feedback and questions

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1619]

**Comment by emileighoutlaw** [comment]
Separated this out into Design tasks, Content tasks, and Dev tasks. 

## Design 
- [ ] Learn more link: FEC has asked us to make all our “learn more” links more prominent. @jenniferthibault , do you have thoughts on this? 

## Content 

### General

#### To do:
- [ ] Remove “th” in dates in calendar list view
- [ ] Remove report codes
- [ ] Add “held today” to all elections
- [ ] For clarity, add commas to descriptions. For example “MD: Senate Election, Primary Election”

### Filters

#### To do:
- [ ] Spell out FEA
- [ ] Spell out AOs

### Conferences
- [ ] Spacing of information. Add commas or periods, so we don’t have content that runs together, like “Orlando Regional ConferenceThe final FEC regional conference of the 2015-16 election cycle for candidates, parties and PACs.”

### Reports 

#### Done:
- “Due” should now visible in all description fields for reports.

#### To do:
- [ ] Pre- and post-election reports: We should put state name at beginning of name
- [ ] Elections: Put state name at beginning
- [ ] Elections: Put “held today” at the end

#### Notes:
- Missing location for Quarterly and Monthly reports: There is no location on the FEC.gov calendar for this either. What would the location be? 


## Data 

#### Done:
- Remove from calendar: All the following have been removed
     - April 5th ME Presidential Report Due
     - April 7th HI Presidential Report Due
     - April 11th MP Presidential Report Due and listed again on April 14th
     -  April 18th VI Presidential Report Due
     - April 21 Presidential Reports Due
     - April 25th GU Presidential Report Due
     - Remove VI Presidential Entry 
     - April 14th: Remove MP Presidential Entry 


#### To do
@LindsayYoung  I didn’t know how to answer or handle any of these ones
- [ ] Multi day events: April 2 lists ND Convention (and April 16 lists WY Convention), but they are multi-day events (April 1–3 and April 14–16). 

- [ ] April 21: Remove “Presidential Election Due.” 

- [ ] April 27: Need to distinguish between CT (Dem-H) Report Due vs. CT (Rep) Report Due. This is a unique situation. Please refer to the current calendar. 

- [ ] April 27: Entry for CT Senate now looks like it is for both parties and it is only for the Republicans: Lindsay, do you know what this is about? 

- [ ] April 28: Remove house election pre-primary reports. 

- [ ] April 28: Entries for NE and WV Reports  (?)

#### Notes:
- Adding links to report deadlines: _Those links go this page: http://www.fec.gov/info/report_dates_2016.shtml#quarterly, which is a table of calendar data and myriad other links; we think that page shouldn’t exist on the beta site, and are reticent to link to it. Would we like this to someday link to the appropriate forms for each report? That makes more sense to us and is do-able._

- *Combining separate events or separating combined events*: 
     - House and Senate pre- and post- reports: _This is possible but would require some data transformation that might be detrimental to the calendar long term. Is there a user need for combining these?_ 
     - Congressional and Presidential election dates: _This is the same question as above. It’s possible, but it requires data transformation we’re reticent to do._ 

- *Double entry*: UT Constitution party entered twice on April 9. _This has happened because it’s been entered in FEC’s system. CONSTITUTION PARTY is in caps because it’s in FEC’s system that way._

- *April 12th*: AL Runoff entry needs to be updated to state the Runoff is not held. _I think the issue here is that our calendar won’t update unless the election table is updated._

- Location: Add location to quarterly reports. _The FEC.gov calendar has “FEC” as the location, but that doesn’t seem like a useful addition to the calendar._

- Links to prior notices: for example http://www.fec.gov/pages/report_notices/2016/state_notices/ks_conv_lib.shtml. _Can someone tell us a little more about why it’s important to link to this notice (or to put it another way, what problem we’re trying to solve by linking to this)? The notice itself announces that the reports are due (which the calendar makes clear) and then covers information that about reporting requirements, which our new registration and reporting section should cover. Would it make sense to link to our new registration and reporting section from this page if people want to better understand filing requirements?_ 

- Conventions and caucuses are listed as “convention or caucus.” _Because of the way the data table is set up, we can’t pull just “convention” or “caucus.” They’re tagged as “convention or caucus.” This is a data entry problem we’d love to solve by changing the way we do data entry._

- Sep entries for MD and PA or find a way to provide the links for both for the same entry: _Can you explain more about what this means?_

**Comment by LindsayYoung** [comment]
The data things need to be fixed in FEC tables. I think we removed the presidential pre-primary but not presidential pre-caucus we might be able to tweak that.

**Comment by jenniferthibault** [comment]
@emileighoutlaw nice organization!

I may have missed something, but where did this feedback come from, and how was it gathered? (not disagreeing, just missed a beat and want to get myself up to speed) 

Before making design changes to the `Learn more` links, I'd like to understand what the motivation is, and if the feedback giver has a specific example of these instances being perceived as not prominent enough. They appear in different contexts on the grid view and the list view, so just want to make sure I understand the issue.

**Comment by LindsayYoung** [comment]
This is feedback from the FEC information division, that came in through slack.

**Comment by jenniferthibault** [comment]
Here are all the other issues that reference feedback on the calendar, on all repos:

https://github.com/18F/FEC/issues/253
https://github.com/18F/FEC/issues/301
https://github.com/18F/FEC/issues/303
https://github.com/18F/FEC/issues/297
https://github.com/18F/fec-cms/issues/264

There was also a great usability session last week that highlighted interaction/data weirdness with the calendar. @onezerojeremy is that in an issue/summarized somewhere?

**Comment by emileighoutlaw** [comment]
Here's an updated list of content tasks, based on our meeting with FEC last week. There's nothing necessary right now (from stakeholders) in terms of design edits. In terms of data, FEC just wants to confirm that our update events process is working in the way they expect it.

FEC has said that they'll feel comfortable switching to the beta calendar if they can:
1. Manually enter new events in all categories
2. Modify things that are already in the calendar
3. Delete things on the calendar
4. Confirm our process for updating events (things updated in tables *do* show up in beta properly. if not, we need to fix)
5. Make microcopy edits, so things are easier to read
6. (Nice to have but not necessary): Link to prior notices.

## Content tasks

### Calendar and filters:
- [ ] Remove “th” in dates in calendar list view
- [ ] Spell out FEA in filter sidebar
- [ ] Spell out AOs in filter sidebar

### Calendar events
- [ ] Remove report codes
- [ ] Microcopy edits to events so they are more human readable.
    - [ ] “held today” to all elections
    - [ ] “due today” to all reports
    - [ ] Add punctuation to descriptions. For example “MD: Senate Election, Primary Election held today”
    - [ ] For content events specifically Spacing of information. Add commas or periods, so we don’t have content that runs together, like “Orlando Regional ConferenceThe final FEC regional conference of the 2015-16 election cycle for candidates, parties and PACs.”

**Comment by onezerojeremy** [comment]
yes! as @jenniferthibault suggested there were a couple from our last usability session:
#1648 
#1650

**Comment by noahmanger** [comment]
Seeing the other issues linked to above (both from the feedback box and usability testing), it looks like we might need a more holistic design pass in addition to the content edits. @jenniferthibault this can be something we tackle together, perhaps designing this sprint and implementing the following?

**Comment by onezerojeremy** [comment]
Circling back on this: After discussing with @noahmanger & @jenniferthibault a bit (feel free to hit on things i missed yooz!) yielded the following:

Zooming out, while the calendar supports myriad use cases, two of the main ones are: 
- helping filers (and the watchers thereof) to know when their next reporting period deadline is
- helping those tracking AOs and other commission decisions (and events) see when things are happening. 

The calendar obviously needs to do other things, but if it's not doing those two well enough, we should make sure we prioritize fixing that. To wit:
- the usability issues above seem to indicate a need for layout which is at once easier to read and includes more content about each individual event in order for all but the most adroit users to understand what they contain. 
- two coming changes should help: 
1. the content changes should go a long way to helping make the calendar more comprehensible 
2. adding state filtering to everything will also help a lot with making the interface more consistent and understandable

- before we add features or enhancements, we should focus on fixing bugs (inclusive of usability/content/code); doing everything at once will make it hard to understand in testing if what we're doing is doing any good. (for example, a search for events might be an easy way around the fact that we haven't made the current way to navigate events easy, and while search will make it easy to find things you know about, such as deadlines, you might miss other things you would want to know about if you had a way of finding out about them). 

Our first move is always to try to make the simplest change that might make things better. To that end, we're first going to test simply changing the default from calendar view to list view and see if that helps folks understand what deadlines are coming, and what decisions are coming. (our assumption is that the calendar view, even with its space limitations is probably great for pro users who can quickly identify an event of interest from the first few words).

**Comment by jenniferthibault** [comment]
Thanks for capturing all this @onezerojeremy! Spot on.

(I did make one tiny edit directly to your comment because the "two coming changes" were rendering as same-level bullets instead of sub-points. Not a usual best practice, nor a habit I will continue, but thought it was small yet important here!) 

👏 👏 👏 
> Doing everything at once will make it hard to understand in testing if what we're doing is doing any good.
> Our first move is always to try to make the simplest change that might make things better.
