### ISSUE TITLE
Update frontend of calendar filters to account for states now filtering periods

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1675]

**Comment by noahmanger** [comment]
Now that we will soon have the ability to filter the reporting periods by state, we need to update the UI of the calendar. There's two questions here:

# 1. Where do the filters go?

## Option A: Move the "Reporting periods" filter inside the "Elections and reporting deadlines" accordion, where the state filter is:
![image](https://cloud.githubusercontent.com/assets/1696495/15594351/a545f942-2369-11e6-93da-b2cbb2b8602f.png)

## Option B: Move the state filter outside the accordion:
![image](https://cloud.githubusercontent.com/assets/1696495/15594369/c9837906-2369-11e6-95e4-b4486a632d45.png)

I think of the two, I prefer Option A, though we might need to rename the accordion, right @emileighoutlaw and @amykort?

# Question 2: Do we hide other events when the state filter is applied?
Even though the state filter applies to more events, it still doesn't apply to the other kinds of events on the calendar, like meetings. Should we hide those when a state is applied, considering they do not take place in that state? I believe we've seen confusion in usability testing to that effect.

Whenever the API work is done, this will be an easy change, so wanted to get folks' thoughts out now.

**Comment by jwchumley** [comment]
On question 1 I'm ambivalent. On question 2 I think I would prefer to continue to show all search options when a state is selected but inactivate them. Gray them out. I like not losing the reminder of what other options are available.

**Comment by noahmanger** [comment]
To be clear, I was talking about showing the actual events, not the filters. I think we'd keep the filters as-is, regardless of the filter applied.

**Comment by jenniferthibault** [comment]
**Question 1:**

My strong preference is *Option A*, to keep the state search inside the accordion containing the categories it applies to. Separating it out from an accordion makes it seem like it applies universally.

I hesitate to throw my hat in the ring for micro copy adjustments, but here are some starter ideas in hopes that it's helpful to @emileighoutlaw & @jeanninehunter :
- Change the default text of the state dropdown button to something like "For all states", so that it's clear that until a specific state is selected, you are defacto viewing data for all states.
- Make a small tweak to the Elections category & checkbox label, to show that it's not election deadlines, but election dates
- It seems like we need to include `Compliance periods` to account for Federal election activity periods, right? Here's one way we could, but I'd love if we could finesse the accordion label to be shorter if possible.

![screen shot 2016-05-31 at 2 25 57 pm](https://cloud.githubusercontent.com/assets/11636908/15686233/52bbd642-273d-11e6-983f-b66be96bb398.png)


**Question 2:**
If a user selects a state, I think we count that as applying a filter in the first accordion section. So once you check "All elections" you no longer see events populate under Meetings or Legal categories anyways, right? We may need to introduce an alert, or error message that appears if a user tries to select a Legal category while a state filter is applied. (The same way an error message appears in a form when you've entered an incorrect password or something)

**Comment by emileighoutlaw** [comment]
I agree that Option A is best. Here's a text draft to go with Jen's initial design:

> **Elections, deadlines and compliance** 
> [ for all states |  ]

> **Election dates**
> [ ] All federal elections
_Includes primary, general and special elections as well as caucuses and conventions_

> **Filing deadlines**
> [ ] Monthly
> [ ] Quarterly
> [ ] Pre- and post-election

> **Reporting and compliance periods**
> [ ] Independent expenditures
> [ ] Electioneering communications
> [ ] Federal election activity periods


What's here:
- I shortened the accordian header for faster, more satisfying reading (I think what's contained in it is still clear, but tell me if you disagree!)
- I expanded our explanation of "election dates", because I don't think it's intuitive that the filter would include all those types of things
- I made "reporting deadlines" "filing deadlines" because it's a deadline to _file a thing with the FEC_ (this is part of our move toward consistent language)

**Comment by noahmanger** [comment]
Ok, I got this started over here https://github.com/18F/fec-cms/pull/323

A couple semi-related snags on the state filter though:

Because the group of checkboxes is actually a `<fieldset>`, we need to have a `<legend>` for accessibility reasons, which is what the "States" label is. Plus, I think it's weird to not have it once we have checkboxes displayed: 
![image](https://cloud.githubusercontent.com/assets/1696495/15762782/9029affc-28d4-11e6-8eff-8f0e998de9c2.png)

Second, presumably we'd want to change the text on the button from "All states" to something else once one is selected. We don't have that functionality on the dropdown component, but can add it later (just not for this release). I think displaying the "All things are selected" message somehow is useful and would be elsewhere.

**Comment by jenniferthibault** [comment]
@noahmanger by `I think displaying the "All things are selected" message somehow is useful and would be elsewhere.` do you mean you need me to find a different place for this now? I'm not sure what you mean.

**Comment by noahmanger** [comment]
Oh I just meant I like the idea in general of having a more descriptive "empty" state for all dropdown filters, but this needs to be a separate task. I'll make an issue and we can discuss later.
