### ISSUE TITLE
Receipts data: Unique filter behaving weird

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1678]
@fec-issue-bot commented on [Fri May 20 2016](https://github.com/18F/FEC/issues/325)

## What were you trying to do and how can we improve it?
Here is a good example of the UNIQUE issue I mentioned before. Steve Aarnio has made four direct contributions to ACTBLUE and some earmarked contributions to Bernie through ACTBLUE. When you hit UNIQUE all the earmarked contributions go away.  

## Tell us about yourself
Jeff Chumley
Time traveler

## Details
* URL: https://beta.fec.gov/data/receipts/?committee_id=C00401224&amp;contributor_name=steve+aarnio&amp;is_individual=true
* User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by noahmanger** [comment]
The other example https://github.com/18F/FEC/issues/324

**Comment by LindsayYoung** [comment]
@jwchumley I am looking at the Steve example and it looks like the unique filter is working as expected, It is supposed to fill out memoed items. The so that people can add totals, Like, "How much has Steve given in a year?"  and we use it to filter out transactions that shouldn't be included in aggregates. We are using that link when we are linking from a total. 

To be over clear, this is not the individual filter, which filters out contributions that aren't individuals.  

Here are is the sql we are using to determine unique records to use in totals. Please tell me if you think there is something incorrect or I am missing something. 
https://github.com/18F/openFEC/blob/develop/data/functions/individual.sql

**Comment by jwchumley** [comment]
Help me out Lindsay,

It looks to me like none of the 8 AARNIO transactions are memo entires and 
from looking at the code snippet (not my strong suit) they should all be 
treated the same and returned by is_inferred_individual. What am I 
missing?

The actual difference between the transactions that are being UNIQUEd out 
and the ones that remain is the remaining ones (the $1 and $2 
transactions) are direct contributions to actblue where the ones being 
removed are earmarks to Bernie Sanders but they are identified not in the 
memo text but in the contribution description. In any event, Old Steve 
here actually gave $77 to actblue  and they presumably sent $70 of it to 
Bernie. If that $70 from actblue to Bernie were in the result set it 
should be uniqued out so IT wouldn't inflate the numbers.

I'm short on coffee so far this morning so I may be missing something 
obvious. Let me know.

**Comment by jwchumley** [comment]
I responded via email the other day but it doesn't appear here so this is what I said:

It looks to me like none of the 8 AARNIO transactions are memo entries and from looking at the code snippet (not my strong suit) they should all be treated the same and returned by is_inferred_individual. What am I missing?

The actual difference between the transactions that are being UNIQUEd out and the ones that remain is the remaining ones (the $1 and $2 transactions) are direct contributions to actblue where the ones being removed are earmarks to Bernie Sanders but they are identified not in the memo text but in the contribution description. In any event, Old Steve here actually gave $77 to actblue  and they presumably sent $70 of it to Bernie. If that $70 from actblue to Bernie were in the result set it should be uniqued out so IT wouldn't inflate the numbers.

I'm short on coffee so far this morning so I may be missing something obvious. Let me know.

**Comment by LindsayYoung** [comment]
Do you want to reopen this when Paul gets back?

We do look at contribution description and we we were given instructions to do the filtering on the opposite transactions, Just show the final transaction to Bernie so as to not double count. 

Looking at it again, it looks like we are not removing memo codes from the individuals that gave more than $200. And that seems wrong to me.

Here are some of the conversations that went into that filter:
https://docs.google.com/document/d/1dZpMv8K6hikRCHnXUSiEt0hQ4twRQNBeh3bZD786yJs/edit#heading=h.z5pmh1onklt3
https://github.com/18F/openFEC/issues/1141
https://github.com/18F/openFEC/issues/1330
https://github.com/18F/openFEC/pull/1340

**Comment by jwchumley** [comment]
I'm still looking at this and it is a little clearer now. The transactions from Steve Aarnio to ACTBLUE earmarked to Bernie 2016 are behaving correctly. You should only see the direct contributions to ACTBLUE with the UNIQUE button checked. The problem comes on the other end. The transactions that are forwarded to Bernie 2016 by actblue should show up when the unique box is checked but they aren't. 

It's a little confusing for me to check in postgres because I'm not sure which tables I should be looking in but here is an example. When I search for steve aarnio as contributor to the  bernie 2016 committee I should see more transactions than I do.  4040420161282315450 is a $50 contribution to bernie through actblue. It should definitely appear when the unique box is checked. The second one, 4040420161282315451, should not but when the unique box is not checked 4040420161282315450 is still not showing up.

select * from fec_vsum_sched_a
where sub_id in (
4040420161282315450,
4040420161282315451
)

We may need to revisit the earmark handling. Also we are now coding individual contributions based on the aggregate amount rather than the transaction amount. This is new (Paul probably told you) and it may impact the unique code.

If you want to wait for Paul that's fine but in the mean time please look at 4040420161282315450 and let me know why it isn't showing up at all. (it's OK if the answer is because I'm missing something  obvious. I can take it.)

**Comment by LindsayYoung** [comment]
Could the issue be that when you search for "Steve" or "Aarnio" there is no text in the ACTBLUE line (sk 270853645) that has the name at all? I am seeing the text as "NOTE: ABOVE CONTRIBUTION EARMARKED THROUGH THIS ORGANIZATION. "

Also, we have not switched to fec_vsum_sched_a yet, so still look at sched_a or ofec_sched_a.

**Comment by jwchumley** [comment]
No. I didn't expect to see 4040420161282315451 which doesn't have Steve's name on it  but I do expect to see 4040420161282315450 which IS from steve aarnio.

**Comment by LindsayYoung** [comment]
The memo text on 4040420161282315450 says " * EARMARKED CONTRIBUTION: SEE BELOW " anything under $200 with "earmark", "earmk" or "ermk" in the memo text it gets filtered out.

**Comment by jwchumley** [comment]
Filtered out by the unique box, correct? Shouldn't it be included if I 
don't check the box? Even so, it needs to be visible without checking the 
box. In this case, the actbule memo entry should be filtered out but the 
steve aarnio non memo entry should not be filtered out. I think we'll need 
to tweak the UNIQUE rules.

**Comment by LindsayYoung** [comment]
Agreed, let's revisit unique when Paul gets back.

**Comment by noahmanger** [comment]
Moving this to Sprint 15 since we can't address it this week.

**Comment by noahmanger** [comment]
**Remaining tasks:**
- [ ] Have a meeting to discuss it

**Comment by jwchumley** [comment]
Check the is_earmark()  function. It is returning all memo entries as earmarks because it is using "or" instead of "and" thus causing is_inferred_individual to always return false if the memo code is checked or if the text mentions earmark. I don't know how is_individual is called but this looks like a problem.

create or replace function is_inferred_individual(amount numeric, line_number text, memo_code text, memo_text text) returns bool as $$
begin
    return (
        amount < 200 and
        coalesce(line_number, '') in ('11AI', '12', '17', '17A', '18') and
        not is_earmark(memo_code, memo_text)
    );
end
$$ language plpgsql immutable;


create or replace function is_earmark(memo_code text, memo_text text) returns bool as $$
begin
  return (
      coalesce(memo_code, '') = 'X' or
      coalesce(memo_text, '') ~* 'earmark|earmk|ermk'
  );
end
$$ language plpgsql immutable;

**Comment by LindsayYoung** [comment]
meeting on this 10 am tomorrow
