### ISSUE TITLE
Visual design of advanced data page 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1681]
I just realized we didn't have a separate issue for this, despite talking about it. We need to design the basic layout and organization for the advanced data index page, which will be linked to from the data landing page. 

@jenniferthibault do you want me to take the first pass at a low-fidelity version of this page and then you style it?

**Comment by jenniferthibault** [comment]
Yep! In a bizarre alignment of foresight and available meeting-free time lining up perfectly, I started this last week.

I don't think the design of this is 100% right yet, but it's a start at nailing down some navigational directions. here's some thinking behind it:
- We can use the basic template for [essentials pages without a right-hand resources bar](https://beta.fec.gov/registration-and-reporting/get-e-filing-password/) established in the CMS
- We should use the same grouping and organization principles that appear in the mega menu
- We could cross-post the links to the interactive overviews, where they apply
- We could surface the election search as a next step navigation option (this bit feels stylistically not quite right in these mocks, but wanted to get it started anyways)

#### Questions:
- Are these navigation options the ones we want to offer people? (Where should we direct people from this page?)

![advanced data](https://cloud.githubusercontent.com/assets/11636908/15476372/9baf834c-20dc-11e6-86c8-754de14968fc.png)

cc @noahmanger @onezerojeremy @emileighoutlaw

**Comment by noahmanger** [comment]
Perfect timing. I agree with using the same grouping and organization principles from th emenu, and also including links to overviews. I don't know that we need the election overview here though, since we have that from the landing page, and it doesn't have an obvious analog here.

My eye has a little trouble with the horizontal row of options given they're all pretty different. What do you think about using the "options" template that we're using on the registration and reporting and legal landing pages? Even though it's not at the same position in the hierarchy, it feels like this page is really serving the same purpose: provide users a set of options to choose from, with links and calls-to-action within each option. 

![image](https://cloud.githubusercontent.com/assets/1696495/15485413/e27b2ba2-20f3-11e6-9475-9eaa07145bac.png)

It might also make sense to group the overview call-to-actions in the bottom, like here:
![image](https://cloud.githubusercontent.com/assets/1696495/15485449/37185bda-20f4-11e6-8f8e-929cec417c54.png)

**Comment by noahmanger** [comment]
One last though: what do you think about bringing in some visual element to better communicate what's behind these links? Something to show that these are table pages, dense with data and filters.

**Comment by jenniferthibault** [comment]
Mmmmk, I was thinking of starting with a very preliminary index-like page, but sounds like I should bump up the complexity and move towards a design with more offerings.

**Comment by jenniferthibault** [comment]
Smart 👀 's Noah. To be honest, I also need to own up to the fact that I was trying to work _too fast_ on the first pass. Not my best work, thank you for breaking that news to me in a really constructive way.

I was doubtful about that pattern here because it makes one reaaaally long page. Seeing it now, it doesn't feel too unmanageable, and I think is a good place to start. There's definitely opportunity (& placeholder text) for us to have an intro to each data section if we want to, but we can remove if it's not useful (cc @emileighoutlaw ! )

The call to actions at the bottom also gave me a good opportunity to finesse a slab color for the neutral variable. Previously I had used the `grey-dark`, but I think the 'grey-lightest` that we've used for filter panels & elsewhere works/looks better. 

I'd still like to find a better symbol than `+`  for "all data" categories, so that's still in the works.

![advanced-data-v2](https://cloud.githubusercontent.com/assets/11636908/15522310/97828914-21df-11e6-90fa-048dd0b51a7c.png)

**Comment by noahmanger** [comment]
Oooh nice. Yeah, that's working better. I think the long page is ok, and in fact, it's on the long pages that the sticky table of contents makes the most sense.

A couple minor thoughts, but largely I think this is looking good:
- What do you think about bringing the icons for each category back in the headings?
- What do you think about either putting the overview calls-to-action in cards and next to the introductory text, or grouping them all together at the bottom?
- Another reason to group them at the bottom would be that I'm not sure where the interactive overviews or profiles cards would actually go to, if not just the landing page.

**Comment by emileighoutlaw** [comment]
I'm a fan of strategic, introductory text — it could even help us underscore the advanced nature of this data. 

Let me see what I can come up with and share a doc in this issue.

**Comment by jenniferthibault** [comment]
Alrighty, I have a version that I feel pretty good about that combines some things I was hearing in your comments about icons & overview pathways.

- Instead of adding icons to the headers, (which we don't do elsewhere) I've integrated them with the cards for each section that has an overview, which is everything but Reports/Filings. This feels like an even spread of icons through the page
- I think we could make each overview card link to the first standalone page of their data graphics. 
 - In the case of Fundraising and Spending overviews, this would be an anchor link in the heading for each section of the data landing page.
- I've made a new icon for "all data" pages. I might want to lighten it up when we see it implemented, but I think it's ok to start with now.

On my end, this feels like a good place to start moving fwd with and learning from, but definitely still open to changes if you have 'em! 'Specially about how/where we link to other pages from this one.

![advanced-data-v2 copy 2](https://cloud.githubusercontent.com/assets/11636908/15579169/7731b704-2331-11e6-8dae-a45836db7ae3.png)

**Comment by noahmanger** [comment]
Yessss. Now we're talkin'! This looks great. I really dig the new all data icon. I'm good move this to implementation.

**Comment by emileighoutlaw** [comment]
I don't have any words for you yet! But I promise I'll get to them as soon as I can!

**Comment by jenniferthibault** [comment]
No rush! We can move forward with implementation without words, as long as the copy area seems about right to you. I.e., is that about the right amount of space, or do you anticipate needing a much differently formatted space?

**Comment by emileighoutlaw** [comment]
Not 100% sure until I draft it if that's exactly the right amount of space, but I definitely don't needing a lot more. It may be a little less. :)

**Comment by jenniferthibault** [comment]
Moved to implementation in https://github.com/18F/openFEC-web-app/issues/1241, so closing this issue.
