### ISSUE TITLE
Pre-release download fixes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1748]
We have a few high-priority items to address before we release downloads. Here is what we have to do for the API:
- [x] Verify that schedule A CSV has the `memo_Code` column, and if not, add it
- [x] Verify that schedule B CSV has the `memo_Code` column, and if not, add it
- [x] Add the timezone to the time the export was generated

And on the web app, we need to:
- [x] Change the link in the export tooltip to go to http://www.fec.gov/finance/disclosure/ftp_download.shtml

And last we need to:
- [x] Round the approximate record count down to the nearest 1000

I'm not sure if this last part happens on the API or front-end, though.

Assigning to @ccostino

**Comment by ccostino** [comment]
Adding the time zone to the manifest file is not as straightforward as it may seem, and yet it is.  Long story short, `datetime` objects in Python are generally naive objects (see the very beginning of https://docs.python.org/3/library/datetime.html for details).  What this means is no timezone information is given, and in this case that's what we're dealing with in terms of the timestamp you see in the manifest.  The timestamp we receive from the resource that we get all of that metadata from does not have this info.

Now, in looking at the difference in time between the generated value and the current time on my system, I can see that the timestamp is coming back as UTC.  Would it just be enough to include "UTC" at the end of that string, since the time zone information is not actually available?

**Comment by LindsayYoung** [comment]
I think the rounding should happen on the web app.

**Comment by ccostino** [comment]
All tasks should be done at this point!

**Comment by noahmanger** [comment]
Resolved! Thanks all.
