### ISSUE TITLE
National Party Nonfederal account committees not on /committees

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1755]
Don't show up on the /committee endpoint you can see that:
https://fec-stage-proxy.18f.gov/data/committees/?committee_type=Z
https://fec-stage-proxy.18f.gov/data/committees/?q=C60001799

Do show up in general text searches and have /committee/id pages:
https://fec-stage-proxy.18f.gov/data/?search_type=committees&search=C60001799
https://fec-stage-proxy.18f.gov/data/committee/C60001799/

**Comment by jontours** [comment]
The problem with this bug is the field "first_file_date".  By default the pages that the record is missing from, when it should be, is sorting based on that field.  And sense "hide_sort_null" is also a selected parameter this clears all results.  In the case of this endpoint: https://fec-stage-proxy.18f.gov/data/committees/?committee_type=Z,  no committees show up because all the columns are null for that committee type.  And ditto for https://fec-stage-proxy.18f.gov/data/committees/?q=C60001799, if you select to sort by name for example, the entry shows up again.  

So I'd say the fix for this bug would be to remove "sort_hide_null=true" from the parameters for this view.  I'm not sure as to why Z type committees have no first_file_date entries, is because of the committee type @LindsayYoung?

**Comment by jontours** [comment]
And now that I think about some more, this doesn't stop a user from selecting a column that is all null on the endpoint.  Ideally maybe the better fix is to turn off being able to click this column if all its row entries for that column are null, although I'm not sure how to approach that.

**Comment by jontours** [comment]
Or maybe this is an option: http://stackoverflow.com/questions/20958679/why-do-null-values-come-first-when-ordering-desc-in-a-postgresql-query

**Comment by LindsayYoung** [comment]
I am not too worried about people sorting on things that are all null. I feel like it is an edge case we can live with.

**Comment by noahmanger** [comment]
Very weird. Why is there no `first_file_date` for these committees? That seems like a bug?

**Comment by LindsayYoung** [comment]
To be clear on my previous comment, we should fix the first file date for all committees. I am not worried about the sorting after we do that.

**Comment by jontours** [comment]
The only way I could it still being a problem, at least in general, is if a loser is looking at a single entry and sorts on something that is null for that record, and then the record disappears.  I would hope the user would have the curiosity to click the other columns.

**Comment by jontours** [comment]
After looking into the problem a bit more, at least on the dev database, the view 'vw_filing_history' has no 'Z' type committees.  So when the materialized view that supports the committee list is built, all the columns that are derived from for that committee are null.  Does the FEC build the table 'vw_filing_history'  ?

**Comment by LindsayYoung** [comment]
Talked to @PaulClark2 about this and these are the soft-money accounts for existing committees. (They are soft money committees that have not existed in decades) 

I'm ice boxing this because a good fix would be mapping these committee ids to their "parent" committee and making them accessible from there.

**Comment by noahmanger** [comment]
Moving to the icebox.
