### ISSUE TITLE
switch off multi-buildpack

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1770]
Make sure docs still work.

**Comment by adborden** [comment]
I was just poking around the issue with the docs. The problem here is the `.cfignore`. Since we're ignoring `dist/`, the `swagger-ui` built site is not getting uploaded to cloud foundry https://github.com/18F/openFEC/blob/d3bd998c008079a595d31cfd6015641812567d06/.cfignore#L17

There's also an issue with the `lib/` too, since that's where `swagger-ui` puts it's third-party js.

`gitignore` semantics match path elements, so the `dist/` does not have to be the top-level  to be ignored (`/dist/` would only ignore the top-level dir).

So, we can add this to the bottom of `.cfignore` and the docs should work.
```
# Exclude swagger-ui site (include it in the cf push)
!/node_modules/swagger-ui/dist/
```

**However**, rather than upload any `node_modules` at all, it would be nice if we just copied the `swagger-ui/dist` dir into the main project dir to avoid uploading a bunch of dev dependencies to CF. That's similar to how the other projects work with regards to copying `fec-style` assets out of the node module.

**Comment by jmcarp** [comment]
Sounds good @adborden. Just make sure to update https://github.com/18F/openFEC/blob/develop/webservices/rest.py#L278 if you change the `swagger-ui` path.

**Comment by LindsayYoung** [comment]
For next sprint, assigning now so we don't forget
