### ISSUE TITLE
Identify process for moving from synthesis to wiki

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1785]
@onezerojeremy and @jeanninehunter work together to improve the process of moving usability findings from synthesis to the wiki.

**Completion criteria:**
- [x] We have a codified process for quickly moving from synthesis to new issues
- [x] We have a codified process for moving from synthesis to the research repo

cc @jenniferthibault @ethanheppner

**Comment by nickykrause** [comment]
Quick update here. We haven't actually conducted a synthesis session this sprint, so I haven't had a chance to participate in this process, in order to document / evolve it. 

We didn't synthesize this week because we had only one user. We'll be testing with the same script next week, thereby adding more data for that script, and then we can synthesize.

**Comment by nickykrause** [comment]
Adding a link to the feature sets files where usability test results are currently synthesized:
[feature sets](https://github.com/18F/FEC/tree/master/feature_sets
)

**Comment by nickykrause** [comment]
Another brief update:

I finally participated in synthesis (yay!), and had some thoughts about how the process could be improved. It turns out that @ethanheppner already had some thoughts on that, too, so we met with @onezerojeremy to connect on the existing process and to review a cool new synthesis prototype that Ethan was working on, which now allows us to see all the answers to a single question _side-by-side_ during synthesis, rather than scrolling all over the place! 🎉   I think everyone will be pleased.

As a part of that meeting, we ended up discussing the testing process as a whole (other than recruiting, which Ethan clearly has a handle on!), and we identified the need to document/discuss/improve various aspects of it. 

Here are a few things that are guiding our thinking on how to evolve the testing -> synth -> documentation process:
- We need to make sure this process is simple for partners to take over, when we hand this off
- We need to recognize that there are multiple internal and external stakeholders and to gather their feedback as we go (Noah, Jen, Pat, etc.)
- We need to understand how this process with sync up with other processes, such as sprint planning and issue management in GitHub

Here are the new next steps we have on this issue:
- Nicky will document the process as-is, adding some notes about places where we have questions or concerns, and Ethan will add his thoughts to that as well.
- Ethan and Nicky will iterate on the document briefly just to make it presentable, and then share it with the team to discuss / gather input

**Comment by nickykrause** [comment]
Updating with a mural: https://app.mural.ly/t/gsa6/m/gsa6/1473432120209

**Comment by nickykrause** [comment]
Met with Noah, Adrian, and Ethan yesterday. We decided to make a testing repo. The process is documented here: https://app.mural.ly/t/gsa6/m/gsa6/1473432120209.

Here are some of the reasons for this solution:
- We should keep track of our testing ideas. Testing is a key feature of our design philosophy and decision-making: We say that we will "test things" to validate our assumptions. A GitHub repo dedicated to testing will offer a unified place to put testing ideas, which can flow elegantly into actual work.
- We need to be able to account for the work of doing testing, from start to finish, so it is visible as a workstream that takes time, and which must be balanced against other work. All of our other tasks are documented in GitHub, so including testing there seems to make sense.
- The testing process integrates with our design and development work; it is a component of a bigger picture. With the GitHub repo, we can integrate testing into our planning process and our issue-tracking practices. 
- We need solid documentation of the testing process, from start to finish. (We need to a place to capture passing ideas + a place to house testing scripts + a place to synthesis results + a place to track issues). GitHub seems like it can do that.
- We want to work in the open. GitHub is public and will help expose our testing process.

Some questions I still have:
- Can we move the test scripts to the testing repo?
- Can/should we move the Design Research Wiki to the testing repo, or does that not make sense?
- Will tagging issues in the GitHub testing repo as being related to specific features help us to get a "snapshot" of the history of a feature?
- Will we realistically have time to continue updating the Design Research Wiki?
    - My first thought is: Maybe. It seems straightforward enough to copy/paste observations and action statements into the wiki, as well as into GitHub, as the process documentation suggests. But, then again, I worry about redundant documentation. If GitHub will help us to see the history of a feature over time (see above), then maybe we won't need to keep updating the wiki with that same info (observations/solutions). But then...maybe there is significant value in the way the wiki presents information, as compared to searching by a feature in GitHub.

**Comment by nickykrause** [comment]
Adding a link to the repo: https://github.com/18F/fec-testing

Last thought: The process will likely need to be iterated on, and it will evolve, but I think this issue can be considered complete for now.
