### ISSUE TITLE
API changes to support /reports/ pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1804]
In order to support the new reports data table pages, we need some API tweaks. I'm getting started on front-end work in order to scope out backend needs, so I'm starting this issue to keep track of everything and then we can either use this or break things out into separate issues.

**Need:**
We need a few immediate things in order for this to replace the filings table.
- [x] Include committee name in the response
- [x] Allow filtering by multiple `committee_id`s
- [x] Allow sorting by 'receipt_date', `total_receipts_period`, `total_disbursements_period` and `independent_expenditures_period`

We also have additional things we want, but don't need immediately
- [x] Allow filtering by:
  - [x] `total_receipts_period`
  - [x] `total_disbursements_period`
  - [x] `cash_on_hand_end_period`
  - [x] `debts_owed_by_committee`
  - [x] `independent_expenditures_period` (for pac-party)
  - [x] party coordinated expenditures (for pac-party)
  - [x] `independent_contributions_period` (for ie-only)
  - [x] Committee type
  - [x] For authorized committee, by related candidate

**Questions:**

1. Is there a reason to separate `presidential` reports from `house-senate` reports? I know they're filed on different forms (Form 3P vs Form 3), but they're both authorized committees and basically show the same info. We had originally included in our plan to just have an Authorized Committee Reports page, an Unauthorized Committee Reports page, and an IE Only Committee page.
2. Do we not care about `receipt_date` for this one?
3. Are we only showing `is_amended=false` reports? i.e. the latest version, rather than previously amended? 

I'll add more here as I notice them.

**Comment by noahmanger** [comment]
FWIW, here's the front-end PR work that I started today: https://github.com/18F/openFEC-web-app/pull/1338

**Comment by noahmanger** [comment]
Just talked with @LindsayYoung . Here's answers to those questions:
1. We're going to keep the presidential and house-senate pages separate.
2. We want `receipt_date`, and it's already in the API, so all good.
3. We want to expose the `is_amended` flag as a filter, with it turned on be default

**Comment by LindsayYoung** [comment]
Thanks Noah!

I would love to get some more user feedback on these kinds of things. We would want to give people heads up with breaking changes, but the more consistent the better. I have kept things reflecting the source data but there are also good data standards orgs we could learn from like [Open Civic Data](http://opencivicdata.readthedocs.io/en/latest/data/introduction.html), that is what some of Sunlight, Google and others use.

As for your specifics, we could call the forms documents but we can't call all documents forms. Our document discription is a bit [more complicated](https://github.com/18F/openFEC/blob/881cf4142a2f2af02ea714a8639ffd0451f6b594/webservices/utils.py#L176). I would love additional opinions on whether this a useful distinction or if it is splitting hairs.
 
Amendment indicator can mean that something is an amendment rather than something has been amended- I want to use `is_amended` for everything that could be presented that way, so people don't have to figure that out themselves, it is really complicated. I am hoping we can make it straight forward with the new filing table. 

Please keep these issues coming!

**Comment by noahmanger** [comment]
Thanks! Fortunately, none the `document_description` and `amendment` stuff aren't blockers. More nice-to-haves to contribute to cleaner code, but only if they make sense for other use cases. 

The amendment stuff is definitely tricky. I can't decide which way seems more intuitive. There's something about `is_amended=false` signifying the report is the latest, definitive version that's confusing (kind of a double negative). But we could also just address this with the language on the frontend. For instance, I'm playing with something like this for the filters:

![image](https://cloud.githubusercontent.com/assets/1696495/16694131/6af2b85c-44ed-11e6-8563-46f05b153a7d.png)

**Comment by LindsayYoung** [comment]
Good options for language might be:
 [ ] final reports
 [ ] amended reports 
 [ ] all reports

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1892
