### ISSUE TITLE
Add sorting to name fields on schedule A and B

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1806]
In order to allow users to sort data table results by useful fields, add sorting to contributor name and payee name.
- [ ] Add sorting to `contributor_name` on schedule A tables
- [ ] Add sorting to `payee_name` on schedule B tables
- [ ] Run benchmarks to verify they're not too slow

Other columns that could be sortable:
- [ ] `employer` on schedule A

**Comment by ccostino** [comment]
@LindsayYoung, do these fields correspond to the following columns?

Schedule A:

* `contbr_nm` (note that there are also `contbr_f_nm`, `contbr_m_nm`, and `contbr_l_nm` columns)
* `contbr_employer`

Schedule B:

* A combination of the `payee_f_nm`, `payee_m_nm`, and `payee_l_nm` - is there a single column instead, or should there be?

**Comment by LindsayYoung** [comment]
If I remember correctly, payee first and last name are not always present

**Comment by ccostino** [comment]
Ah, so we'd have to account for hiding `nulls` in this case as well then.

**Comment by LindsayYoung** [comment]
I think it is best to just use the name because it is always present.

If committees without fundraising disappear when you sort or receipts or something you care about, that is not a big deal. However, if people randomly disappear on sort, that is a big problem, because it is too easy to miss donors that you are looking for. Additionally, the data is not consistent about what goes in the first name verses last name for the same person. That is why we don't use first_name and last_name for the candidates either.

**Comment by ccostino** [comment]
I see, thanks @LindsayYoung!  The other issue then is that there's no `payee_nm` field to use instead for Schedule B.  Is that something we can/should derive?

**Comment by LindsayYoung** [comment]
That's a great point, Carlo! I am leaning toward deriving it on schedule B for consistency. It would be nice to sort on last name, but that would be the only place where sorting would work like that.

**Comment by jontours** [comment]
There should be a way to concatenate other fields to generate one field with SqlAlchemy right?  And make that field not directly mapped to the database.

**Comment by LindsayYoung** [comment]
yea I think we can add a property to it with SqlAlchemy

**Comment by ccostino** [comment]
Definitely a good thing to look at, @jontours!  I think there are some places in the code where we already do that, I thought I've come across it before.  I'll take a look and see!
