### ISSUE TITLE
purpose of disbursement aggregates

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#1833]
On both [production ](https://beta.fec.gov/data/committee/C00575795/?tab=disbursements)and [dev ](https://fec-dev-proxy.18f.gov/data/committee/C00575795/?tab=disbursements) this committee has $34,311.08 for travel. However, looking at our production database, I think amount for travel for this committee should be around $4.6 million.

We should revisit purpose of disbursement and the purpose aggregate table.

@ccostino @LindsayYoung @jwchumley

**Comment by PaulClark2** [comment]
I looked at a few big committees. Here are there travel related descriptions. I'm going to ping @llienfec She might have some insight into how to refine are purpose of disbursement logic.

AIR
AIRPLANE TICKETS
BUS RENTAL
CAR RENTAL
FLIGHT
FUEL COSTS
GROUND TRANSPORTATION
LODGING
PARKING
PLANE TICKETS
RAIL
RV RENTAL
TAXI
TRANSPORTATION
TRANSPORTATION SERVICES
TRAVEL AND SUBSISTENCE
TRAVEL EXPENSE REIMBURSEMENT
TRAVEL: BAGGAGE
TRAVEL: FEE
TRAVEL: FOOD
TRAVEL: FUEL
TRAVEL: INSURANCE
TRAVEL: MEALS
TRAVEL: MEETING EXPENSE
TRAVEL: MILEAGE
TRAIN FARE
TRAVEL: TRAIN
TRAIN TICKET

**Comment by llienfec** [comment]
@PaulClark2 those look reasonable to me.  On Monday, can we talk a little more about this feature?  I want to understand a little bit more about what this is and what we are trying to achieve before weighing in more.  Thanks!

**Comment by llienfec** [comment]
Paul/Jeff - thanks for having me take a look.  Here are my thoughts for this particular page:
https://beta.fec.gov/data/committee/C00575795/?cycle=2016&tab=disbursements

Unfortunately, RAD doesn't have a list of what we would consider "travel" vs other categories of purposes on this webpage since it doesn't affect reviewing reports.  In addition, you can see how a purpose like "taxi" may be travel for some committees and incidental getting around for others -- all depending on the committee's context.  These categories will be used by opponents and press to tell a certain story about the committee ("look at how much they're spending on travel!"), so it's really important to get this right.  We can help refine which purposes go into which categories, but I'm going to lay out my other concerns about this particular graph (set of filters?) below.  I would suggest not including this page when we flip the site.  I think it will take a lot more discussion to make 100% sure that this is a direction that we would want to go in, a bunch of research work regarding possible purposes, and a procedure for how we make updates and if/when we make corrections.  I don't think we have time to do all of this pre-flip, but you'll have more information about priorities and IT workload than I have.

1.  FEC is careful to use what the committee themselves reports.  This is the only time I can think of that we are characterizing a committee's activity and I think this will be a problem.  We won't be able to get it right in every case.  More than that, every other filter on the committee page uses only the committee's filing information.  Employers, occupations, contributor name, vendor names are all on the report.  I think this makes it seem like the disbursement categories are on the committee's reports - when they aren't.  I'd suggest we just rank the committee's reported purposes instead - that way it'll always be correct.
2.  If we keep this page with its current disbursement categories, we need a really big and carefully worded disclaimer that these categories are approximate AND not identified by the reporting committee.
3.  The page needs a total line for all disbursements.  Just would be helpful.  Doesn't show up on page.
4.  When I click on the total for a particular bar on the graph, it takes me to ALL disbursement data, and not just the data making up that particular bar's category (which is what I think users would expect).  Even more importantly, once I got to that page, there's no way for me to use the current filters to see what the FEC is categorizing as "travel," "fundraising," etc.  
5.  I can't tell how memo entries are being handled.  For example, a committee has a credit card disbursement with memo entries (descriptive entries) that are mixed-use (some travel expenses, some fundraising expenses, some media expenses).  This is a very common scenario, and unclear to me how this set of transactions would be represented in this visualization.  

I'm happy to talk about these concerns and work with you if you think it's really important to have this graph on our site.  Please let me know how I can help or where you'd like to go from here.

**Comment by noahmanger** [comment]
Thanks @llienfec . I hear the concerns. @PaulClark2 do you agree we should disable this for now?

**Comment by PaulClark2** [comment]
@noahmanger, yes. I think we should disable this feature for now. Hopefully, we can turn it back on soon after the flip.

**Comment by noahmanger** [comment]
Ok, I just removed it in this PR https://github.com/18F/openFEC-web-app/pull/1928

But I also added in the full itemized tables too.

Moving this issue back to the icebox to resolve the actual issue later.
