### ISSUE TITLE
rename indexes

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1840]
During partitioning all our indexes are being dropped and this is causing queries to be crazy slow and eat up storage space.

We want to add a function like rename tables to rename indexes, hopefully that will keep them from being dropped.

**Comment by LindsayYoung** [comment]
@ccostino found this for reference:
https://www.postgresql.org/docs/9.4/static/sql-alterindex.html

**Comment by ccostino** [comment]
One other thing we noticed is that the `gin` indexes were not dropped and renamed properly, so we'll need to investigate why that is as well.

**Comment by ccostino** [comment]
Initially we were thinking of doing a broad rename of all of the indexes we created in the database once everything was done and removing the `_tmp` portion of them, but this appears to be more risky than initially thought since the indexes aren't named as consistently as the materialized views are.

We're going to scope this to be around the indexes that are created as a part of the partitioning steps for now and revisit other indexes later.
