### ISSUE TITLE
Test new data landing chart

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1853]

**Comment by onezerojeremy** [comment]
Excellent write-up from Pat below, bound for the wiki page:

:large_orange_diamond: Problem: Users first interpreted the graph as the total raised each month instead of a cumulative total up to the month selected. Users consistently articulated needing a better indication of what they were looking at before having to interact with the graph. One user expressed that the table data did not immediately register as specifically correlating to the month the vertical line is on, until the user interacted with the arrows and moved it to a new month. Once that happened, the user saw the association.
:wrench: Adding some shading to the left side of the vertical dotted line might help users understand that the total is a cumulative total up to the month selected. Also adding more interactivity to be able to change the month or quarter by dragging the vertical line may help.

:large_orange_diamond: Problem: The majority of the participants did not understand or were unsure of what the dotted line represented. 
:wrench: Many users wanted to be able to drag the dotted line, thus adding a short explanation on hover/click to the vertical dotted line may help.

:white_circle: One user struggled to understand how the interactivity of the graph "next month" or "previous month" buttons or dotted line worked. Others were successful with both buttons. Keep an eye on expected interactivity on hover and/or click as the graph interaction may be improved on the live site. 

:white_circle: The users successfully understood what the dots meant on the line graph, however, it did take a few minutes to process and understand. All users communicated that they understood different filers had different filing schedules.  

:large_orange_diamond: Problem: Largely, users did not understand why the top two lines extended the length of the graph while the bottom two lines stopped half way. Another observation was that none of the users seemed to notice that the bottom line was shorter until it was brought to their attention. 
:wrench: When users move the vertical dotted line, there should be an indication on the numbers on the right hand side that Party Committees and others have no data because they have not filed yet for the selected time period. Also, extending the incomplete line with a dotted line for the time period with unavailable data may be useful.
