### ISSUE TITLE
Add discription and pdf_url to e-filings

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1887]
From https://github.com/18F/openFEC/pull/1884#issuecomment-239708276

 - [x] document_description: the computed name of the document, e.g. July Quarterly 2016
 - [x]  pdf_url. I tried just manually building it for some filings and it worked, but would be good for the API to provide this

**Comment by noahmanger** [comment]
Just to follow up on my note re: amendment indicator. I agree that it's confusing and not straightforward, but it seems like we should have _something_ there. At least on the frontend, since there's a column for it in the table, it'd be nice to have parity. But alternatively, if you don't want to implement on the API, we could always derive the field on the front end from the `form_type`.

**Comment by LindsayYoung** [comment]
We can show if something has been amended or if someone is an amendment- which is much better.

**Comment by noahmanger** [comment]
Yeah, I think that's great.

**Comment by LindsayYoung** [comment]
@noahmanger want to give you a ux heads up that the pdf files take a while to build. We might want to  warn people that pdfs might not be ready right away.

**Comment by noahmanger** [comment]
Added by #1889
