### ISSUE TITLE
Issues with paging through nulls

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1960]
Since the data can have missing values, there needs to be a way to page through nulls.

discovered in #1927 

---

**Completion criteria:**
- [x] Schedule A can paginate through nulls
- [x] Schedule B can paginate through nulls
- [x] Schedule E can paginate through nulls

**Comment by ccostino** [comment]
Upon some further investigation, here are some things to bear in mind about this:

* Whenever we supply a default column to sort by, whether we sort by ascending or descending has a bit of an impact due to what [Postgres does under the hood](https://www.postgresql.org/docs/9.5/static/queries-order.html).  TL;DR is that when we order something by descending order, Postgres will also set `NULLS FIRST` as a part of the query under the hood.  In the case of Schedule E, where `expenditure_date` is our default column to sort on in descending order, there are `null` values present in the table.
* When making requests directly to the API itself, the `sort_null_hide` flag is not automatically present in the request so records with `null` values in the sort column(s) set will appear unless it is explicitly provided.  `null` values do not on the web app because we set that flag to `True` within the app itself (due to this same issue causing problems with requests and empty results appearing).
* The paging mechanism already takes care of providing a way to page based on whatever field we define as the `index` (e.g., `sub_id` for the itemized records) simply by supplying a `last_index` parameter.  If you want the results to continue to be sorted, however, you must also supply the `last_x` (where `x` is the column you're sorting on).  This is a problem though if the value ends up being `null` for a couple of reasons:
  * Marshmallow will treat it as an invalid value and throw an error, e.g., `expenditure_date`, because it is not a valid value for the field type (`date` in this case).
  * Even if `null` is a valid value, that wouldn't give any indication as to which record is being referred to; we need to sort on another column, which we currently don't do.

@LindsayYoung, @jontours, and I all spoke the other day of possible solutions and one easy solution we came up with was possibly just setting another column to sort by that we know won't ever be `null`, such as the `sub_id` for the itemized models.  Some additional discussion revolved around supporting [keyset pagination](http://use-the-index-luke.com/no-offset), but this is already supported by our app via [marshmallow-pagination](https://github.com/jmcarp/marshmallow-pagination/blob/master/marshmallow_pagination/paginators.py#L59).

At the moment I've added support to sort by `sub_id` for all itemized models in addition to whatever column we're sorting by which helps in providing some semblance of order even when the records returned contain `null` values in the sort column being specified, but it doesn't solve the issue of being able to handle a `last_x` parameter for paging that would be `null`.  At the moment I don't know of an effective way to handle this cleanly:

* Do we simply ignore that parameter if it's null (or at least until it's not)?
* Should we adjust the way marshmallow or marshmallow-pagination handle this behavior?
* Some other alternative?

That's where I'm at currently with this.  I'd definitely welcome any other ideas or recommendations if anyone has them while I continue working toward a full solution.

A big thank you to @LindsayYoung for working through more of this with me today and explaining how some of these other pieces tie together!

**Comment by ccostino** [comment]
One other question that comes to my mind about this that I'm mulling over:  Do we expose this secondary sort parameter (and if so, as a truly separate parameter or convert the existing `sort` parameter to support a list of columns)?  Would it make sense to?

**Comment by LindsayYoung** [comment]
:+1: Nice work on this plan!

Also, quick clarification schedule a, b and e use the itemized paging, because they are big. Schedules c, d and f use default "page=" pagination

**Comment by jontours** [comment]
Yup I second that.  Taking that second sorting parameter is probably the safest option.

**Comment by ccostino** [comment]
Thanks!

_looks over Schedule C, D, and F..._  Oh, so they do. :-)

@LindsayYoung:  Under the hood I have this currently set to do the secondary sort for all itemized models, should I keep that change to just Schedule A, B, and E?

**Comment by LindsayYoung** [comment]
Yea, for now, keep it to A B and E since they need it and keep the rest simple.

In the future, we can think about moving everything to the same pagination scheme, but we would not do that before the election at this point, or without doing a lot of user outreach

**Comment by jontours** [comment]
I think as far as the code goes C, D, and F aren't itemized; as they don't extend the itemized class; so I think you'll be fine?

**Comment by ccostino** [comment]
Ah, good call on both counts.  Thanks @LindsayYoung and @jontours!

**Comment by ccostino** [comment]
At this point I believe I have this mostly working, I just need to figure out a way to allow for `null` to be passed in but ignored for any of the `last_x` columns.

**Comment by ccostino** [comment]
Work on this is now completed and includes the following:

* Fixed pagination for sorted columns that may contain `null` values for itemized resources
* A new flag we can pass in called `sort_reverse_nulls`
* Additional tests

Please see the PR for more details!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1989
