### ISSUE TITLE
Move s3 buckets to the new cloud.gov

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2031]
The following buckets need to be moved to the new cloud.gov infrastructure:
- [ ] Data downloads
- [ ] Legal resources
- [x] Content documents

Also:
- [x] Give Pat credentials to the new buckets

@LindsayYoung Does this negate the task of making the other buckets public?

**Comment by LindsayYoung** [comment]
Only the content bucket isn't public.

At this point, we could just make a new, public bucket. I am not sure how much we can mix and match the clouds. In theory, it should be fine. 

We might want to give them human-readable .gov names when we move them since we will be messing with them anyway so that might be an efficient time to do that.

**Comment by LindsayYoung** [comment]
Did this for content

@ccostino I think this was a dependency for your renaming work, so that is ready for you

**Comment by ccostino** [comment]
Oh awesome, thanks @LindsayYoung!
