### ISSUE TITLE
New itemized views ".._vsum_xyz" need indexes on root tables

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#2046]
In the process of debugging another issue noticed that the view for schedule B takes a lonnnng time to run a query on if any filters are added to the query.  Perhaps adding indexes to the root tables can help there, e.g. add index on columns for `disclosure.nml_sched_b`.

**Comment by LindsayYoung** [comment]
Yes, we will want to ad the indexes directly for things like efiling that we don't want delays when we create and refresh our views.  Like the filings endpoint, and we will want to have less filters and sorts so that the inserts are not getting slowed down too much by reindexing. The reason we have our own views for things like schedule a is that, when we tried adding indexes directly on those tables it made FEC's refresh tasks too slow. Also we want to make sure we give the DBAs a head's up before adding the indexes.

**Comment by jontours** [comment]
@PaulClark2 suggested in the future it may be good to add some indexes on this resource, but it's a minor issue.  As a DB user though it's good to keep in mind that any direct queries on these tables will run a _long_ time.  It's a minor issue though as we will be sensing any updates to these tables via  a trigger; which will run fast regardless of the target table.
