### ISSUE TITLE
Create strategy for migrating to gov cloud

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2047]
In order to prepare us for all of the work of migrating to the new gov cloud this quarter, we need to hammer out details about the strategy we'll take. 

Some questions to address:
- Are we moving over little things first? Or are we moving over the most difficult things first?
- Who from the cloud.gov team is able to help and how?
- Who from the FEC needs to be involved or shadow?

I'm not sure what else this needs to cover, but I want to end Sprint 1 with a clear action plan for the next 5 sprints.

**Comment by LindsayYoung** [comment]
I requested an org for us on govcloud. I can add people to it when we get the account going. Once that happens, we can start moving the apps. 

We are going to try and move the apps (we can work concurrently on these):
 1. openFEC-web-app - this will probably be the easiest
 2. fec-cms - has some data but shouldn't be too difficult
 3. fec-eregs - has some data but shouldn't be too difficult
 4. openFEC - this is the trickiest because it connects to lots of things
(we don't need the proxy app on govcloud)

Here is the general documentation for a govcloud migration:
  - https://cloud.gov/docs/apps/govcloud/#migration
We can also get assistance from cloud.gov staff

Our apps will need to use cloud,gov configured routes instead of the proxy app:
  - https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html

It doesn't look like we are moving the RDS boxes soon. We have gone over our needs with cloud.gov and they will continue to work on extending the platform so we can migrate the data into the new govcloud.

**Comment by LindsayYoung** [comment]
I am closing this because we had the meeting, please edit or comment if you have additional thoughts
