### ISSUE TITLE
Document API views and models

### ISSUE THREAD

**Issue by adrianwebb** [18F/openFEC#2112]
Create documentation within the repository for the API views and models.

**Comment by adrianwebb** [comment]
@LindsayYoung: Seems like this could be handled by any of our engineers?

**Comment by LindsayYoung** [comment]
I think we will want a dev with legal experience and a dev with data experience because we have been acting pretty independently in the code. 

I would really like to see some high-level docs of where to find different aspects of the code and put the specifics in docstrings within the code.
 
A good place to start with the doc strings would be, the management commands in the API. That way, when you enter `./manage.py` without an argument you get a list of the management commands and discription, which should include when to run them. We have some descriptions going but it would we nice to have that completed. 

<img width="704" alt="screen shot 2016-12-20 at 8 38 50 am" src="https://cloud.githubusercontent.com/assets/4406333/21359123/0645ac6e-c690-11e6-895f-b1d9e248488f.png">

Adding more doc strings also opens up the possibility of using tools like Sphinx later.

**Comment by adrianwebb** [comment]
Sounds good to me.

**Comment by adrianwebb** [comment]
Create new issues with more granularity

**Comment by vrajmohan** [comment]
I think I have completed adding docstrings for all the commands related to legal documents. There are some others (e.g. `build_district_counts`) that I don't know well at all. @LindsayYoung, can you please decide what to do about them? As well, are there any other outstanding tasks from this ticket?

**Comment by LindsayYoung** [comment]
Thanks for taking on all the legal doc strings, I can take the remainder!
