### ISSUE TITLE
Add date sort to charts

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2122]
Example url that need a date sort:

https://api.open.fec.gov/v1/totals/by_entity/?cycle=2016&page=1&per_page=20&api_key=DEMO_KEY

**Comment by ccostino** [comment]
@LindsayYoung, do you know of any others?  Is it all aggregates, just anything without a date sort already that has date columns, something else?

**Comment by ccostino** [comment]
Also, should this sort in ascending or descending order by default?  I'm assuming descending, but wanted to check.

**Comment by ccostino** [comment]
This is going to be a more difficult than anticipated.  The `date` column on this model/resource is not directly mapped to a database column, it is instead a property on the class itself that is calculated via the `month` and `year` columns.

Our sorting code currently expects a column name that maps directly to a column on the database.  Furthermore, because this is actually two columns under the hood, that runs into the other issue/limitation we have around being able to sort against only one column at a time.

I'm diving back into the sorting code and looking in other parts of the API to see if we have accomplished this anywhere else, but so far I'm not coming across anything.

**Comment by LindsayYoung** [comment]
I think it will be easiest if we add date to the underlying sql table here, https://github.com/18F/openFEC/blob/develop/data/sql_updates/large_aggregates.sql#L203

**Comment by ccostino** [comment]
I didn't consider that at all, thank you! :-)

**Comment by ccostino** [comment]
One thing I've noticed while working on this is that the dates are already sorted in ascending order.  Are we exposing this to sort in reverse chronological order?

Also, would it be enough to simply expose a date column in the `ofec_entity_chart_mv` view that is ultimately created that is derived from the month and the year (along with just defaulting to the first of the month to keep things simple), or should we expose the underlying date column that the month and year are derived from (`cvg_end_dt`, which I'm assuming means `coverage_end_date`)?
