### ISSUE TITLE
Figure out how to get plain language summaries for AOs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2163]

**Comment by AmyKort** [comment]
I got together with Cheryl and @amypike and we have a proposal. What if for the canonical pages we keep the short summary that currently appears, and then also create a really great buttony link type thing that would allow users to click open the Record summary of the AO if they wanted to (rather than replacing the short summary with the Record summary). Under this plan, we could start with just the AO summaries that are in Wagtail now. Over time, Information Division could manually add all of the past AO summaries to Wagtail, filling out both that subject filter in the Record display and populating the AO pages.

This would also solve the problem Cheryl brought up: the AO is released before the summary. For the first week or so, only the short summary would appear and then the Record summary could become available once it is published.

Is this a:

1) Bad idea?
2) Not possible?

**Comment by AmyKort** [comment]
@jenniferthibault (I meant to ping you)

**Comment by jenniferthibault** [comment]
@AmyKort thanks for brainstorming on this!

But I can't answer you question just yet 🙊  because the design/UX solution is going to depend on the technical possibilities of getting FEC Record articles into the AO page template. This is exactly where we left off in our grooming session on Tuesday. From the notes:

> **TO DO before sprint planning:**  What is the work of getting the FEC record articles into the AO template?

Here I want to tag in some backend help: @anthonygarvan or @vrajmohan if the problem space looks something like the following, can you help groom the system questions?:

**For AOs going forward**
1. As soon as an AO becomes public (which is when it enters pending status), there is a one sentence summary in the AO metadata. 
2. Later, a Record article is published that contains a more detailed summary, background, and analysis.
- System question: How does this Record text make its way onto the AO page? 
- Design question dependent on ^: What happens in the gap of time between when there is an AO published and when there's a Record summary to accompany it?

**For AOs from 2009-now**
1. A one sentence summary exists in the AO metadata. 
2. Later, a Record article was published that contains a more detailed summary, background, and analysis, but the article is in PDF format AND contains more content than just one AO
- example: https://beta.fec.gov/updates/ao-2010-28-state-party-refund-to-federal-campaign-not-a-contribution/
- System question: How does only the Record text about the AO make its way onto the AO page? 

**For AOs before 2009**
1. A one sentence summary exists in the AO metadata. 
2. FEC Record articles don't exist in the new system
Design question: What info will be presented on the AO page?
Hypothesis: The Summary from the metadata, since that's all that's available.

@AmyKort once we understand the limits/capabilities of HOW this Record data gets in, we can start speaking more confidently about the design solutions.

If I'm off track, please let me know!

**Comment by AmyKort** [comment]
A agree, @jenniferthibault . One clarification: we weren't thinking of trying to link to pdf versions of Record summaries if we implemented this plan. Over time, we were thinking about going back and inputting the text from all of the Record summaries of AOs into the CMS (there are a lot, but not an uncountable number) to make this content in particular more accessible. So, in this (half-baked) plan, only CMS-based articles would show up.

The one sentence summary from metadata would need to be there no matter what. The AO summary would be an additional source of information.

**Comment by noahmanger** [comment]
I like this plan. From a system angle, seems like the thing to do is to set a property on each FEC Record article that associates it with a particular AO. I _think_ this should be pretty easy to do using Wagtail's [REST API](http://docs.wagtail.io/en/v1.8.1/advanced_topics/api/v2/configuration.html).

For all Records going forward, this would just be a field that gets filled in when adding it. For all Records past, I think we could probably programmatically go through and assign them based on the title. Do all Record articles that relate to an AO follow the same title scheme?

**Comment by noahmanger** [comment]
So, after a little poking around, turns out this approach is really easy. (See https://github.com/18F/fec-cms/pull/774). 

In that case, in order to get this going, we'd need to: 
1. Settle on design answers to Jen's questions above
2. Merge the PR and either programatically or by-hand add an `advisory_opinion` property for each Record article
3. Add the front-end code to the AO page to pull this in

On #1, it seems like we have an approach [already designed](https://gsa.invisionapp.com/share/QCA404INT#/215254017_AO_Canonical-Collapsed), right?

![image](https://cloud.githubusercontent.com/assets/1696495/22448309/6780fa9a-e70d-11e6-80be-a5c56a2c606a.png)

Where, if there's now Record article yet, the "Background" section would not be there, but if it is, we would show it. As the designs show, the page would only show the first part of it and you could click to expand more.

**Comment by AmyKort** [comment]
Thanks! Folks on our end are really excited to make this work.

**Comment by vrajmohan** [comment]
For AO's from 2009 to now, it looks hard to do as the PDFs that cover multiple AOs are multi-column and are also _magazine style_, where an article is continued later on, in a potentially skipped page/column. I don't know how we would OCR these. @tony would know more.
