### ISSUE TITLE
Data issues - Candidate Search

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2210]
https://beta.fec.gov/data/candidates/?election_year=2016	

There are three things that I see that need to be taken care of before go-live:

1. ~The Unverified filers list needs to be applied so those candidates don't show up here.~ Captured in other issue

2. ~There are about 57 off-year candidates that are currently not showing up in search results because of the off-year bug identified last week.  I'll post details in that issue.~ Done

3. There are 62 candidates I can't find either in the beta candidate search or the API. They are listed on the "2016 Candidates missing from BETA" tab in Column B.
https://docs.google.com/spreadsheets/d/1P_KtGlStcniFZBy2aGw_-cR7KOmdeOFeq3ahrF06KlM/edit?usp=sharing

@ccostino @noahmanger @LindsayYoung

**Comment by jontours** [comment]
The candidates (from category 3) below are not showing up because of an inner join preventing them from ending up in the materialized view that supports the endpoint, the inner join fails because the field for party affiliation is null in `disclosure.cand_valid_fec_yr`:
```
 P60005469
 P60015310
 P60015369
 P60018751
 P60020500
 P60022209
 P60023017
 P60023025
 P60023041
 S6MO00388
```
After ATO/migration work is over will look into reasons for the rest of the missing candidates.

**Comment by LindsayYoung** [comment]
Thanks for hunting that down, it sounds like we should do a left join instead of an inner join

**Comment by noahmanger** [comment]
@LindsayYoung do we need to do something before these show up on staging? Because I'm still not seeing them.

**Comment by ccostino** [comment]
Yes, running `update_all`, which we're in the process of doing in all three of the GovCloud DBs, should address this!
