### ISSUE TITLE
Show links to HTML reports on /reports/ and /filings/

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2226]
So that users can view an HTML version of filings and reports, include a link to the HTML pages on docquery on responses from `/filings/` and `/reports/***/`.

---

The URL structure, as far as I can tell, is:
- **Electronic filings:** `http://docquery.fec.gov/cgi-bin/forms/[committee_id]/[filing_id]/`
- **Electronic filings:** `http://docquery.fec.gov/cgi-bin/paper_forms/[committee_id]/[filing_id]/`

This is lower priority than other work, but it should be easy. 

**Completion criteria:**
- [x] Include `html_url` for efilings on `/filings/` and `/reports/**/` responses in API
- [x] Include `html_url` for paper filings `/reports/**/` responses in API
- [x] Show `html_url` as a download option on the frontend

**Comment by jontours** [comment]
Dropping a note here for clarification, but guessing up above ^^ that the second bullet should say "Paper Filings".

**Comment by noahmanger** [comment]
Oh yes that's a fair assumption.

**Comment by noahmanger** [comment]
Working on the front-end for this and hit upon a small microcopy/UI question. All references we currently have to the different ways to access reports is to download them. Both the icon in the table and the label in the panel is for a download:

![image](https://user-images.githubusercontent.com/1696495/27459141-a146f4b8-5761-11e7-80ba-53f934c477c8.png)

One simple approach would be to make the main document title in the table be the link to the HTML version if it exists (fall back to PDF if not), keeping the options in the dropdown the same, and then relabling in the panel to "Read report" (or something better, but trying to stay away from "View").

![image](https://user-images.githubusercontent.com/1696495/27459195-d59b2b6c-5761-11e7-8d99-26222c0770a0.png)

I think it would be better to include the link in the dropdown as well so people know it's there explicitly, but feels weird with the download icon. 

Also, I'm wondering what we should name these links? On classic they're referenced just as "HTML" but that feels overly technical. We could just use "Web" as I did above or maybe there's something better.

Anyway, questions for @jenniferthibault and @jameshupp mostly.

**Comment by jameshupp** [comment]
If the main document title is web and falls back to PDF, I'd leave it out of the dropdown with the current icon, since that's more confusing than anything. 

As far as the list, I think `web` is fine in and of itself, but my concern is what happens with the addition of the `FEC` filetype. As a novice, my first reaction to `FEC` was confusion about what was different between those two things. `.fec` is clearly an extension, but `FEC` could just as easily mean FEC.gov. I think some kind of separation between the HTML option and the others is helpful. Here's one version (sorry for weird markdown table rendering):

|   |   |
|---|---|
|Read report | on the web |
|   | Download as CSV / PDF / FEC |

Or even more simply:

|   |   |
|---|---|
|Read report | web |
|   | CSV / PDF / FEC |

Some sort of separation. If it really needs to be a text-driven distinction, I'd consider using `webpage` or `online` rather than `web`. It's a stronger cue that this behavior is different, as it's the only non-three-character type.

**Comment by noahmanger** [comment]
+1 to webpage and good point about distinguishing as a file extension. I realized we actually use .fec / .csv / .pdf in the dropdowns, so what about just using that here:

![image](https://user-images.githubusercontent.com/1696495/27498996-9c76c8e0-5816-11e7-9360-a00ea171b941.png)

**Comment by jameshupp** [comment]
This looks good to me!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2499/ and https://github.com/18F/openFEC-web-app/issues/2153
