### ISSUE TITLE
distinct dev tasks

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2246]
Edit this with your ideas of dev tasks we could farm out without having to do the full onbording

 - ~scrapers~(We think we are good)
 - Load testing (jcc)
 - training development (is this done?)

**Comment by ccostino** [comment]
I'd be cautious about the training development only because we're attuned to FEC's needs and this is going to become a primary activity for some of us in the coming months, especially after the site flip.

The preliminary seed training we've done I think covers a good chunk of what we'll be diving into more, but until we're in the midst of it, leveraging outside help might be a bit difficult.

That said, it would be awesome to incorporate more of 18F Learn/Agile Corp into things in the future, if possible!
