### ISSUE TITLE
Election candidate lists

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2248]
https://beta.fec.gov/data/candidates/?district=00&cycle=2016&state=AK&office=H
and possibley here:
https://beta.fec.gov/data/elections/house/AK/00/2016/

The lists of candidates for each election is including extra candidate. The reason appears to be that it isn't using the candidate_election_yr in the data call.  Using just FEC_election_yr gets all the correct candidates but includes candidates from previous elections that are still connected to their committees.  This removes those earlier candidates:

fec_election_yr=in (2015,2016)
AND cand_election_yr in (2015, 2016)

This is important for the election pages. It may be also on the page with the second url above but it would be harder to find an example. The code should be the same in any event.

@hcaofec

**Comment by noahmanger** [comment]
The next step on this issue is to make sure that the API is using the correct value for the election year. This would be goo dto do pre-flip, but not high priority.

We should also look into whether using `cycle` vs. `election_year` as a filter on the data page makes a difference.

**Comment by jwchumley** [comment]
https://beta.fec.gov/data/candidates/?district=00&cycle=2016&state=AK&office=H

These four should not be on the list:
CHESNUT, DEBRA SUE - 2012 
CISSNA, SHARON MARIE - 2012 
COX, JOHN R - 2012 
VONDERSAAR, FRANK J - 2014

The rest of them are correct:
HEIKES, GERALD L - 2016
HIBLER, WILLIAM D - 2016
HINZ, LYNETTE - 2016
KILE, ZACHARY A - 2016
MCDERMOTT, JIM C - 2016
SOUPHANAVONG, BERNARD IGNATIUS MR - 2016
TINGLEY, JESSE J - 2016
WATTS, JON BRIGGS - 2016
WRIGHT, STEPHEN T - 2016
YOUNG, DONALD E - 2016

**Comment by noahmanger** [comment]
Ah ok. I see the issue. Again, this is a place where the actual parameter used is `cycle`, which corresponds to the cycle in which the candidate has a committee with financial activity; so if those candidates' committees were active in 2016, they would show up. But this definitely feels wrong. 

My suggestion is to instead make the filter on /data/candidates an election year filter and instead of showing two-year ranges, show every year:

![image](https://cloud.githubusercontent.com/assets/1696495/25642221/55a47fda-2f4d-11e7-8896-3afad07e42a7.png)

On beta.fec.gov/data/candidates/house/, though, we're actually interested in the time period of the finances, which should be a two-year cycle like this:

![image](https://cloud.githubusercontent.com/assets/1696495/25642236/6a25603c-2f4d-11e7-8332-63c38c03e340.png)

**Comment by noahmanger** [comment]
If that works, the fix is in https://github.com/18F/openFEC-web-app/pull/2000

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2000
