### ISSUE TITLE
investigate data slowness

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2263]
As reported by Jean and Rohan, we are not seeing performance parody on govcloud.

**Comment by ccostino** [comment]
Chris Nelson from cloud.gov is helping us take a look into what might be going on.

**Comment by ccostino** [comment]
It appears that this is likely the cause of physical network latency based on the tests Rohan has done at FEC and Chris has done for us.  Unfortunately there's not a whole lot we can do because Golden Gate is already setup to run things in BATCH mode, but there are two important pieces to note:

* Golden Gate is connecting directly to the RDS instances, which means an exposed port and the best we can hope for are batch operations
* PostgreSQL supports a [`COPY`](https://www.postgresql.org/docs/current/static/sql-copy.html) mechanism, which is a lot quicker than even batch processing

Chris shared an article with us that highlights a lot of these pieces very nicely: https://blog.2ndquadrant.com/postgresql-latency-pipelining-batching/

We should continue researching and talking with at least Rohan and Jean and see if we can come up with another solution that makes this processing go more quickly.  As of now, there seem to be two options, which we can also implement incrementally on each other to get us in an overall better state:

* Point Golden Gate to a local PostgreSQL instance(s), then do a dump of that instance and a restore into the RDS instance(s) - this still requires the exposed port for a direct connection
* Point Golden Gate to a local PostgreSQL instance(s), then do a dump in `COPY` mode, upload the data dump to an S3 bucket in GovCloud, then import the data from there via `COPY` - will likely require some kind of  daily/nightly running app/task to manage the S3 bucket and execute the commands

I'm not entirely sure how far this will get us, but it seems worthwhile to investigate and could help decouple some things that shouldn't have been tied so directly together as it is.  We'll update this issue more with our findings/discussions in the future!

**Comment by noahmanger** [comment]
Any more to do on this?

**Comment by ccostino** [comment]
@noahmanger:  Not at the moment.  We'll need to dedicate some time in the future to review the options outlined above, but I think that'll have to happen well after the site flip.  It might be a good thing to embark on with the DBA team down the road as some of the training/transition effort to dive more into the PostgreSQL side of things.  We could always create a new issue at that time, or put this back into the icebox until we're ready to tackle it again.

**Comment by noahmanger** [comment]
Ok cool. I'm going to move to the icebox.
