### ISSUE TITLE
As a reporter, I want a spreadsheet to to download analyze data. Add ability to export search results as a .csv

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#231]

**Comment by LindsayYoung** [comment]
We will want to use the existing FEC download infrastructure as much as we can. They have several servers dedicated to this and do that much better than they used to. We should revisit this after the MVP.

**Comment by noahmanger** [comment]
Let's talk about this, maybe next week. Not knowing what it would take technically, I have thoughts about where this might be really valuable to include in some way in an MVP, but want to be sure we're talking about the same thing.

**Comment by LindsayYoung** [comment]
If we get the file id from the warehouse, we can leverage the existing infrastructure for custom csv downloads with a reasonable amount of work. I am guessing this will happen, but it is not in my control so, I can't promise it will happen.

I don't think we should implement anything on our own. Some of the downloads people will want are very large. For example if someone wants all the contributions to Obama, that is 1,661,649 lines of a csv to write. There are over 8 million contributions for the 2012 cycle alone. I am sure we could implement something that would handle that, but it might be expensive and it would be duplicative since the FEC has expanded the number of servers dedicated to that task and has been building capacity over the years.  

I agree that the csv downloads are very important. We should try to include them in the MVP and revisit or csv distribution strategy after the MVP is released. 

I am also happy to chat more with you about this whenever.

**Comment by noahmanger** [comment]
Cool. Thanks for explaining. I didn't realize their existing infrastructure supported custom downloads. That's great. And yeah, all for leveraging what they have.

**Comment by noahmanger** [comment]
This is an old issue and the nuances will be captured in subsequent issues based off the story cards. So I'm closing.
