### ISSUE TITLE
IE processed vs raw  Filter problem

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2318]
1. Search for committee C90013301 (just a good example with multiple ie candidates)

2. Click on independent expenditures 

3. Click on the link in the first row of the grid. ($12,307,930.26)
 Observe the filters. They are correct.

4. Click on "Raw" and all the filters go away.  All the filters have been dropped. This makes no sense. The committee (C90013301) and the date range should carry over because they are the same in both processed and raw data. Otherwise no matter which committee you have navigated to you look at exactly the same set of raw IEs.

@noahmanger

**Comment by noahmanger** [comment]
I see what you're saying, but this is a tricky one. In order to have the raw data as fast as possible, we can't have all of the same indexes that are needed in order to maintain the same filters across both datasets. So with the first iteration of this feature, we tried it out by retaining values in the filters that stayed, while disabling the filters that were no longer available. However, usability testing showed that this was problematic: users didn't realize that the filters were disabled, and so there was confusion over what data was actually shown. From that we redesigned so that the two datasets just use entirely different filters. 

We can talk more about this though.

**Comment by LindsayYoung** [comment]
Can we keep cycle too? That keeps the API calls smaller.

**Comment by noahmanger** [comment]
Yep, I think that makes sense. Per our conversation earlier, I'm moving this out of the pre-flip list, but know that it's a real "nice to have".

**Comment by noahmanger** [comment]
I rewrote this issue here https://github.com/18F/openFEC-web-app/issues/2130, so I'm closing this.
