### ISSUE TITLE
Pac and Party reports returns nothing

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2319]
https://beta.fec.gov/data/reports/pac-party/?is_amended=false&data_type=processed

Presidential and House/Senate both return lists but if you choose PAC and Party it churns for a while and returns nothing.

**Comment by noahmanger** [comment]
I'm seeing this too. Looks like a 502 error in the API call. Can anyone look into this? @ccostino @LindsayYoung @jontours ?

**Comment by ccostino** [comment]
We were just discussing this in the FEC Slack #dev channel and the problem appears to be resolved.  The underlying cause was in the database with some of these queries:

```
canceling statement due to conflict with recovery
User query might have needed to see row versions that must be removed.
```

Which in turn was causing long-running queries to timeout in the web server resulting in worker timeouts (thus the 502 errors).  I'm not sure why these errors started happening but I didn't see any recent replication events or interruptions in RDS.  The production web site is using the read replica and that's where this activity was occurring, but again, no real indication as to why.

@jwchumley and @noahmanger, if you try again (you may need to hard refresh your browser), do you still see the error?

**Comment by ccostino** [comment]
For more details and things to look at more closely:

* http://stackoverflow.com/questions/14592436/postgresql-error-canceling-statement-due-to-conflict-with-recovery
* https://www.postgresql.org/docs/current/static/hot-standby.html#HOT-STANDBY-CONFLICT

**Comment by noahmanger** [comment]
This is working now, but it does seem to be particularly slow. I'm closing though since it's no longer broken.

**Comment by LindsayYoung** [comment]
This one is not working, the call times out (there are over a million records for this.) I double checked and the indexes look right. 

We might need to change pagination to what we have itemized data. 

The fastest frontend fix is to enforce filtering by cycle. Could we get that going @noahmanger?

**Comment by noahmanger** [comment]
That was an easy add: https://github.com/18F/openFEC-web-app/pull/1979

And it seems to help. Is the idea this is a temporary fix pre-flip and then we'll address the underlying issues later?

**Comment by LindsayYoung** [comment]
Thanks @noahmanger. I can add something to the API side too. 

I think that will buy us a lot of time. If this comes up as a request again, we can see if a change in the pagination would allow searches across all the records.

**Comment by noahmanger** [comment]
Fixed by https://github.com/18F/openFEC-web-app/pull/1979
