### ISSUE TITLE
update schedule views 

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2324]
related to https://github.com/18F/openFEC/issues/2309

We need to make a change to the schedule views in PG.  The current views join a schedule table to V_SUM. We need to change the join from V_SUM to F_ITEM. @fecjjeng @ChingKuan have some ideas. @ccostino @jontours 

The new join will look like this:
FROM disclosure.SCHEDULE alias, disclosure.f_item_receipt_or_exp fi
WHERE SCHEDULE.sub_id = fi.sub_id;

We need these changes applied to schedules listed below:
public.fec_vsum_sched_a_vw
public.fec_vsum_sched_b_vw
public.fec_vsum_sched_c_vw
public.fec_vsum_sched_c1_vw
public.fec_vsum_sched_c2_vw
public.fec_vsum_sched_d_vw
public.fec_vsum_sched_e_vw
public.fec_vsum_sched_f_vw
public.fec_vsum_sched_h1_vw
public.fec_vsum_sched_h2_vw
public.fec_vsum_sched_h3_vw
public.fec_vsum_sched_h4_vw
public.fec_vsum_sched_h5_vw
public.fec_vsum_sched_h6_vw
public.fec_vsum_f56_vw
public.fec_vsum_f57_vw
public.fec_vsum_f76_vw
public.fec_vsum_f91_vw
public.fec_vsum_f94_vw
public.fec_vsum_f105_vw

There are 4 columns we pull from V_SUM. But, we can pull them from F_ITEM

vs.form_tp_cd AS filing_form,
vs.rpt_tp,
vs.rpt_yr,
vs.rpt_yr + vs.rpt_yr % 2::numeric AS election_cy

fi.form_tp_cd AS filing_form,
fi.rpt_tp,
fi.rpt_yr,
fi.rpt_yr + vs.rpt_yr % 2::numeric AS election_cy

**Comment by fecjjeng** [comment]
Paul,

I can create another set of views that joins f_item table and the sched tables (for example: public.fec_fitem_sched_b_vw) for them to try.
The reason I suggested to use the name fec_fitem_sched_xx_vw are
1. They are joining ftime tables instead of vsum tables, use the old name fec_vsum_sched_xx_vw is misleading.
2. The views already have materialized views (ofec_xxx) built on top of them, in order to make changes to the view definition using the same name, the materialized views based on these views need to be dropped first. Using another view name will allow us some time for testing before dropping the existing materialized views that the API is using.

I had created several views in FR_DEV databases.  The row count for the fec_fitem view is less than the fec_vsum views, does it look correct?

/*
select count(*) from public.fec_fitem_sched_e_vw;
278400

select count(*) from public.fec_vsum_sched_e_vw;
282803
*/

/*
select count(*) from public.fec_fitem_sched_c_vw;
434423

select count(*) from public.fec_vsum_sched_c_vw;
441760
*/

/*
select count(*) from public.fec_fitem_sched_b_vw;
61028436

select count(*) from public.fec_vsum_sched_b_vw;
61622506
*/


As Joseph and I briefly discussed with you this afternoon, the performance of joining the two biggest tables (f_item and sched_a/sched_b) will need to be considered, depending on how these views are used (if the materialized views that utilizing them are refreshed once nightly it maybe tolerable) .  Also, if the new web site does not use f_item table, we will consider only transferring the core columns (such as form_tp_cd, rpt_tp, rpt_yr) that are needed instead of the full 116 columns, especially when the transferring speed to FR site is much slower than to the regular AWS site.  We will explore different options.

Please let me know if the proposed view name fits the need.


Jean

**Comment by PaulClark2** [comment]
Does the set of columns below make sense for a smaller version of FITEM? Or, are you thinking fewer columns?  Image number might not be necessary.

sub_id, 
v_sum_link_id, 
cmte_id, 
form_tp_cd, 
sched_tp_cd, 
rpt_tp, 
rpt_yr, 
image_num, 
file_num

**Comment by ccostino** [comment]
I haven't had a chance to follow up on this more yet, but should finally have time tomorrow to take a closer work, sorry for the delay!

**Comment by ccostino** [comment]
Coming back to this now, sorry for the delay:  @PaulClark2 was your question about the set of columns for me or for @fecjjeng or @ChingKuan?  If it is for me I know we'd probably want to preserve what we have if possible in terms of the columns that are ultimately present in the view that we'd base the materialized views on, but would double check with @LindsayYoung or @jontours to verify that.

**Comment by PaulClark2** [comment]
@ccostino my question was for @fecjjeng and @chingkuan. My understanding is fewer columns didn't make much of a difference in query speeds. It might make a difference in the daily update. I think Jean and Joseph are leaning toward leaving FITEM as is.

**Comment by fecjjeng** [comment]
We are also considering if there is other way to improve the performance.  But since we don't know the performance tuning capability of PostGreSQL that well, not sure how much we can do on the PostGreSQL side.  

@ccostino @PaulClark2 Carlo had mentioned that one other thing he was trying to ascertain is which table to watch changes.  If the API intends to only show records in schedule tables that is in the f_item table (is this the case?), maybe the sub_id/sched_tp_cd in DISCLOSURE.F_ITEM_RECEIPT_OR_EXP should be the driver to send records to the "partitioned tables" of sched_a_yrs and sched_b_yrs?
On the related topic, do we need to keep the records in sched tables (and their "partitioned tables") that is NOT in the f_item table?  Quite a lot records in the sched tables are not in the f_item table since that had been replaced by the amendment data.

**Comment by ccostino** [comment]
Thanks, @fecjjeng!  As for Postgres, there are plenty of opportunities and areas for performance tuning! :-)  If you're looking for some general resources to learn more, here are two:

* [PostgreSQL Performance Tips](https://www.postgresql.org/docs/current/static/performance-tips.html) - from the official documentation
* [Performance Tuning PostgreSQL](http://www.revsys.com/writings/postgresql-performance.html) - a write-up written by Frank Wiles, who has used PostgreSQL for a number of years in many different environments

Another big thing that can help is the [`EXPLAIN` statement (or `EXPLAIN ANALYZE`](https://www.postgresql.org/docs/current/static/using-explain.html) to see the query execution plans being run.  [`INDEX`es](https://www.postgresql.org/docs/9.6/static/sql-createindex.html) are also helpful on columns frequently accessed and PostgreSQL provides a number of different options.  More often than not, we've found just adding the default (btree) index on a few columns that we typically query for, join on, sort by, group by, etc., will go a long way in improving performance.

All of that said, we're also happy to set aside some time to review things with you and pair on these things to help!

Thank you (and everyone else!) for looking further into which underlying table to watch too, we definitely appreciate it!  It'll be a huge help to finally resolve #2309. :-)

**Comment by ccostino** [comment]
Quick update on this:  The DBA team, @LindsayYoung and I met and had a great conversation around all of these things.  The changes discussed in this issue in particular are slated for future development (there were a couple of other changes already made for immediate fixes to address the pre-flip needs), but not until we've all had a chance to meet a couple more times to plan things out further.  This can be put in the backlog in the mean time.

**Comment by ccostino** [comment]
I think this is now resolved, right @PaulClark2?  The views were updated recently, and they account for `f_item` now, right?

**Comment by ccostino** [comment]
Ah wait, we did this in two steps; the current views are setup with that extra `WHERE` clause, but there are new views built off with the `f_item` table now too.  I think we need to switch to those in the API though, which would fall under the other work we're doing I think.

**Comment by ccostino** [comment]
We're going to try and follow up on making this switch with the itemized schedule work we're doing.  We'll reach out to Helen for additional help while Jean is out!

**Comment by ccostino** [comment]
Another follow up to this:  These new `f_item` based views have been created in the `dev` environment but not `stage` or `prod`.  It also appears that we do need to switch all itemized data to use these new views, not just schedule A and B given the issues we're seeing with schedule E.

It looks like the next two steps are the following:

* Create these new views in `stage` and `prod`
* Update all API  references to use the new views

Am I missing anything @LindsayYoung, @jontours, @fecjjeng, or @PaulClark2?

**Comment by ccostino** [comment]
@PaulClark2 or @jwchumley:  I found a few other `fec_vsum` based views that we reference, do these need to be updated to be `fec_fitem` instead as well?  I don't see them in the `dev` database.

* `fec_vsum_f1_vw`
* `fec_vsum_f3_vw`
* `fec_vsum_f3p_vw`
* `fec_vsum_f3x_vw`
* `fec_vsum_f5_vw`

**Comment by jwchumley** [comment]
I can't log into PG from home so I can't look but if I recall these are all just form views and have no connection to f_item

**Comment by ccostino** [comment]
Ah okay, that makes sense, thanks @jwchumley!

**Comment by ccostino** [comment]
The work to support using these new views is now ready in PR #2483!

**Comment by ccostino** [comment]
We'll be able to test this in `dev` once the PR is merged, but we should keep this issue open until we've been able to verify numbers and the views are ready in `stage` and `prod` too.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by fecjjeng** [comment]
Yes

On Nov 22, 2017, at 1:05 PM, Amy Kort <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this ready to close?
