### ISSUE TITLE
Improve F2 results on /filings/

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2344]
While troubleshooting https://github.com/18F/openFEC-web-app/issues/1962, I caught a few tweaks we should make to the /filings/ endpoint in order to get what we're trying to get. 

First, either we need a `election_year` filter, that filters by the `election_year` property on F2s, or the `cycle` property should be adjusted to be the year that the F2 is actually for. Currently, you can filter by `cycle`, but because this refers to the year a document was filed rather than the year it's _for_, you can't actually find, say, F2s filed _for_ the 2018 election; you can only find those that were filed _during_ a time period.

Second, the `document_description` for F2s apparently uses the `cycle` as the year to display, so that an F2 filed in December 2016 for the 2018 election gets a description of `Statement of candidacy 2016`, but I think it should be `Statement of candidacy 2018`. It makes for confusing results like:

![image](https://cloud.githubusercontent.com/assets/1696495/25364229/c5e83b76-2915-11e7-953f-252a1c206cba.png)

**Comment by LindsayYoung** [comment]
We are using `report_year` for the naming, which is generally the year that document applies to. 

We can change the naming convention to not include a year for statements of candidacy. That is probably the quickest fix.

There isn't an election year for statements of candidacy in the filings information, there is report year, but, that isn't what you want here. We can make a special endpoint from the F2 records, but that would take a bit more work because I am not sure what that data looks like, it might have nulls that need to be populated by previous docs etc.

**Comment by noahmanger** [comment]
Really? In the first result here, the PDF says its for the 2018 election, which is what the `election_year` field says, while `report_year` is 2016: https://api-stage.open.fec.gov/v1/filings/?candidate_id=H8WI01024&api_key=DEMO_KEY&form_type=f2&election_year=2018

**Comment by LindsayYoung** [comment]
Ok, I checked and you are right about election year available, so we can add a filter. https://github.com/18F/openFEC/blob/9068fd915a4d4578b38165683047643cc8b717fc/data/sql_updates/filings.sql#L37

We use report year, because if a filing from three years ago is amended, it will have the report year as three years ago and the receipt date as today.
Not all reports/documents are going to have and election year, that is the one we want in most cases.

This is where we make the document names, we can add a new case for F2.
https://github.com/18F/openFEC/blob/5309838d3ea2758556b4b74ec852d97459d36cea/webservices/utils.py#L251

**Comment by noahmanger** [comment]
Ok cool. I have a workable solution on the app side for the filter for now, so that's less urgent. Updating the names would be nice. Thanks for looking into it.
