### ISSUE TITLE
Better default date for null dates on legal resource documents

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2345]
When a legal resource doc doesn't have a date, it defaults to 01/01/1900, which is weird:

![image](https://cloud.githubusercontent.com/assets/1696495/25397544/72e02a32-299d-11e7-8d7d-cbcf729df030.png)

We should have a better default for this.

**Comment by jenniferthibault** [comment]
## Research into why this is happening

@anthonygarvan found that there are there are 157 such documents out of many thousands displaying date 01/01/1900.

Broken down by document category:

>Final Opinion  |  65
Draft Documents  |  11
AO Request, Supplemental Material, and Extensions of Time  |  5
Commissioner Statements  |  76

Tony made a [CSV](https://github.com/18F/openFEC/files/976216/docs_with_no_dates.csv.zip) of all of those documents. Here's a sample pulled from them:
- https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/legal/aos/68520.pdf
- https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/legal/aos/69412.pdf
- https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/legal/aos/67340.pdf
- https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/legal/aos/58183.pdf
- https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/legal/aos/68043.pdf

We had originally thought that a long-term solution would be to manually update the dates for these 157 docs in the database, but looking at these reveals that there is no date on the document itself, so that option is off the table.

Further, Jason from FEC confirmed in slack:
> if there is no date present on the document, then I or whomever is dating and titling, unchecks the date box. This has been standard operating procedure for all published MURs, ADRs, and AOs.  If you were do to the same search on the MURs and ADRs, you will generate a much larger list...

So confirmed that there is no date on the document, and we are unable to date it. Therefore, the date wasn't recorded/is unknown.

This gives us solid logic for writing microcopy for this field, which is the permanent solution.

## Possible solutions
Task: Figure out copy for the date field when no date is entered in the database

Options:
> `Not recorded`
> `Unknown`
> `Undated`

@emileighoutlaw @nickykrause what do you think of the above options?

**Comment by anthonygarvan** [comment]
Tentatively using 'Unknown', feel free to update PR with latest copy: https://github.com/18F/openFEC-web-app/pull/2010

**Comment by nickykrause** [comment]
I personally prefer "not recorded." It seems the most accurate/specific. "Undated" is similar but might be an awkward word? Although, it has the benefit of including "date" right in the word, which makes it clear what is missing, as compared to "Not recorded," which might add a slight effort for the user who has to ask "_what_ wasn't recorded? oh yeah, the date"

Minor details, I suppose...but I am curious what emileigh thinks!

**Comment by jenniferthibault** [comment]
`Undated` = `Not dated` ?

**Comment by nickykrause** [comment]
Yes, sure - I  like `Not dated`  👍

**Comment by emileighoutlaw** [comment]
I love `Not dated`

**Comment by jenniferthibault** [comment]
Thanks all! Updated in https://github.com/18F/openFEC-web-app/pull/2010/commits/c2d9e4c371c7f3e7e69c00cd86ad25bb7e1abce3

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/issues/2010
