### ISSUE TITLE
Schedule E by candidate returning null data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2364]
On [this page](https://beta.fec.gov/data/candidate/P80001571/?tab=other-spending&cycle=2020&election_full=true) the IE table is missing the committee column:
![image](https://cloud.githubusercontent.com/assets/1696495/25684322/8318449c-3015-11e7-8b1f-02591e4e8927.png)

Looking at the [API call](https://api.open.fec.gov/v1/schedules/schedule_e/by_candidate/?api_key=DEMO_KEY&sort_hide_null=true&sort=-total&per_page=10&page=1&candidate_id=P80001571&cycle=2020&election_full=True), and both `committee_id` and `candidate_id` are null:
```
{
"committee_name": null,
"committee_id": null,
"total": 66811.79,
"candidate_id": null,
"cycle": 2020,
"count": 16,
"candidate_name": null,
"support_oppose_indicator": "O"
},
```

This works fine for previous cycles.

**Comment by jontours** [comment]
The root cause is this, is that for this candidate the entries in the table `ofec_candidate_history_mv` table has no entry with a two year period ending in that cycle (2020), so when it tries to glean the names from that table, nothing comes back.  I'd argue it would makes sense to pull names from the latest cycle that has an entry, not some cycle that hasn't happened yet.

**Comment by jontours** [comment]
After spending some time trying to resolve this I'm gonna say it's hard to fix with any tricks of logic.  The problem is that the cycle that is being passed in is `2020`, but there are no active records in either `CandidateHistory` or `CommitteeHistory` (for any of the contributing committees) for the cycle of `2020`, so not sure what to do here.  @PaulClark2 @LindsayYoung  do y'all have any insight on the best way to move forward with this?

**Comment by noahmanger** [comment]
I inadvertently landed on a front-end fix for this while solving a different but related problem, which I include (and explain) here: https://github.com/18F/openFEC-web-app/pull/2013
