### ISSUE TITLE
Bug: Candidate and committee totals coverage dates are wrong

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2416]
Perhaps related to the totals work that was done, the candidate and committee totals coverage dates are all wrong:

![image](https://cloud.githubusercontent.com/assets/1696495/26381131/5fd2d278-3fd7-11e7-820e-1ad3309d5653.png)

e.g. https://api.open.fec.gov/v1/candidate/S6AL00195/totals/?per_page=20&api_key=DEMO_KEY

cc @jontours @LindsayYoung

**Comment by noahmanger** [comment]
Tagging in @jontours.

**Comment by jontours** [comment]
Gonna leave some notes here because I'm tired enough to completely forget by the morning.  At first I thought the logic was off, but now I'm thinking there could be a problem with how we are calling to_timestamp(), it seems to be pumping about dates from the '70s regardless of what dates are passed in (using with a format of YYYYMMDD), which to say, is pretty...groovy.

**Comment by jontours** [comment]
Yup, that's probably it, `to_timestamp` expects an `int`, and that value is seconds since the epoch, which started in 1970.  Docs here: https://www.postgresql.org/docs/9.6/static/functions-datetime.html#FUNCTIONS-DATETIME-TABLE

**Comment by ccostino** [comment]
Thanks @jontours, good hustle on this!

**Comment by noahmanger** [comment]
Resolved.
