### ISSUE TITLE
Bug: Incorrect candidates showing up running in a district

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2428]
Started here https://github.com/18F/FEC/issues/4114

It seems we are using `fec_election_yr` instead of `cand_election_yr` to determine what elections candidates have participated. We should use `cand_election_yr` to make that determination.

See, https://www.fec.gov/data/candidates/house/?cycle=2018&state=TX&district=07, for example. James Lloyd and Maria Espinoza are 2016 candidates but not 2018 candidates.

For candidates, cycle=2018 should include candidates with election years 2017 and 2018.

**Comment by LindsayYoung** [comment]
@PaulClark2 I thought fec_election_yr was the 2-year cycles that applied to a candidate. What does it actually mean?

**Comment by LindsayYoung** [comment]
I am asking because we want to be careful with this fix, because we would want to show the candidate's committee information on the candidate profile page in all cycles where there is financial activity.

**Comment by PaulClark2** [comment]
Candidate's can be pulled forward into the next two-year period if any of their authorized committees are still active (not terminated or administratively terminated).  `fec_election_yr` is a construct for convenience. 'cand_election_yr' represents the elections a candidate filed a F2 for.  

We need to show financial activity for years beyond the candidate's election year, if it exists. However, we shouldn't display a candidate for a two-year period just because they have financial activity. In other words, we should see Lloyd's 2017-2018 financial activity from his candidate or committee profile page, but Lloyd should never show up in a search for 2018 candidates. 

For example Lloyd and Espinoza filed a Forms 2 for 2016, they both have two rows in `cand_valid_fec_yr` and in `cand_cmte_linkage`. 

cand_valid

CAND_NAME	|	CAND_ID	|	CAND_ELECTION_YR	|	FEC_ELECTION_YR
----	|	----	|	----	|	----
ESPINOZA, MARIA L	|	H6TX07128	|	2016	|	2016
ESPINOZA, MARIA L	|	H6TX07128	|	2016	|	2018
LLOYD, JAMES	|	H6TX07110	|	2016	|	2016
LLOYD, JAMES	|	H6TX07110	|	2016	|	2018


linkage

CAND_ID	|	CAND_ELECTION_YR	|	FEC_ELECTION_YR	|	CMTE_ID
---	|	---	|	---	|	---
H6TX07110	|	2016	|	2018	|	C00599530
H6TX07110	|	2016	|	2016	|	C00599530
H6TX07128	|	2016	|	2018	|	C00600858
H6TX07128	|	2016	|	2016	|	C00600858

**Comment by noahmanger** [comment]
Arg. This is the issue that won't go away. This is going to require a front-end tweak to go along with an API change, as far as I can tell.

On the front-end we're filtering by cycle two-year period, but you're right this should totally be election year. But because it's a totals endpoint, we also need to still pass that two-year cycle period through. Where this gets tricky is when those aren't the same, as in the case of odd-year special elections. 

Right now, just searching by election_year yields weird results for GA: https://api-stage.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=true&election_year=2017&sort=-receipts&per_page=30&page=1&office=H&state=GA

I _think_ what we need to do is pass `cycle=2018&election_year=2017`, but `election_year` as a parameter doesn't seem to be working right.

Hopefully this helps and not just confuse the matter.

**Comment by LindsayYoung** [comment]
For the front end can we pass election_year=2018&election_year=2017 for the selector and use cycle to in the results to create links etc.?

**Comment by noahmanger** [comment]
I missed this issue in sprint planning. @jontours do you have time to look into it?

**Comment by jontours** [comment]
for sure!

**Comment by noahmanger** [comment]
Pulling out the tasks here from my earlier comment:

- [ ] The API `election_year` filter needs to be fixed.  It doesn't seem to work correctly at all for [this query](https://api-stage.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=true&election_year=2017&sort=-receipts&per_page=30&page=1&office=H&state=GA)
- [ ] The front-end needs to be updated so that choosing a time period of 2017-2018 filters to `cycle=2018&election_year=2017&election_year=2018`

**Comment by LindsayYoung** [comment]
Good catch! I think the API is looking for election year = 2017 instead of 2017 in a list of election years

**Comment by chasehd** [comment]
This is just a comment from an outside observer, but if you take the `totals` portion out of the query, you get more results--results that have multiple values in `election_years`, which would seem to imply that `election_year` does search through it; however, just not when `totals` is applied. I just started looking at the API a few days ago, so it's very possible that I'm missing the point, but I just thought I'd add my thoughts as I'm using the API as part of my daily work.

**Comment by LindsayYoung** [comment]
Thanks for taking the time to write in @chasehd. We will look into that

**Comment by jontours** [comment]
Don't want to over promise and haven't verified yet, but think the PR here: https://github.com/18F/openFEC/pull/2454, may remedy this issue.  I'll verify today.

**Comment by noahmanger** [comment]
Thanks for weighing in @chasehd ! Always feel free to chime in or ask questions.

**Comment by noahmanger** [comment]
Closing in favor of a consolidated issue in https://github.com/18F/openFEC/issues/2590
