### ISSUE TITLE
Get Lindsay the fields we want to include on committee and candidate endpoints

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#244]
Get her which fields we want to show relationship between the two endpoints.

**Comment by rjmajma** [comment]
Hey @LindsayYoung, please make sure the appropriate issue in this sprint lists this as a dependency if it is one.

**Comment by LindsayYoung** [comment]
@rjmajma added #246 as the follow up to this one

**Comment by theresaanna** [comment]
@noahmanger Because you're more familiar, will you have time to put this list together? If not, I'll dig around.

**Comment by noahmanger** [comment]
AFAIK: 
For the candidates page, we should be able to get the related committees `name`, `designation`, and `id`.

For committee pages, we should be able to get related candidates `name`, `office_sought`, and `id`.

Might a committee have different designations for different candidates? Like, could it be an authorized PAC for some and unauthorized for others? If so, then we'd need the `designation` per candidate.

**Comment by theresaanna** [comment]
@LindsayYoung How does that look?

**Comment by LindsayYoung** [comment]
Thanks guys!

We have candidate_id and designation on the committee endpoint and committee_id on the candidate endpoint. 

The committee designation does not depend on candidate so that simplifies things. 

I think we can add committee name to the candidate endpoint as well as candidate name and office_sought to the committee endpoint.

I updated #246 to reflect this.
