### ISSUE TITLE
latency issue with filings

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2461]
A form 99 was filed on Tuesday with image number 201706070300158623. It appears in the Filings search:
https://www.fec.gov/data/filings/?data_type=processed&form_type=F99&beginning_image_number=201706070300158623

But not on the profile page:
https://www.fec.gov/data/committee/C00572537/?cycle=2016&tab=filings

Also the count on the profile says 19 but there are only 9.

**Comment by noahmanger** [comment]
It's actually there:
![image](https://user-images.githubusercontent.com/1696495/26938821-3e9bc79a-4c2a-11e7-8b96-ee7d59552da8.png)

This is kind of a weird quirk, but because there's no financial reports for the 2018 cycle for this committee, it's defaulting to 2016. If you switch to 2018 it's there:
https://www.fec.gov/data/committee/C00572537/?cycle=2018&tab=filings

**Comment by noahmanger** [comment]
Since this isn't an actual bug I'm going to close.

**Comment by jwchumley** [comment]
Before you close look at one more:
