### ISSUE TITLE
Bug: Alabama senate special election missing

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2476]
Currently the Alabama special senate election is missing from the election lookup data: https://www.fec.gov/data/elections/?cycle=2018&state=AL

**Comment by noahmanger** [comment]
I'm pretty sure this is an API/data issue. The API call that the tool makes is this: https://api-stage.open.fec.gov/v1/elections/search/?api_key=DEMO_KEY&cycle=2018&state=AL

There are no senate results in that.

On the client side we also call the `/dates/` endpoint to look for any upcoming election dates, and if there are any for state/office/district combinations that match those provided by the `/elections/` endpoint, then we use the new date, but this requires that seat showing up as having an election in the first place.

cc @LindsayYoung

**Comment by LindsayYoung** [comment]
The [election date model](https://github.com/18F/openFEC/blob/f234a1833b3561da525017ad49ac657c55335780/webservices/common/models/dates.py#L46) takes the data directly from `fecapp.trc_election` 

The data is not in the table. The following query yields no results:
```
select * from fecapp.trc_election where election_state='AL' and election_yr=2017 order by election_date desc;
```
These are the elections we have for the year in that table:

 election_state | office_sought | election_district |       election_notes       | election_date 
--|--|--|--|--
 GA             | H             | 06                | Rep. Tom Price's Seat      | 2017-06-20
 SC             | H             | 05                | Rep. Mick Mulvaney's Seat. | 2017-06-20
 CA             | H             | 34                | Rep. Xavier Becerra's Seat | 2017-06-06
 MT             | H             | 00                | Rep. Ryan Zinke's Seat     | 2017-05-25
 SC             | H             | 05                | Rep. Mick Mulvaney's Seat. | 2017-05-16
 SC             | H             | 05                | Rep. Mick Mulvaney's Seat. | 2017-05-02
 GA             | H             | 06                | Rep. Tom Price's Seat      | 2017-04-18
 KS             | H             | 04                | Rep. Mike Pompeo's Seat    | 2017-04-11
 CA             | H             | 34                | Rep. Xavier Becerra's Seat | 2017-04-04
 KS             | H             | 04                | Rep. Mike Pompeo's Seat    | 2017-02-11
 KS             |               | 04                | Rep. Mike Pompeo's Seat    | 2017-02-11
 KS             | H             | 04                | Rep. Mike Pompeo's Seat    | 2017-02-09
 GA             | S             |                   |                            | 2017-01-10
 GA             | H             |                   |                            | 2017-01-10

@jwchumley @PaulClark2  do we want to follow up to get the data added. Also, that table has been problem before, is there something we can do to help?

**Comment by LindsayYoung** [comment]
Nope, looked at the wrong data base-

**Comment by jontours** [comment]
I was afraid it was a data problem.  I think @PaulClark2 @jwchumley would know where that data lives.

**Comment by LindsayYoung** [comment]
Well, it is in the elections date endpoint- 
https://api.open.fec.gov/v1/election-dates/?api_key=DEMO_KEY

I also see the records in the candidate history view, so that is good
`select * from ofec_candidate_history_mv where two_year_period=2018 and state='AL' and office='S';`

I am thinking that we are filtering things out. I think I remember a problem where people would register for elections that did not exist. 

I can look into the ElectionList resource more tomorrow

Also, I will follow up with infrastructure about the old dbs still being around.

**Comment by LindsayYoung** [comment]
Ok, I think we never had special elections in the election list or election view. I think we did not notice because house races will show for every cycle.

Here is the [resource](https://github.com/18F/openFEC/blob/develop/webservices/resources/elections.py) for that endpoint, I think the join with ElectionResult is excluding special elections. I think we will want to enhance or replace that filter with something we create off of `fecapp.trc_election`

**Comment by LindsayYoung** [comment]
Noting that trc_election data starts in 2003

**Comment by jontours** [comment]
Yeah, I was the last to work on this resource.  I made the join more restrictive (changed to inner join), to eliminate weird bugs like Presidential elections for 2018, e.g.  `trc_election` sounds familiar back when we were talking about this stuff...in February!?  Time flies.

**Comment by LindsayYoung** [comment]
It seems like our options are:
- base it off real election date records - start 2003 ( would still need a rewrite)
- base it off what people file for - lots of false positives
- some really complicated logic that gets it right from 2003 and some data fixes pre 2003

**Comment by jwchumley** [comment]
That fixed it.


________________________________

**Comment by noahmanger** [comment]
Seems like the first option is probably best? Do you have a preference?

**Comment by LindsayYoung** [comment]
I do like the fist option best, I think that is closest to what we are trying to convey in that search. We can still have links to the older election pages from candidate profiles. 

Maybe, in the future we can make a manual select for the older pages if there is a need. Or get a list of Senate special elections, since those are the tricky ones to show.

I would also like to hide the zip code search for the previous redistricting periods since that we never made zipcode mapping files for them.

**Comment by LindsayYoung** [comment]
#2485 should fix this
