### ISSUE TITLE
Check for and remove older software versions [ATO]

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2488]
Older and outdated software was discovered. Some of the reported versions contain vulnerabilities ranging from DoS, XSS, as well as SQL injection. In addition, on some of the sites, multiple versions of the software were found running. The following libraries were found:

The library jquery version 1.8.0.min has known security issues.
The library jquery version 2.2.4 has known security issues.
The library moment version 2.10.3 has known security issues.
The library handlebars version 2.0.0 has known security issues.
The library jquery version 1.10.1.min has known security issues.

**Comment by xtine** [comment]
Double checking these dependencies, it seems that we should be good on most of these except for `moment`. For performance reasons I may have to remove the library and write some custom date functions already, so that issue should probably be prioritized if `moment` is out of date and posing a security risk.

**Comment by LindsayYoung** [comment]
Thanks @xtine 
Let's look into getting that done once we have the cmd deploy issues ironed out

**Comment by xtine** [comment]
With https://github.com/18F/fec-cms/pull/1338 I have upgraded Moment from the older vulnerable version, so we are up to date with our npm packages.

**Comment by LindsayYoung** [comment]
Final work for that here: https://github.com/18F/fec-cms/pull/1338
