### ISSUE TITLE
Replace hard-coded Senate special election years and classes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2621]
Right now, senate classes for special elections are hard-coded in [`constants.py`](https://github.com/18F/openFEC-web-app/blob/master/openfecwebapp/constants.py#L632). It would be good to replace this with something dynamic from the API.

- [x] make special election years data-driven
- [x] check with Public Records for older special elections

Test with http://127.0.0.1:8000/data/elections/senate/AL/2018/

@hcaofec

**Comment by lbeaufort** [comment]
This Issue is a result of PR [#2276 ](https://github.com/18F/openFEC-web-app/pull/2276)

**Comment by LindsayYoung** [comment]
We will want a new endpoint in the api that populates that data.
We want a way not to hardcode that constants list

We have election data on fecapp.trc_election so we could make an endpoint from that table that just supplies that list to the web app of when senate elections happen and updated the list when the election data changes.

Practically speaking, House elections will be every 2yr cycle and presidential elections will be every other cycle, we know when the senate elections should be but senate special elections need to be added to the drop downs, that can easily accommodate the regular schedule. 

If we could add class to this data, it would be great, but joining the date data and the finance data is really hard, so that doesn't need to be immediate. 

@lbeaufort can you look at how to reproduce that list using fecapp.trc_election with post gres, and then we can give you more support on how to add that to the API?

**Comment by PaulClark2** [comment]
I didn't realize we were using `fecapp.trc_election` as our election source.  Good to know. I asked Laura to review data in `disclosure.dim_race_inf`. @lbeaufort can you confirm the Senate special general elections in  `fecapp.trc_election` and `disclosure.dim_race_inf` are the same. I think `fecapp.trc_election` only goes back to 2004.

**Comment by LindsayYoung** [comment]
We just had a chat and @lbeaufort has a good idea on how to leverage some existing endpoints. 

@PaulClark2 weren't the `dim_ tables` from the warehouse? We migrated off of all of those a long time ago.

**Comment by PaulClark2** [comment]
Many of them were from the warehouse but `disclosure.dim_race_inf` is a FECP table.

**Comment by PaulClark2** [comment]
Merged: https://github.com/18F/fec-cms/pull/1471
