### ISSUE TITLE
candidates showing up outside their cycle

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2628]
We made a lot of election fixes in #2590 but this is still outstanding.

Here is an example of two candidates that are listed because their fec_election_yr is 2018- because they have committees connected to them and should have a profile page for those years, but should not show up in the candidate results, because they don't have a cand_election_yr of 2018.

https://www.fec.gov/data/candidates/house/?cycle=2018&state=TX&district=07
H6TX07110
H6TX07110

This also needs a test that is sophisticated enough to catch this in the future. We have seen this a few times. 

- [ ] on profile pages show financial data if committee is still active
- [ ] on election pages confirm candidate are running for office during the two-year period being displayed

**Comment by PaulClark2** [comment]
@jwchumley and @hcaofec can you investigate how widespread this issue is?

**Comment by jwchumley** [comment]
Looks like the issue is with the candidate search endpoint (and maybe other candidate endpoints).  the "cycle" data element is described as the two -year election cycle in which a candidate runs for office but what it seems to be doing in this case is using the committee's activity instead of the candidates election year to determine whether to include the candidate in the output or not. This is wrong.   Cycle should  ONLY look at the candidate's election year and not the committee's activity period.
@hcaofec  could you look at the code and see if you can suggest a correction?

**Comment by hcaofec** [comment]
If these two candidates are not running for 2018, should they be inserted into cand_inactive table for that particular cycle? 
@jwchumley @LindsayYoung

**Comment by PaulClark2** [comment]
The candidate doesn't have a 2018 F2 row. I don't think cand_inactive is the solution.  

The candidate election year is 2016 in the relevant tables. The candidate/committee pair correctly has a 2016 (candidate election year) /2018 (FEC election year) row in `cand_cmte_linkage` and `cand_valid_fec_yr` because the PCC is still active.

`select election_yr, form_tp, cand_id, begin_image_num, sub_id, receipt_dt from disclosure.nml_form_2_2Z_view where cand_id = 'H6TX07110' order by receipt_dt desc;`

`select * from disclosure.cand_valid_fec_yr where cand_id = 'H6TX07110';`

`select * from disclosure.cand_cmte_linkage where cand_id = 'H6TX07110';`

**Comment by hcaofec** [comment]
There is also a column 'candidate_status' returned by the API which has values like:
 P	STATUTORY CANDIDATE IN PRIOR CYCLE
 C	STATUTORY CANDIDATE
Can we use add 'if...else' logic to this page using this column 
@jwchumley @PaulClark2 @LindsayYoung

**Comment by hcaofec** [comment]
Election page looks correct. These two candidates are not shown. ( H6TX07110,  H6TX07128 )
https://www.fec.gov/data/elections/house/TX/07/2018/

**Comment by LindsayYoung** [comment]
Thanks for getting this done! @hcaofec   😄
