### ISSUE TITLE
Add automated checks for terminated processes - AWS RDS

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2752]
Research task

Creating a better alarm for idle processes (cloudwatch)

**Comment by jwchumley** [comment]
Create separate issue for implementation for next sprint.

**Comment by LindsayYoung** [comment]
I think this is a bit harder than I thought because we would need a thresh hold so that we would not get notified until there were something like 3 or more "idle in transaction" queries in one message 

Though, there may be a way to do it, here are the docs:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

**Comment by ccostino** [comment]
This is a bit more frustrating because CloudWatch is for watching log events.  Aside from enabling all queries to be logged along with their duration ([an example of which can be seen here](https://www.depesz.com/2008/08/28/hunting-idle-in-transactions/)), we wouldn't be able to hook on to any event or state to watch for.

Furthermore, RDS itself only notifies about events that take place related to system administration tasks, instance events, e.g., shutdowns, startups, patching, etc., and server/instance performance metrics (see documentation listed below for more details).  This leaves us with having to periodically query the database itself to uncover any `idle` or `idle in transaction` queries.

While not exactly ideal, we might be able to leverage other AWS components to do this easily, namely using [AWS Lambda for scheduled events](https://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html).  What we could theoretically do is create a script (much like [the aforementioned example](https://www.depesz.com/2008/08/28/hunting-idle-in-transactions/)) to query the database and look for troublesome things in the `pg_stat_activity` table, then have AWS Lambda execute it and return the results to us somehow; it looks like you can wire this up with [AWS CloudWatch Events - Schedule](https://docs.aws.amazon.com/lambda/latest/dg/with-scheduledevents-example.html).

This, combined with the query monitoring that we are already doing in conjunction with pgBadger, should help with what we're aiming for here. :-)

AWS Docs for more reference:

* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Monitoring.html
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.html
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html
* https://docs.aws.amazon.com/lambda/latest/dg/welcome.html

**Comment by AmyKort** [comment]
After some research we've determined that the benefit of this work doesn't outweigh the effort to implement the change. We'll hold onto this great research in case we decide to revisit it later.
