### ISSUE TITLE
add retries for redis

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2773]
Short outage on cloud.gov can result in a download failure that lasts for hours. In the future, we'd like to have code in place to keep trying to reconnect if there is a brief outage. It will help us identify issues by generating additional error messages as well. 

Here is an example of set up of redis retries on another project- https://github.com/18F/cg-uaa-extras/pull/89/files

**Comment by ccostino** [comment]
The solution in that linked PR simply logs a warning if it is unable to connect to Redis and doesn't do anything more (though it will try and connect each time a command is run against it).  Is this enough in our case, or do we need some other form of graceful fallback, e.g., reporting back a status and message that shows up when a user tries to export that says something to the effect of "Downloads are unavailable at this time, please try again later."

**Comment by ccostino** [comment]
Actually in reading through I saw that the original solution wasn't ultimately used, this one was used instead: https://github.com/18F/cg-uaa-extras/pull/100

**Comment by ccostino** [comment]
I was able to catch up with a couple of folks on cloud.gov about this and learned a few things that are worth clarifying:

The service plan we're using now is HA (High Availability), but instance disruptions (both planned and unplanned) will still happen; what they've noticed is that a lot of clients (including Celery) like to maintain persistent, open connections to Redis and don't do well with retrying to connect, if they even bother trying.  Because of this, they've updated the [cloud.gov Redis HA documentation](https://cloud.gov/docs/services/redis/#ha-client-configuration) to account for adjusting the timeout settings.

This may not necessarily be enough though, because the instance that was connected to under the hood may not become available again; what should happen is the client should try connecting to the broker/router/whatever you want to call it that would in turn connect it to an available instance.  The work done in the follow-up PR I found does just that.  I'll confirm again to be sure that's appropriate, but it seems that's the path we need to take on our side as well!

**Comment by ccostino** [comment]
The solution in https://github.com/18F/cg-uaa-extras/pull/100 that I found won't fix our issue because this doesn't retry anything, it simply provides more detailed and useful error messages in the case of a connection error to Redis.  Our use-case here is different:  we're trying to re-establish a connection to Redis automatically in the event that we lose it.

**Comment by PaulClark2** [comment]
There's no GitHub frowny face emoji.

**Comment by ccostino** [comment]
This Google Group thread describes the issue we seem to be having, but there's no resolution there.  Another thing we came across though is the [changelog for the latest version of `redis-py`](https://github.com/andymccurdy/redis-py/blob/master/CHANGES#L1), which has a few fixes related to timeouts and retries.

[Celery's defaults](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-broker_connection_timeout) around this account for [cloud.gov's Redis HA service recommendations](https://cloud.gov/docs/services/redis/#ha-client-configuration), so I'm inclined to think there's something else we need to adjust/configure.  The `redis-py` updates look like a low impact way of trying something, though.

**Comment by AmyKort** [comment]
cc @LindsayYoung

**Comment by AmyKort** [comment]
thanks!
