### ISSUE TITLE
Update uglify 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2794]
Update from uglify-js 2.4.24 to a patched version

**Comment by xtine** [comment]
The github warning comes from `package-lock.json` showing the dependency tree for `gulp-handlebars` which uses an older version of handlebars that uses an older version of uglify-js. Technically the older handlebars code is never executed because we force `gulp-handlebars` to use the latest version of handlebars that we require, so we can ignore this until we decide to upgrade to swagger-ui 3.x which doesn't use the gulp task build system.
