### ISSUE TITLE
Fix invoke deploy command for manual deploys

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2834]
The recent changes for DB migrations added support for migrating the database with the [`invoke deploy`](https://github.com/18F/openFEC/blob/develop/tasks.py#L159) command that we have, but it now assumes that there is a migrator account always set, which we wouldn't have locally.  This prevents us from running the `invoke deploy --space <space>` command locally to do a manual deploy of the API.

One way to solve this is to provide a fallback mechanism to see if that environment variable is set and if not, fall back to whatever `SQLA_CONN` is set to.  Another option is to refactor our whole deployment setup a bit more and leverage [CircleCI workflows](https://circleci.com/docs/2.0/workflows/) like we did for the [FEC Pattern Library CircleCI config](https://github.com/18F/fec-pattern-library/blob/master/.circleci/config.yml) as a part of them (this would be a larger level of effort, but likely worth it).

I am definitely open to other suggestions, though. :-)

**Comment by LindsayYoung** [comment]
We shouldn't really be doing manual deploys, unless something has gone wrong. In that case, we can also do a manual migration with the flyway command passing the database name, user name, and password. I am not sure coding this up is worth the effort. It might also encourage manual deploys which are not good for best practices and ATO compliance because they circumvent our ci process.

**Comment by ccostino** [comment]
Fair enough, thanks @LindsayYoung!  I'm going to close this issue then so it's not cluttering anything up. :-)
