### ISSUE TITLE
Test Schedule B/expression-based sort changes on `stage`

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2922]
Because these are pretty significant changes: https://github.com/18F/openFEC/pull/2905 we should manually test the API/CMS for these changes, and load test stage and compare to production with Locust, and analyze query performance with PGBadger. This would be a good opportunity to pair with FEC staff who haven't used Locust yet.

Locust notes are here: https://docs.google.com/document/d/1ru6Qg0ErTQLD7a86qxW7kbaKbzkayt_X9PmGjZdC_nY/edit

- [x] manually test the API/pagination/sort
- [x] manually test CMS Schedule B searches/pagination 
- [ ] load test stage and compare to production with Locust.
- [x] generate some logs by running the queries/searches, then pull those down and run them in pgBadger to see what we're looking at.

**Comment by ccostino** [comment]
Okay, some initial tests performed!  Unfortunately we didn't capture a full baseline of staging before the release branch was cut, but I performed a little bit of manual testing this morning and then implored others (@rjayasekera, @fec-jli, @fecjjeng, and @hcaofec) to do more. :-)

We then ran our first locust test against the staging API and there was a pretty high error rate, which surprised us.  We also noted a few instances where schedule B was definitely not performing as expected still, so it looks like we will need to tackle issue #2923 sooner rather than later.

In the meantime, it'll also be interesting to see what pgBadger reports with the query logs, so we'll be doing that next before anything else.

**Comment by ccostino** [comment]
PR #2932 created to address the remaining `COALESCE`-based indexes.

**Comment by ccostino** [comment]
Staging RDS logs have been pulled during the time of testing and shared among the team; a couple of us have run them through pgBadger and are starting to sort through the results.

It appears that while there is no negative impact on performance, there's no significant positive impact either.  Some of this is due to queries that do *not* have `COALESCE` in the statement and therefore would be good candidates for additional performance tuning, but for the statements that do have the `COALESCE` statement, I am leaning toward missing indexes being the culprit.

It'll be interesting to see if we have better performance for the `COALESCE`-based queries once the remaining indexes from PR #2932 are merged in.

**Comment by ccostino** [comment]
I ran some more Locust tests to take baseline samples in `dev` before the remaining `COALESCE` indexes get applied for Schedule B.

**Comment by fecjjeng** [comment]
@ccostino Great job!! In addition to the Locust tests run, it would be useful to save the postgresql logs generated during the run for the baseline analysis too.  It seems Locust is a good tool designed for Stress test of the system.  However, since the main focus is on performance tuning, pgBadger and/or New relic may provide us more clues.

**Comment by ccostino** [comment]
@fecjjeng yup, you're right!  I've been pulling the RDS logs after running the tests for that very reason. :-)

**Comment by AmyKort** [comment]
Testing complete!
