### ISSUE TITLE
Research and adjust IOPS for RDS

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2952]
There was a performance degradation the morning of  20/02/18 Looking at the AWS stats, it looks like we could use some more iops-

For this task:
 - [x] research the ideal iops settings 
 - [x] price out increase
 - [x] verify permission to increase
 - [x] increase for both read replicas and Prod https://github.com/18F/fec-infrastructure/blob/master/terraform/fec_rds.tf

Here is the doc we have been using for keeping tabs on postgres tuning
https://docs.google.com/document/d/1zB3CZPaS0gY9vPaIhM5Xn3U-lIMOvsVaip77sIXpJmU/edit#heading=h.zi3gefjj5f4c

**Comment by AmyKort** [comment]
We'll want to complete this early in the sprint.

**Comment by ccostino** [comment]
For more information about provisioned IOPS:  https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#USER_PIOPS

**Comment by wjiangFEC** [comment]
Rohan and I did some research on IOPS.  We would like to get more statistic data to make a more accurate estimate of the average read/write throughput usage.

**Comment by rjayasekera** [comment]
Getting the Most Out of Amazon RDS Provisioned IOPS
Using Provisioned IOPS storage increases the number of I/O requests that the system can process concurrently. Increased concurrency allows for decreased latency since I/O requests spend less time in a queue. Decreased latency allows for faster database commits, which improves response time and allows for higher database throughput.

For example, consider a heavily loaded OLTP database provisioned for 10,000 Provisioned IOPS that runs consistently at the channel limit of 105 Mbps throughput for reads. The workload isn’t perfectly balanced, so there is some unused write channel bandwidth. The instance would consume less than 10,000 IOPS but would still benefit from increasing capacity to 20,000 Provisioned IOPS.

Increasing Provisioned IOPS capacity from 10,000 to 20,000 doubles the system’s capacity for concurrent I/O.  Increased concurrency means decreased latency, which allows transactions to complete faster, so the database transaction rate increases. Read and write latency would improve by different amounts and the system would settle into a new equilibrium based on whichever resource becomes constrained first.

It is possible for Provisioned IOPS consumption to actually decrease under these conditions even though the database transaction rate can be much higher. For example, you can see write requests decline accompanied by an increase in write throughput. That’s a good indicator that your database is making better use of group commit.  More write throughput and the same write IOPS means log writes have become larger but are still less than 256 KB. More write throughput and fewer write I/O means log writes have become larger and are averaging larger than 32 KB since those I/O requests consume more than one I/O of Provisioned IOPS capacity.

https://stackoverflow.com/questions/18777070/aws-rds-provisioned-iops-really-worth-it
AWS RDS Provisioned IOPS really worth it?
However, if I were a financial consultant in a small or medium business, I would just scale-up(as in CPU, memory) on my RDS instances gradually until the performance/price matches P-IOPS. 

http://iomelt.com/iomelt-aws-ebs-benchmark-december-2012/

**Comment by rjayasekera** [comment]
Provisioned IOPS (SSD) Storage
For each DB Instance class, Amazon RDS provides you the ability to specify or provision the I/O capacity your database needs. You can provision and scale from 1,000 IOPS to 40,000 IOPS and 100 GB to 16 TB of storage with the PostgreSQL DB Engine. Note that maximum realized IOPS will vary by database workload. With Provisioned IOPS, you will be charged for the throughput and storage you provision. However, you will not be charged for the I/Os you consume.

Storage Rate    $0.125 per GB-month
Provisioned IOPS Rate    $0.10 per IOPS-month

In our case currently:
instance - db.r3.2xlarge (8 vCPU, 64GB RAM)
Storage - 2000GB
PIOPS - 12000
(if we decided to increase PIOPS to 20K then it is going to cost us additional $800/month)

Our storage is 2000GiB so 20K PIOPS makes sense. From AWS doc 

AWS documentation recomendation

Provisioned IOPS  |  Volume Size
--------- | ------------
100            |                 10 Gb
1,000         |                 100 Gb
2,000        |                 200 Gb

In my opinion we should go for db.r3.8xlarge (32 vCPU, 244 GiB RAM) / Storage 2000GiB / PIOPS 20000

**Comment by wjiangFEC** [comment]
Good information. I do think we max out the IOPS sometimes from the graph. Increase the IOPS should help.

Wenchun

On Feb 27, 2018, at 12:52 PM, Rohan Jay <notifications@github.com<mailto:notifications@github.com>> wrote:


Provisioned IOPS (SSD) Storage
For each DB Instance class, Amazon RDS provides you the ability to specify or provision the I/O capacity your database needs. You can provision and scale from 1,000 IOPS to 40,000 IOPS and 100 GB to 16 TB of storage with the PostgreSQL DB Engine. Note that maximum realized IOPS will vary by database workload. With Provisioned IOPS, you will be charged for the throughput and storage you provision. However, you will not be charged for the I/Os you consume.

Storage Rate $0.125 per GB-month
Provisioned IOPS Rate $0.10 per IOPS-month

In our case currently:
instance - db.r3.2xlarge (8 vCPU, 64GB RAM)
Storage - 2000GB
PIOPS - 12000
(if we decided to increase PIOPS to 20K then it is going to cost us additional $800/month)

Our storage is 2000GiB so 20K PIOPS makes sense. From AWS doc

AWS documentation recomendation

Provisioned IOPS        Volume Size
100     10 Gb
1,000   100 Gb
2,000   200 Gb

In my opinion we should go for db.r3.8xlarge (32 vCPU, 244 GiB RAM) / Storage 2000GiB / PIOPS 20000

**Comment by LindsayYoung** [comment]
Adding increasing the IOPS to 2000 on prod, and the prod mirrors will cost additional $4108.80 a month

**Comment by LindsayYoung** [comment]
Adding some context from meeting we had about this decision.

We are going to do a more conservative increase of 100 additional IOPS for the production and the two production read replicas. We want to make this change and then see if that makes an impact on latency and impact on migration. We can make additional changes as necessary.

This change would add $513.6 a month to our bill.  We will implement this next week if the costs are approved.

**Comment by wluoFEC** [comment]
This is approved!  thanks

**Comment by fecjjeng** [comment]
How much will increase of 1000 addition IOPS be?

**Comment by LindsayYoung** [comment]
Wanted to flag that I made a mistake, I priced out 1,000 more IOPS but dropped the zero here. I wanted to flag here so we are on the same page.

**Comment by LindsayYoung** [comment]
Thanks @fecjjeng for flagging this!

**Comment by LindsayYoung** [comment]
Thanks @rjayasekera, @fecjjeng and @wjiangFEC! This was applied last night
