### ISSUE TITLE
Consider showing /totals data in candidate & committee results tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#346]
Just an idea, but it might be really valuable to show top line totals data in the candidate and committee tables. It gives a very quick look into the relative weight and importance of different results, and if your'e doing something like filtering down to all candidates in a certain state, you can do basic comparisons between them. Just want to flag this for further discussion.

**Comment by arowla** [comment]
This got thrown in this sprint but we haven't actually discussed how this would work. Would we want to include totals for just the current election cycle, the last one completed, or all of time? How would we communicate that to the user? Would we be allowing users to filter to different election cycle totals on the browsing/searching pages? Would this be for just browsing, or name/keyword searches as well? (Asking all these questions because they have ramifications for how this would be completed on the back end.)

I'm tempted to throw this one back into the backlog for grooming, since not much time remains in the sprint. Sorry I didn't catch this sooner.

**Comment by LindsayYoung** [comment]
I think we should have election views to compare similar candidates and committees. Aside from the time-sensitive issues Alison mentioned, I think putting everything together encourages apples to oranges comparisons.

**Comment by arowla** [comment]
Agreed- so we throw this one back?

**Comment by noahmanger** [comment]
Sorry I totally missed this discussion. I agree, let's talk more about it.

**Comment by jmcarp** [comment]
Now that we have election pages with per-candidate fundraising totals, I'm wondering if we can close this. Thoughts @LindsayYoung @noahmanger?

**Comment by LindsayYoung** [comment]
Agreed.
