### ISSUE TITLE
Create user stories from user research

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#402]
*Goal:* Turn the compiled [user research](https://mural.ly/t/gsa6/m/gsa6/1421109755684) into a list of user stories for the entire fec.gov project.

**Comment by rjmajma** [comment]
Turns out, this was easy to do. The information in the Murally was ready to go. I've gone ahead and put all of the suggestions written there into the Trello board as story candidates. 

We're much further ahead than I thought we were, so we can augment the goal of this task to: 
- [ ] Organize the story candidate list
- [ ] Port story candidate ideas that aren't reflected currently but on the site
- [ ] Flesh out the story candidates and begin to organize within the product backlog

**Comment by rjmajma** [comment]
Completed!
