### ISSUE TITLE
Remove nested committees from candidate results

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#504]
- [x] Remove nested field marshalling for committees
- [ ] Remove any joins or calls to nested objects in the endpoint `get()` or `get_candidates()`
- [ ] Remove or comment out any `db.relationships` on Candidate models.
- [x]  Update automated tests

**Comment by LindsayYoung** [comment]
I have removed the embedded committee resource and updated the tests.

I can't remove the joins in the models,  `get()`, or `get_candidates()` without breaking the `/committee/id/candidates` endpoint.

This also gets rid of committee_id filtering on `/committees`, I am happy to add that back in since I think filters are helpful but would require a join in cases where committee_id was requested.

**Comment by LindsayYoung** [comment]
To be a bit more clear, the `CandidateCommitteeLink` model still needs the link for committee_id to be filterable. The links that created the nesting are removed form the candidate models.

**Comment by LindsayYoung** [comment]
I think we are on the same page and this is taken care of in pr #516

**Comment by LindsayYoung** [comment]
dependency web app refactor #511

**Comment by LindsayYoung** [comment]
covered by #588
