### ISSUE TITLE
Make candidate history endpoint

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#505]
Make a new view, ofec_candidate_history_mv. Remove active_through and election_years. Replace with just “election_year”. Route should be `/candidate/<id>/history`.

**Comment by LindsayYoung** [comment]
This is going to produce an endpoint that shows the state of a candidate at the end of a two-year period.

This will need to use the dimcandproperties table since, that has the dynamic data.

Things to consider- 
- What if the users try an odd numbered year? I would like to be forgiving
- Would it be helpful to give an out of range message if there are no results for that year?

I don't know exactly how I am going to do it yet, but I do know how to make a full history endpoint so I think I will re-create that, and then try to narrow that down into this leaner version.

**Comment by arowla** [comment]
Hey Lindsay, I think you are actually talking about a different endpoint here. The endpoint in this task should return multiple results, one for each two year cycle (assuming there's no need for odd years). The Python layer should probably translate odd numbered years into the even numbered version. Since this is the task to return everything, don't worry about out of range situations just yet.

**Comment by LindsayYoung** [comment]
Ok, I made the one that I was thinking of. I think it will be useful, so I pushed the branch. I am happy to make the endpoint you want, but I don't know how. Can we talk tomorrow?

**Comment by LindsayYoung** [comment]
here is the branch https://github.com/18F/openFEC/tree/candidate_history

**Comment by arowla** [comment]
Took a look at the branch-- it's close to what we want here. It is is still aggregating the years to get `active_through` and `election_years`, though. It should not have either of those columns, but use `dimcandstatusici.election_year` straight up, without aggregation. It'll need to group on that, too, of course. The join line to `dimcandstatusici` aliased to `csi_recent` can be removed, as well.

The filters in the endpoint code should be filtering directly on `election_year`, rather than working with `expire_date` and `load_date`. The order_by will need to use `election_year`, too. 

You also have a duplicate `year` arg parser.

It occurs to me that perhaps the year filtering, rather than always rounding up to the even year, should blow out to both the odd and even value, like: 2013 -> [2013,2014] or 2014 -> [2013, 2014], etc., since there is  some odd-year election_year data in there, and we should make sure our filtering catches it. We could also do it another way instead, which would be to do it in the SQL, by creating a column such as `two_year_period`, which would always contain the even-numbered year. (We can talk tomorrow about how to do that if you are interested in going that route-- I don't feel too strongly about it either way.)

**Comment by LindsayYoung** [comment]
Thanks for the feedback. I am taking out active-through, the join to csi_recent and the extra year parsing as well as adding election_year. I will push that when I finish implementing. 

Perhaps you are thinking of a better sql technique, but I thought that we still need to look at the expire date to find the most recent information, since the forms are amended at random there is often more than one record per year. Also, when we want the form that applies to a given year, there may not be a filing that year, but the previous filing has not expired so that is the filing we want. 

If you take a look at Jim Moran in dimcandproperties, cand_sk=2710143946, you can see a good example of how the information changes over time. 

Election_years is necessary for the year dropdown, so I don't understand why we would take that out. 

What I am trying for, is that if you don't pass in a year, it will give you the most recent record for that candidate. If you do pass in a year, it returns the information that was true at the end of that year. I am focus on the information that the web app needs, without overdoing it again. 

Thanks!

**Comment by LindsayYoung** [comment]
OK, I think I get the election_year vs. election_years issue. Is it that we can only have one and election year is more helpful in this view?

**Comment by arowla** [comment]
I am on my way downtown, so I will just briefly address your last question,
since I am on my phone. Election year needs to be a single year, because
this endpoint will return a _list_ of candidate records year by year, and
election_year needs to reflect which year each record is for. If we need
something to show all years for the dropdown, we could include that, but I
am leaning towards throwing that in a separate endpoint to return just that
piece of info, like /candidate/id/years. It is best not to mix time series
data with aggregate data.

**Comment by LindsayYoung** [comment]
Thanks!

**Comment by arowla** [comment]
More comments for the branch:

* new sql file has ‘candidate’ misspelled in filename
* Rename table suffix from `_vw` to `_mv` (to easier see that it's materialized— need to do a sweep on other tables for this later)
* In Python get_candidates() method, remove `for argname in…` block, as none of those filters are supported here
* Expire and load dates need to be handled in the SQL (will get to this later)
* order_by() should be election_year (desc)
* Question: we talked about implementing the `year` filter as a part of the URL instead of as a query param, e.g. `/candidate/<id>/history/<year>`... Should we just do that now?

**Comment by LindsayYoung** [comment]
That all sounds solid to me. I will attack the things on that list and then loop back to you about the sql.

**Comment by LindsayYoung** [comment]
Ok everything in PR #532 except the SQL changes: 
- Expire and load dates need to be handled in the SQL (will get to this later)
- order_by() should be election_year (desc)

We can talk about that Monday.

**Comment by LindsayYoung** [comment]
Almost done, need to tweak the underlying table.
