### ISSUE TITLE
Discussion: election cycle choosing

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#522]
@LindsayYoung @arowla I have some questions/things I'd like to talk about around election cycle defaults.

1) I'm thinking that it might make sense to be able to ask for `cycle=latest` on any of the endpoints. It would return the latest election cycle record on a single record endpoint, and only records that are related to the latest cycle on list endpoints. Should perhaps match what the search does?

2) Will the search continue indefinitely to default to the latest two election cycles? We should probably match this up with how we're treating election cycle defaults elsewhere?

3) We have this date of 2/20, iirc, to switch to a new election cycle, but it sounds like there's more complexity there. We should figure that out with FEC.

Probably more soon...

**Comment by LindsayYoung** [comment]
Theresa, these are all really good points that we should talk more about. Here are my initial thoughts on the things you outlined:

1) I agree there should be an easy way to get the latest cycle. As much as possible things should default to the most recent cycle. 

2) The API is defaulting a little broader than strictly the last 4 years. Is currently looking at the past 4 years and the next year. You can find that logic in the default year function of webservices/common/util.py 

The idea behind that is that you would always get a sitting president.  We could expand to go back 6 years to make sure we get all the sitting senators too. The reason for the default was that in the current system, the old results were burying the more reverent new results. 

Right now, the date restrictions are not transparent on the web app and there are a few ways we could approach that. 

One way to solve that is to have the filters for 2013, 2014 and 2016 shown as pre-selected and give the user the ability to click on multiple cycles to change their preferences. (Not pressing, but we would then want to make sure the defaults only go 3 years back in even numbered years so that we line up with the cycle.) 

Or, we could take off the year filtering for the search by either adding `year=* `to the `/candidates` call or taking away the default years from the API.

Additionally, we could also make the browse view just show one cycle. Default to the current cycle, show that default in the filter and give the user the ability to change the election cycle.  

3) We do need to talk about this some more. In the last discussion with them, It sounds like the best way to attack that might be to always show the most recent data. If we can do that and show the date that the next filing is due, people should be able to  figure out what is going on without anyone having to make the system show things a particular way on a rigid schedule.

**Comment by noahmanger** [comment]
Just to chime in with my UX sense:

Yes we need to be transparent both on the browse page and the search page with which cycles we're showing. I actually really like the idea of of checkboxes with some pre-selected. i think often times people may want multiple. Right now, one of the confusing things on the search results page is why you only get certain results and not others. I'll be addressing this in the new designs. 

I also think it might make sense to have the search default to 6 years. Definitely need all the sitting senators in there, right?

**Comment by noahmanger** [comment]
Related, I'm not sure how we talk about these in the UI. Do we say: "Select an election cycle" or "Select a year"? And what's the difference? 

So if you select the 2014 election cycle it shows candidates / committees active in 2013 and 2014. But what if you do 2013?

**Comment by LindsayYoung** [comment]
How about select a two-year period

For the current cycle, we would want to select 2016.

**Comment by noahmanger** [comment]
Oh right, that's the language. We should probably always say the two years. So it's 2013-2014, 2015-2016, etc. I'm just thinking UI, not backend.

**Comment by noahmanger** [comment]
Here's how I could see it working on search results ( #514 ): 

![new search results](https://cloud.githubusercontent.com/assets/1696495/6905892/f67d847e-d6df-11e4-88fe-58208b13d0c2.png)

Basically defaults to having a couple options selected, with one more unselected (or something like that), but then you could always add additional ones with the dropdown, which would work as so:

![additional filters](https://cloud.githubusercontent.com/assets/1696495/6905903/044ddaf4-d6e0-11e4-901d-5b50678f4b88.png)

(I'm thinking of using this check-box + dropdown for additional options approach on the main filters as well...allows us to surface common options while still having the rest available).

**Comment by LindsayYoung** [comment]
I like that- it seems really clear and intuitive!

**Comment by rjmajma** [comment]
I really dig the way this was designed. Prompting the users with the three most recent election cycles is a great choice. Nice work.
