### ISSUE TITLE
Continuous deployment to CF

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#553]

**Comment by theresaanna** [comment]
Taking myself off of this. Would recommend finding another assignee. @rjmajma @leahbannon

**Comment by jmcarp** [comment]
Per discussion with @arowla, we should automatically push updates to Cloud Foundry for passing builds as follows:
* develop -> dev
* master -> stage
* master with release tag -> prod

**Comment by jmcarp** [comment]
I think there are (at least) three ways to approach this problem, with different pros and cons. The trade-off is between simplicity and keeping the API and webapp in sync when we deploy. If sync isn't a major concern (i.e., if changes to one app aren't likely to break the other one), then the first option below is best. Otherwise, options 2 or 3 would be more appropriate.

In theory, breaking changes to the API should also increment the API version, so once we get v1 into a stable state, we shouldn't have to worry about synchronization between apps at all--meaning option 1 would be best. In practice, I don't think the API is stable yet, so we may want to couple the apps for the time being anyway. Thoughts @arowla @LindsayYoung?

Option #1: Independent builds for API and webapp
* On successful API build, deploy API
* On successful webapp build, deploy webapp

Option #2: Coupled builds for API and webapp
* On successful API build, deploy API and corresponding webapp branch (optionally using blue-green)
* On successful webapp build, trigger a build of corresponding API branch

Option #3: Move API and webapp to shared repo
* API and webapp tests run in the same build
* On successful build, deploy both API and webapp (optionally using blue-green)

**Comment by noahmanger** [comment]
Nothing to contribute, but just wanted to say I'm excited this is
happening. Go team! :)

On Tue, May 12, 2015 at 8:32 AM, Joshua Carp <notifications@github.com>
wrote:

> I think there are (at least) three ways to approach this problem, with
> different pros and cons. The trade-off is between simplicity and keeping
> the API and webapp in sync when we deploy. If sync isn't a major concern
> (i.e., if changes to one app aren't likely to break the other one), then
> the first option below is best. Otherwise, options 2 or 3 would be more
> appropriate.
>
> In theory, breaking changes to the API should also increment the API
> version, so once we get v1 into a stable state, we shouldn't have to worry
> about synchronization between apps at all--meaning option 1 would be best.
> In practice, I don't think the API is stable yet, so we may want to couple
> the apps for the time being anyway. Thoughts @arowla
> <https://github.com/arowla> @LindsayYoung
> <https://github.com/LindsayYoung>?
>
> Option #1 <https://github.com/18F/openFEC/issues/1>: Independent builds
> for API and webapp
>
>    - On successful API build, deploy API
>    - On successful webapp build, deploy webapp
>
> Option #2 <https://github.com/18F/openFEC/issues/2>: Coupled builds for
> API and webapp
>
>    - On successful API build, deploy API and corresponding webapp branch
>    (optionally using blue-green)
>    - On successful webapp build, trigger a build of corresponding API
>    branch
>
> Option #3 <https://github.com/18F/openFEC/issues/3>: Move API and webapp
> to shared repo
>
>    - API and webapp tests run in the same build
>    - On successful build, deploy both API and webapp (optionally using
>    blue-green)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/553#issuecomment-101321515>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
This happened.
