### ISSUE TITLE
Year filtering on /committees is broken

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#649]
Year filtering for /committees works for me locally but not on http://api.open.fec.gov/?year=2012&api_key=xxx

This is needed for filtering the committee results in the browse view.

**Comment by jmcarp** [comment]
Looks like something's different about the `expire_date` column. In production, it only has two values: 2015-03-10 (for a handful of rows) and null (for most of them). Looking into this now.

**Comment by leahbannon** [comment]
I noticed I can't change the year on the dropdown on candidate pages. Is this related? (Chrome and Firefox)

**Comment by LindsayYoung** [comment]
That sounds like an additional issue with the web app

**Comment by jmcarp** [comment]
I think it was intentional--looks like a stopgap until the API was fixed. I see that @noahmanger added the `disabled` attribute to that select in https://github.com/18F/openFEC-web-app/commit/0eabcf28f7c1e9e3a01c4781e9666192e42ca4d2. @noahmanger, is the idea to reenable the select once filtering is fixed on the backend?

**Comment by LindsayYoung** [comment]
Ok, that makes sense
