### ISSUE TITLE
Date Limit all views to recent data

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#698]
Filter out psychedelic data from the 70's and cover 1980-present.

This will fix data quality issues from old ids that were reused. 

@arowla There is an email about this yesterday, but this seems like the most straight forward fix.

**Comment by arowla** [comment]
:+1:

**Comment by LindsayYoung** [comment]
Views to update- 
remove all results before 1980

|view                                          | what to filter on | 
|----------------------------|----------------------------|
create_candidate_detail_view | two_year_period from dimcandproperties - this needs to be added |
create_candidate_history_view | two_year_period from dimcandproperties |
create_candidates_view | two_year_period from dimcandproperties - this needs to be added |
create_committee_detail_view | rpt_yr from dimcmteproperties  - this needs to be added |
create_committees_view | rpt_yr from dimcmteproperties - this needs to be added |
create_fultext_table | two_year_period from dimcandproperties and  rpt_yr from dimcmteproperties |
create_linkage_name_view | *  |
create_reports_house_senate_view | two_yr_period_sk from facthousesenate_f3 |
create_reports_pacs_parties_view | two_yr_period_sk from factpacsandparties_f3x |
create_reports_presidential_view | two_yr_period_sk from factpresidential_f3p |
create_totals_house_senate_view | two_yr_period_sk from facthousesenate_f3 |
create_totals_pacs_parties_view |  two_yr_period_sk from factpacsandparties_f3x |
create_totals_presidential_view | two_yr_period_sk from factpresidential_f3p |

*in dimlinkages, cand_eleciton_yr and fec_eleciton_year can be several years off, there are not nulls in either so that is good. 

I am going on the assumption that the general years are more reliable then individual dates

How does that sound @arowla @jmcarp ?

**Comment by jmcarp** [comment]
Looks good to me. Just to be clear, we're keeping candidates and committees that were around before *and* after 1980, right? So that committees running from 1975 to 1985 would be preserved.

Also, does anything bad happen if we keep all rows from `create_linkage_name_view`? What if we have a candidate (let's say Joe Biden) who ran committees before and after 1980? Then it seems like the linkage table would include references to non-existent committees for that candidate. I don't *think* this would break anything, since we aren't actually using foreign key constraints here, but wanted to confirm that with you.

**Comment by LindsayYoung** [comment]
I think we won't get those links if we filter the linkage table properly. 

It might be good idea to have a methodology section or glossary-style link for our data methodologies.

**Comment by LindsayYoung** [comment]
To answer your first question- We won't have candidates and committees before 1980 because they have re-used ids that are causing problems.

**Comment by LindsayYoung** [comment]
It would also be good to add two_year_period to committees from cand_election_yr in dimcmteproperties.

That way we will have the data standardized by 2-year-period.

**Comment by jmcarp** [comment]
Thanks for the clarification! One more specific question: will we have a record for the Republican National Committee? Looking at the current `ofec_committees_mv`, it's been around from 1976 until the present. Is the idea to drop data about the RNC pre-1980, or drop the committee entirely because it's been around since before 1980?

**Comment by LindsayYoung** [comment]
WE are keeping committees that start before the cut off if they continued to be active. We are just filtering out their earliest reports form our tables. Those committees should have multiple reports. in the case of the RNC, they have 47 records in dimcmteproperties and we would only filter out the ones from the 70s.

**Comment by LindsayYoung** [comment]
Paul suggested that for the first release, we may want to be even more conservative- just focusing on 2011-2016 for the most recent data. I think that once we have the profiles properly filtering we could add all the 1980-2010 data. 

Another thing to consider, is that the earliest of that data won't have electronic source documents. I would  rather display the data we have then hide the data because it is incomplete.
