### ISSUE TITLE
To make summary data easier to read, improve scale on inline bar charts

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#756]
Could we add a minimum to the scale. Maybe $50 or $100? 
for example- $3 as 100% looks odd
![screen shot 2015-05-14 at 10 51 18 am](https://cloud.githubusercontent.com/assets/4406333/7634226/6f252854-fa27-11e4-9721-bee7fd052134.png)

**Comment by noahmanger** [comment]
Is this still something we care about? @jenniferthibault ?

**Comment by jenniferthibault** [comment]
I don't think we want to add a minimum here, $3 still isn't $0. — Do the $0 categories still show up with the sliver of bar? I think we'd want to not show anything at all in that graph column.

**Comment by noahmanger** [comment]
Yeah, I think we're talking about two separate issues. Lindsay's talking about $3 taking up the full bar, because it's the highest number in the set. I don't know if there's a good way to get around that.

As far as $0 showing a sliver of column, I agree that we should get rid of that.

BUT, @jmcarp and I have been discussing refactoring this whole component, so I don't think we should spend much time on it now. I'll see if there's a quick fix and if not, just table it.

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/suJmV4xKbKUmLDnUEFZhfg

**Comment by noahmanger** [comment]
No longer relevant.
