### ISSUE TITLE
HTTP site still has basic auth activated

### ISSUE THREAD

**Issue by NoahKunin** [18F/openFEC#831]
Should direct to HTTPS site instead.

cc @LindsayYoung @leahbannon

**Comment by LindsayYoung** [comment]
@konklone I thought this covered in the work you did?

**Comment by LindsayYoung** [comment]
@NoahKunin  If I type http://open.fec.gov/ it takes me to https://open.fec.gov/ Was that not working for you or are you talking about something else?

**Comment by jmcarp** [comment]
The issue is that the basic auth check and the https redirect happen in the wrong order. When users who haven't previously authenticated hit http://open.fec.gov, they'll be prompted for basic auth credentials, then get redirected to https, then get prompted for credentials again. And the first batch of credentials won't be encrypted.

This should be as simple as reversing the order of the basic auth and sslify extensions. I'll take a look.

**Comment by LindsayYoung** [comment]
Thanks @jmcarp
