### ISSUE TITLE
Schedule A Donations endpoint

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#836]
This will allow for display of granular donations. 

It is pretty straight forward, there are just a lot of records.

**Comment by jmcarp** [comment]
Following up on discussion in #305, let's talk through our options for handling the size of this table.

* Restrict to recent election cycles. This is simple and should give us good performance, but of course we lose most of the data. The current FEC site lets users browse donations at least back to 2000.
* Use partitioned tables. For example, we might partition on report year, election cycle, or some function of the committee ID (e.g. hash(name) % number of tables). This gives us all the data and good query performance, *unless* we want to run queries that span multiple partitions. That means we have to think carefully about the partitioning function before we start.
* Don't do anything. Adding indices on a big table like this is slow, but once they've been added, queries are still pretty snappy. We definitely wouldn't want to rebuild the view from scratch nightly, since it would take too long, but update performance should be manageable if we just insert the new rows. And some counts would be slow, but we may be able to get by with a combination of indices as approximate counts (e.g. `SELECT reltuples FROM pg_class WHERE oid = 'public.sched_a'::regclass;`).

I think an important preliminary question to answer will be the queries we want to expose through the API. If we want to make queries on contributions a sub-resources of committees (e.g. `/v1/committee/<committee_id>/contributions`), then a partition by hash of committee ID would be a good solution. But if we *also* want to show all contributions by ActBlue to any committees, that partition wouldn't work well.

@arowla and @LindsayYoung, what do you think? @noahmanger and @msecret, ignoring the implementation details, any thoughts about what kinds of queries we'll want to support through the API?

**Comment by jmcarp** [comment]
Follow-up on the "do nothing" option: we can get very fast approximate counts using an awesome hack that parses the output of `explain`. Which actually works reasonably well, and is recommended on the postgres wiki: https://wiki.postgresql.org/wiki/Count_estimate. If we require exact counts, though, I don't think "do nothing" would work.

**Comment by LindsayYoung** [comment]
I think that that most searches will be tied to a particular committee, form, looking for a particular donor, or looking for the most recent records.

**Comment by noahmanger** [comment]
It sounds like it might be helpful to test this on a smaller scale with users to see what they need. From user research, I think we know there's a few discrete needs:
- Search across all contributions to all committees by particular fields like: name, employer, occupation, location
- Search within a committees receipts to find contributions by particular fields
- See all contributions received by a committee, ordered by different fields (size, date, etc.)
- See who gave to orgs like Act Blue and who they in turn gave to
- Be able to export the data (different interest, but important as it comes up a lot)
- See who committees give to

Not sure if this helps the technical considerations, but wanted to capture it.

**Comment by noahmanger** [comment]
Also, maybe it'd be good to mock up some of the interactions we're hoping for just to make sure we're on the same page?

**Comment by LindsayYoung** [comment]
Mock up sound great!

Back to your points before:

 - Search across all contributions to all committees by particular fields like: name, employer, occupation, location
     - This could be limited to searching one cycle at a time
 - Search within a committees receipts to find contributions by particular fields
    - Receipts are schedule B - that will be a different endpoint
 - See all contributions received by a committee, ordered by different fields (size, date, etc.)
   - I think people could look at one cycle at a time
- See who gave to orgs like Act Blue and who they in turn gave to
    - In this example, aggregates are better to deal with. You would want to look at the memoed fields and then group by committee id to see how much Act Blue gave committee X
 - Be able to export the data (different interest, but important as it comes up a lot)
 - See who committees give to
    - Again, doing subtotals for committee to committee transfers is better for this than looking at the line items.

**Comment by noahmanger** [comment]
(My second point was worded weird: I mean the contributions received by a committee, so Schedule A).

**Comment by jmcarp** [comment]
I'm never going to say no to a mockup.

That said, though, this discussion is already helpful for thinking about technical issues. @arowla can correct me if I'm wrong on this, but it sounds like partitioning might not be flexible enough for these use cases--it's going to be pretty hard (probably impossible) to design partitions such that we're not often querying a large number or all of them at once, which sort of defeats the purpose.

Any thoughts about using approximate counts? Exact counts aren't too expensive for small queries, so I'm thinking we could get exact counts for queries with e.g. <1000 rows, and approximate counts (maybe plus or minus 10%) otherwise. Would that be a dealbreaker?

**Comment by noahmanger** [comment]
I agree that doing by cycle should probably be ok...or we'll learn that people want more! But my guess is that cycle by cycle is how this is going to work.

**Comment by noahmanger** [comment]
Re: Counts, that means counting the number of results a query returns? I bet approx counts are cool, especially if it's just for large sets (did you mean >1000?)

**Comment by LindsayYoung** [comment]
I think that approximate counts for large queries are fine with me, as long as that behavior is clear to the user. :+1:

**Comment by LindsayYoung** [comment]
A precise count isn't super useful from a reporting standpoint since it does not the number of donors. And if I was doing a story and needed that figure, I would round it anyway.

**Comment by noahmanger** [comment]
Here's the current [Individual Contributor Searchscreen](http://www.fec.gov/finance/disclosure/advindsea.shtml): 

![screen shot 2015-06-10 at 10 32 09 am](https://cloud.githubusercontent.com/assets/1696495/8089341/2d4522aa-0f5c-11e5-8c8b-673fe7e8ccd0.png)

I can def say we'll want to be able to have all of these fields as filters, right?

**Comment by jmcarp** [comment]
Re. approximate counts: @noahmanger, yep, I was thinking about using them for queries that we think have >1000 results, although that value would need to be tuned for performance. @LindsayYoung: counts are mostly used for pagination, so for a large result set, we might wind up saying there are 1000000 pages when there are really 950000.

Also, if we're all right with forcing every query to include a year or election cycle, partitioning over time could be useful. The search page that @noahmanger linked doesn't have this restriction, so maybe we shouldn't either. Also, that page is super slow! It took about 45 seconds to load all records from New York, and it didn't even give me a count!

**Comment by emileighoutlaw** [comment]
Hi all. Popping into this conversation: Not sure what the new page will look like, but after looking at the old screenshot I noticed, "zip code" 100% should be two words. There are probably a few other grammar considerations on old page, too.

**Comment by noahmanger** [comment]
One thing that could be neat would be able to filter by "Contributor Information" fields as well as by "Recipient Information" that would be not just Committee ID, but maybe the other committee fields as well. So that you could see all of the contributions a person named "Firstnamey Lastnamerson" gave to, say, PACs registered in California.

**Comment by LindsayYoung** [comment]
I like that idea, but I think we need to address a few other things first. 

We are not going to be doing a good job of finding contributions by individuals across different committees just using text search. Names and addresses are going to be reported differently in the data. So, adding this feature, in my opinion, be promising more than we can deliver, since we are not delivering "Firstnamey Lastnamerson" that well to begin with. 

One idea, to make that search better would be to use Alison's name cleaver behind the scenes. So we would return, the original data but we could normalize the search request use clean, normalized names and addresses behind the scenes for searching.

I don't think we would have to do that right away but it would be something to think about.

**Comment by noahmanger** [comment]
To be clear, I just meant you could search by a name and see all contributions reported by committees attached to that name. So taking as a given that we can't definitively link them to the same individual.

**Comment by LindsayYoung** [comment]
Yea, we will never be able to say it is the same person and we shouldn't attempt to.  

I just mean that if you are interested in a name it will appear as:
 - Firstnamey Lastnamerson
 - Firstnamey Lastnamerson Sr.
 - Firstnamey M Lastnamerson
 - First Lastnamerson

Personally, I wouldn't use this data to do the additional filtering that you mentioned until I trusted it to find the name I was looking for. That is why if I was still reporting, I would use Sunlight's search for this rather than ours until, I knew that I was getting equal or better results.

**Comment by noahmanger** [comment]
So here's a quick mock I had time to throw together:

The exact filters aren't necessarily right, but this should give you the picture. DataTables will be especially handy for these tables as I could imagine there being a _ton_ of columns, so making use of the ability to show or hide columns or nest them under collapsible rows could be nice.

![contribution filters](https://cloud.githubusercontent.com/assets/1696495/8091188/38abbaea-0f67-11e5-9e06-ff13c1a1808d.png)

**Comment by noahmanger** [comment]
I think there's a lot of behavior to figure out here. E.G. does the Committee Name or ID have Typeahead (I think it should). And if you fill it, does it make the filters below inactive? 

And then in general thinking about how we want to impose constraints to keep queries from getting out of control (if we need to).

**Comment by LindsayYoung** [comment]
That looks really good. I think typeahead is a great idea too!

**Comment by jmcarp** [comment]
I think the mockup looks great. Now we just have to figure out how to make the necessary database queries performant :smiley:

**Comment by emileighoutlaw** [comment]
@noahmanger Awesome mockup! Wondering if "Filters" in "Apply filters" should be capitalized, since you have "Individual Contributions" and "Filer Contributions" capitalized on that page? I think yes.
