### ISSUE TITLE
Termination reports included in reports endpoints

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#881]
The reports endpoints currently return all report types, including termination reports. But since termination reports don't include a coverage start date, or most other fields, this can lead to bugs in charts, including 500s.

Possible solutions:
* Always exclude termination reports from reports endpoints
* Add a query parameter (e.g. `exclude_types`) to endpoints to allow exclusion of termination reports

Thoughts @LindsayYoung?

**Comment by jmcarp** [comment]
Example: http://fec-dev-api.cf.18f.us/v1/committee/C00486647/reports?cycle=2012

**Comment by LindsayYoung** [comment]
I think it is an amendment problem that frequently shows up in Termination reports.

If an amendment doesn't have all the previous pages and just the part that is amended, we are getting null values for most of the fields. 

My instinct is to show termination reports as the most recent. Since this is really an amendment problem. If it is too much trouble, we could think of something else. 

I think the real fix would be to look at the form type and if it is adding or replacing a previous record and then, do the transformation. However, I don't see that any information like form type where we could look for "F3z" or an is amended flag etc.  I currently don't see anything that would tell us it this amendment is meant to add to or replace the form it is amending- just the expire date. I will follow up on the with the FEC. Hopefully, I am just missing something. 

Additionally, I think we might want the web-app to not break completely when there are null values. 

example of amended form:
http://docquery.fec.gov/pdf/333/12030812333/12030812333.pdf

**Comment by LindsayYoung** [comment]
Just reread the DW documentation and in 3.3 it looks like amendments in CDFM are supposed to be complete, and we are not supposed to have to fix them.
