### ISSUE TITLE
Add label to Glossary link at top of page

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#910]
The explanation of the Glossary (?) icon is currently at the bottom of the home page, so people don't get a description of what the icon does until they scroll down to the bottom of the home page.  User reported that it is not intuitive that it will open the glossary until/if you read the explanation.  The (?) icon without a label could be confused for a Help link instead.  Recommend adding a label next to the (?) icon indicating that it will open a glossary.

**Comment by noahmanger** [comment]
So this is something I want to do...but adding a label breaks the design. So going to spend some time today trying to figure out a solution.

**Comment by noahmanger** [comment]
Working on a few concepts here, but reluctant to spend too much more time on it considering it'll all be redone when we design the alpha site. But here goes:

## Option 1 - Search in header
![1 1](https://cloud.githubusercontent.com/assets/1696495/8171393/9feb122e-1385-11e5-97b0-bcf001b49a0b.png)

Clicking on "Search" transitions to the search bar taking over the middle of the header
![1 2](https://cloud.githubusercontent.com/assets/1696495/8171414/be8cb390-1385-11e5-9b07-3d1efe3c33da.png)

Collapse "candidates" and "committees" under a drop down
![1 3](https://cloud.githubusercontent.com/assets/1696495/8171415/c262edea-1385-11e5-9dc2-33e790f08657.png)

## Option 2 - Search in dropdown
![2 2](https://cloud.githubusercontent.com/assets/1696495/8171425/ce0c7cd8-1385-11e5-977a-e99f644c610e.png)

## Option 3 - Alt dropdown
![3 2](https://cloud.githubusercontent.com/assets/1696495/8171442/de0822ea-1385-11e5-99cf-a432159ffa44.png)
![3 3](https://cloud.githubusercontent.com/assets/1696495/8171441/de06b388-1385-11e5-98aa-1c90aa299bf2.png)

## Option 4 - Side menu
This would move the browse links and the search bar into an offscreen side menu, which could be consistent across all screen sizes. This is nice because it has consistency with the glossary panel.

![4 1](https://cloud.githubusercontent.com/assets/1696495/8171464/00070406-1386-11e5-9366-98aca0173537.png)
![4 2](https://cloud.githubusercontent.com/assets/1696495/8171463/0005b43e-1386-11e5-80ae-69488d8da7f4.png)

## Option 5 - Search in header (alt)
![5 1](https://cloud.githubusercontent.com/assets/1696495/8171470/0c90a678-1386-11e5-8ef3-cd74d88a9576.png)
![5 2](https://cloud.githubusercontent.com/assets/1696495/8171469/0c90734c-1386-11e5-9b72-5f430d3a437c.png)

## Option 6 - Full-screen search overlay
![6 1](https://cloud.githubusercontent.com/assets/1696495/8171472/124ceb62-1386-11e5-9c61-154a22bdceb8.png)
![6 2](https://cloud.githubusercontent.com/assets/1696495/8171471/124c054e-1386-11e5-9eae-8239d18e61c3.png)

**Comment by rdpiazza** [comment]
Hi @noahmanger -- Taking a look at these.  To better understand the problem we're trying to solve, can you clarify how adding the Glossary label breaks the design? Is it that there's not enough horizontal space for the label, or something else?

**Comment by noahmanger** [comment]
Sorry, yeah that's exactly it. It only all fits on a pretty wide display. Jennifer is helping by looking into a new icon for the glossary to see if that helps too.

**Comment by jenniferthibault** [comment]
Since the word won't fit, and it will likely open more worm cans to refactor the header if we're launching Thursday, here would be my suggestion:

Make the icon the book icon in the menu, but everywhere else inline where a term can be defined, use the info-alt icon. That gives more clues to that it's not a help tool, but a tool that provides more info. Mocked up here:

![artboard 1](https://cloud.githubusercontent.com/assets/11636908/8187612/b9728d46-141e-11e5-8628-180984d3bb0e.png)

**Comment by rdpiazza** [comment]
I like the book.  It's less ambiguous than the (?) icon.  I think this should wait for post-launch, however, so we can get the change approved and so we aren't making any changes so close to launch.

**Comment by jenniferthibault** [comment]
Who would need to approve this? I don't think it's entirely launch crucial, but also don't think it interferes with anything at the level of approval-needing, and would be easy (I think?) to incorporate.

**Comment by LindsayYoung** [comment]
This isn't the kind of thing FEC has insisted on approving in the past. The things pertaining to legal definitions need legal approval. Small changes that don' t impact legal definitions are constantly changing since we need to make adjustments as we go allong.

**Comment by noahmanger** [comment]
See a potential solution here: https://github.com/18F/openFEC-web-app/pull/277

**Comment by rdpiazza** [comment]
Really like the way the glossary icon looks, but I'd like to wait until the next iteration, since there could be things we'd overlook.  For example, if we change the image on the top of the bar, we'll also need to change the text and image for "Need Help Understanding the Terms?" on the home page.  Want to limit changes this close to go time.

**Comment by jmcarp** [comment]
No disagreement with delaying this, just to be cautious, but it looks like @noahmanger's patch includes those changes.

**Comment by leahbannon** [comment]
This issue is no longer relevant with the new designs.
